-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft_1024_top_fft_1024_top_Pipeline_VITIS_LOOP_47_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_TVALID : IN STD_LOGIC;
    input_r_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    input_r_TREADY : OUT STD_LOGIC;
    input_r_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    input_r_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    input_r_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    ga_M_real_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ga_M_real_V_ce0 : OUT STD_LOGIC;
    ga_M_real_V_we0 : OUT STD_LOGIC;
    ga_M_real_V_d0 : OUT STD_LOGIC_VECTOR (25 downto 0);
    ga_M_imag_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ga_M_imag_V_ce0 : OUT STD_LOGIC;
    ga_M_imag_V_we0 : OUT STD_LOGIC;
    ga_M_imag_V_d0 : OUT STD_LOGIC_VECTOR (25 downto 0);
    grp_fu_154_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_154_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_154_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_154_p_ce : OUT STD_LOGIC;
    grp_fu_158_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_158_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_158_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_158_p_ce : OUT STD_LOGIC;
    grp_fu_162_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_162_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_162_p_ce : OUT STD_LOGIC;
    grp_fu_165_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_165_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_165_p_ce : OUT STD_LOGIC );
end;


architecture behav of fft_1024_top_fft_1024_top_Pipeline_VITIS_LOOP_47_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_38800000 : STD_LOGIC_VECTOR (31 downto 0) := "00111000100000000000000000000000";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv54_0 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv12_433 : STD_LOGIC_VECTOR (11 downto 0) := "010000110011";
    constant ap_const_lv12_18 : STD_LOGIC_VECTOR (11 downto 0) := "000000011000";
    constant ap_const_lv12_FE8 : STD_LOGIC_VECTOR (11 downto 0) := "111111101000";
    constant ap_const_lv12_36 : STD_LOGIC_VECTOR (11 downto 0) := "000000110110";
    constant ap_const_lv12_1A : STD_LOGIC_VECTOR (11 downto 0) := "000000011010";
    constant ap_const_lv26_0 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv26_3FFFFFF : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln47_fu_156_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal input_r_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_3_reg_651 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_3_reg_651_pp0_iter1_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_3_reg_651_pp0_iter2_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_3_reg_651_pp0_iter3_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_3_reg_651_pp0_iter4_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_3_reg_651_pp0_iter5_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_3_reg_651_pp0_iter6_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_3_reg_651_pp0_iter7_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_3_reg_651_pp0_iter8_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_3_reg_651_pp0_iter9_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln293_fu_172_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln293_reg_660 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln293_1_reg_665 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_M_value_fu_191_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_M_value_4_fu_195_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal v_assign_reg_680 : STD_LOGIC_VECTOR (31 downto 0);
    signal v_assign_reg_680_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal v_assign_reg_680_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal v_assign_reg_680_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal v_assign_reg_680_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal v_assign_1_reg_686 : STD_LOGIC_VECTOR (31 downto 0);
    signal v_assign_1_reg_686_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal v_assign_1_reg_686_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal v_assign_1_reg_686_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal v_assign_1_reg_686_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_s_reg_692 : STD_LOGIC_VECTOR (0 downto 0);
    signal exp_tmp_reg_697 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln600_fu_225_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal trunc_ln600_reg_702 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln606_fu_229_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln606_reg_707 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln606_reg_707_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln606_reg_707_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_42_reg_714 : STD_LOGIC_VECTOR (0 downto 0);
    signal exp_tmp_2_reg_719 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln600_2_fu_261_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal trunc_ln600_2_reg_724 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln606_2_fu_265_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln606_2_reg_729 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln606_2_reg_729_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln606_2_reg_729_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal man_V_7_fu_291_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal man_V_7_reg_736 : STD_LOGIC_VECTOR (53 downto 0);
    signal man_V_7_reg_736_pp0_iter8_reg : STD_LOGIC_VECTOR (53 downto 0);
    signal sh_amt_fu_322_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sh_amt_reg_741 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln617_fu_330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln617_reg_748 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln618_fu_336_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln618_reg_753 : STD_LOGIC_VECTOR (25 downto 0);
    signal and_ln616_fu_351_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln616_reg_759 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln616_reg_759_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal man_V_10_fu_377_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal man_V_10_reg_764 : STD_LOGIC_VECTOR (53 downto 0);
    signal man_V_10_reg_764_pp0_iter8_reg : STD_LOGIC_VECTOR (53 downto 0);
    signal sh_amt_2_fu_408_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sh_amt_2_reg_769 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln617_2_fu_416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln617_2_reg_776 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln618_2_fu_422_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln618_2_reg_781 : STD_LOGIC_VECTOR (25 downto 0);
    signal and_ln616_1_fu_437_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln616_1_reg_787 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln616_1_reg_787_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln616_fu_443_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln616_reg_792 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln620_fu_446_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln620_reg_797 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln617_fu_483_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal select_ln617_reg_802 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln616_1_fu_490_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln616_1_reg_807 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln620_2_fu_493_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln620_2_reg_812 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln617_1_fu_530_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal select_ln617_1_reg_817 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_val_V_fu_581_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_val_V_reg_822 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_val_V_2_fu_632_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_val_V_2_reg_827 : STD_LOGIC_VECTOR (25 downto 0);
    signal i_cast_fu_639_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_90 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln47_fu_162_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_3 : STD_LOGIC_VECTOR (10 downto 0);
    signal ireg_fu_199_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln590_fu_203_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal ireg_2_fu_235_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln590_2_fu_239_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal p_Result_41_fu_274_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln604_fu_281_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal man_V_6_fu_285_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal zext_ln501_fu_271_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal F2_fu_298_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln616_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln616_fu_310_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln616_fu_316_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal or_ln617_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln617_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_43_fu_360_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln604_2_fu_367_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal man_V_9_fu_371_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal zext_ln501_2_fu_357_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal F2_2_fu_384_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln616_2_fu_390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln616_2_fu_396_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln616_2_fu_402_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal or_ln617_1_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln617_1_fu_431_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln616cast_fu_456_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal icmp_ln638_fu_451_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln639_fu_460_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal xor_ln606_fu_473_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln617_fu_478_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln638_fu_465_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln616_1cast_fu_503_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal icmp_ln638_2_fu_498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln639_2_fu_507_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal xor_ln606_1_fu_520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln617_1_fu_525_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln638_2_fu_512_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal zext_ln621_fu_537_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal ashr_ln621_fu_540_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal bitcast_ln768_fu_549_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_552_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln621_fu_545_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal select_ln623_fu_560_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal select_ln620_fu_568_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal select_ln616_fu_575_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal zext_ln621_2_fu_588_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal ashr_ln621_2_fu_591_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal bitcast_ln768_4_fu_600_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_16_fu_603_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln621_2_fu_596_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal select_ln623_2_fu_611_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal select_ln620_2_fu_619_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal select_ln616_2_fu_626_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_132_ce : STD_LOGIC;
    signal grp_fu_137_ce : STD_LOGIC;
    signal grp_fu_142_ce : STD_LOGIC;
    signal grp_fu_145_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fft_1024_top_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fft_1024_top_fpext_32ns_64_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component fft_1024_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component fft_1024_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    i_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln47_fu_156_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1))) then 
                    i_fu_90 <= add_ln47_fu_162_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_90 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln606_2_reg_729 = ap_const_lv1_0))) then
                and_ln616_1_reg_787 <= and_ln616_1_fu_437_p2;
                icmp_ln617_2_reg_776 <= icmp_ln617_2_fu_416_p2;
                man_V_10_reg_764 <= man_V_10_fu_377_p3;
                sh_amt_2_reg_769 <= sh_amt_2_fu_408_p3;
                trunc_ln618_2_reg_781 <= trunc_ln618_2_fu_422_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                and_ln616_1_reg_787_pp0_iter8_reg <= and_ln616_1_reg_787;
                and_ln616_reg_759_pp0_iter8_reg <= and_ln616_reg_759;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                exp_tmp_2_reg_719 <= ireg_2_fu_235_p1(62 downto 52);
                exp_tmp_reg_697 <= ireg_fu_199_p1(62 downto 52);
                i_3_reg_651_pp0_iter2_reg <= i_3_reg_651_pp0_iter1_reg;
                i_3_reg_651_pp0_iter3_reg <= i_3_reg_651_pp0_iter2_reg;
                i_3_reg_651_pp0_iter4_reg <= i_3_reg_651_pp0_iter3_reg;
                i_3_reg_651_pp0_iter5_reg <= i_3_reg_651_pp0_iter4_reg;
                i_3_reg_651_pp0_iter6_reg <= i_3_reg_651_pp0_iter5_reg;
                i_3_reg_651_pp0_iter7_reg <= i_3_reg_651_pp0_iter6_reg;
                i_3_reg_651_pp0_iter8_reg <= i_3_reg_651_pp0_iter7_reg;
                i_3_reg_651_pp0_iter9_reg <= i_3_reg_651_pp0_iter8_reg;
                icmp_ln606_2_reg_729 <= icmp_ln606_2_fu_265_p2;
                icmp_ln606_2_reg_729_pp0_iter7_reg <= icmp_ln606_2_reg_729;
                icmp_ln606_2_reg_729_pp0_iter8_reg <= icmp_ln606_2_reg_729_pp0_iter7_reg;
                icmp_ln606_reg_707 <= icmp_ln606_fu_229_p2;
                icmp_ln606_reg_707_pp0_iter7_reg <= icmp_ln606_reg_707;
                icmp_ln606_reg_707_pp0_iter8_reg <= icmp_ln606_reg_707_pp0_iter7_reg;
                man_V_10_reg_764_pp0_iter8_reg <= man_V_10_reg_764;
                man_V_7_reg_736_pp0_iter8_reg <= man_V_7_reg_736;
                p_Result_42_reg_714 <= ireg_2_fu_235_p1(63 downto 63);
                p_Result_s_reg_692 <= ireg_fu_199_p1(63 downto 63);
                p_val_V_2_reg_827 <= p_val_V_2_fu_632_p3;
                p_val_V_reg_822 <= p_val_V_fu_581_p3;
                trunc_ln600_2_reg_724 <= trunc_ln600_2_fu_261_p1;
                trunc_ln600_reg_702 <= trunc_ln600_fu_225_p1;
                v_assign_1_reg_686 <= grp_fu_158_p_dout0;
                v_assign_1_reg_686_pp0_iter5_reg <= v_assign_1_reg_686;
                v_assign_1_reg_686_pp0_iter6_reg <= v_assign_1_reg_686_pp0_iter5_reg;
                v_assign_1_reg_686_pp0_iter7_reg <= v_assign_1_reg_686_pp0_iter6_reg;
                v_assign_1_reg_686_pp0_iter8_reg <= v_assign_1_reg_686_pp0_iter7_reg;
                v_assign_reg_680 <= grp_fu_154_p_dout0;
                v_assign_reg_680_pp0_iter5_reg <= v_assign_reg_680;
                v_assign_reg_680_pp0_iter6_reg <= v_assign_reg_680_pp0_iter5_reg;
                v_assign_reg_680_pp0_iter7_reg <= v_assign_reg_680_pp0_iter6_reg;
                v_assign_reg_680_pp0_iter8_reg <= v_assign_reg_680_pp0_iter7_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln606_reg_707 = ap_const_lv1_0))) then
                and_ln616_reg_759 <= and_ln616_fu_351_p2;
                icmp_ln617_reg_748 <= icmp_ln617_fu_330_p2;
                man_V_7_reg_736 <= man_V_7_fu_291_p3;
                sh_amt_reg_741 <= sh_amt_fu_322_p3;
                trunc_ln618_reg_753 <= trunc_ln618_fu_336_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                i_3_reg_651 <= ap_sig_allocacmp_i_3;
                i_3_reg_651_pp0_iter1_reg <= i_3_reg_651;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln616_1_reg_787) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln606_2_reg_729_pp0_iter7_reg = ap_const_lv1_0))) then
                icmp_ln620_2_reg_812 <= icmp_ln620_2_fu_493_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln616_reg_759) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln606_reg_707_pp0_iter7_reg = ap_const_lv1_0))) then
                icmp_ln620_reg_797 <= icmp_ln620_fu_446_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_0 = and_ln616_1_reg_787) and (icmp_ln606_2_reg_729_pp0_iter7_reg = ap_const_lv1_0))) then
                select_ln617_1_reg_817 <= select_ln617_1_fu_530_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_0 = and_ln616_reg_759) and (icmp_ln606_reg_707_pp0_iter7_reg = ap_const_lv1_0))) then
                select_ln617_reg_802 <= select_ln617_fu_483_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln606_2_reg_729_pp0_iter7_reg = ap_const_lv1_0))) then
                sext_ln616_1_reg_807 <= sext_ln616_1_fu_490_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln606_reg_707_pp0_iter7_reg = ap_const_lv1_0))) then
                sext_ln616_reg_792 <= sext_ln616_fu_443_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln47_fu_156_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln293_1_reg_665 <= input_r_TDATA(63 downto 32);
                trunc_ln293_reg_660 <= trunc_ln293_fu_172_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    F2_2_fu_384_p2 <= std_logic_vector(unsigned(ap_const_lv12_433) - unsigned(zext_ln501_2_fu_357_p1));
    F2_fu_298_p2 <= std_logic_vector(unsigned(ap_const_lv12_433) - unsigned(zext_ln501_fu_271_p1));
    add_ln47_fu_162_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_3) + unsigned(ap_const_lv11_1));
    add_ln616_2_fu_396_p2 <= std_logic_vector(unsigned(F2_2_fu_384_p2) + unsigned(ap_const_lv12_FE8));
    add_ln616_fu_310_p2 <= std_logic_vector(unsigned(F2_fu_298_p2) + unsigned(ap_const_lv12_FE8));
    and_ln616_1_fu_437_p2 <= (xor_ln617_1_fu_431_p2 and icmp_ln616_2_fu_390_p2);
    and_ln616_fu_351_p2 <= (xor_ln617_fu_345_p2 and icmp_ln616_fu_304_p2);
    and_ln617_1_fu_525_p2 <= (xor_ln606_1_fu_520_p2 and icmp_ln617_2_reg_776);
    and_ln617_fu_478_p2 <= (xor_ln606_fu_473_p2 and icmp_ln617_reg_748);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(input_r_TVALID, icmp_ln47_fu_156_p2, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((icmp_ln47_fu_156_p2 = ap_const_lv1_0) and (input_r_TVALID = ap_const_logic_0) and (ap_start_int = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(input_r_TVALID, icmp_ln47_fu_156_p2, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((icmp_ln47_fu_156_p2 = ap_const_lv1_0) and (input_r_TVALID = ap_const_logic_0) and (ap_start_int = ap_const_logic_1));
    end process;

        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(input_r_TVALID, icmp_ln47_fu_156_p2)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((icmp_ln47_fu_156_p2 = ap_const_lv1_0) and (input_r_TVALID = ap_const_logic_0));
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln47_fu_156_p2, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln47_fu_156_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter9_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_90, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_3 <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_i_3 <= i_fu_90;
        end if; 
    end process;

    ashr_ln621_2_fu_591_p2 <= std_logic_vector(shift_right(signed(man_V_10_reg_764_pp0_iter8_reg),to_integer(unsigned('0' & zext_ln621_2_fu_588_p1(31-1 downto 0)))));
    ashr_ln621_fu_540_p2 <= std_logic_vector(shift_right(signed(man_V_7_reg_736_pp0_iter8_reg),to_integer(unsigned('0' & zext_ln621_fu_537_p1(31-1 downto 0)))));
    bitcast_ln768_4_fu_600_p1 <= v_assign_1_reg_686_pp0_iter8_reg;
    bitcast_ln768_fu_549_p1 <= v_assign_reg_680_pp0_iter8_reg;
    ga_M_imag_V_address0 <= i_cast_fu_639_p1(10 - 1 downto 0);

    ga_M_imag_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then 
            ga_M_imag_V_ce0 <= ap_const_logic_1;
        else 
            ga_M_imag_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    ga_M_imag_V_d0 <= p_val_V_2_reg_827;

    ga_M_imag_V_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then 
            ga_M_imag_V_we0 <= ap_const_logic_1;
        else 
            ga_M_imag_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    ga_M_real_V_address0 <= i_cast_fu_639_p1(10 - 1 downto 0);

    ga_M_real_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then 
            ga_M_real_V_ce0 <= ap_const_logic_1;
        else 
            ga_M_real_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    ga_M_real_V_d0 <= p_val_V_reg_822;

    ga_M_real_V_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then 
            ga_M_real_V_we0 <= ap_const_logic_1;
        else 
            ga_M_real_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_132_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_132_ce <= ap_const_logic_1;
        else 
            grp_fu_132_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_137_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_137_ce <= ap_const_logic_1;
        else 
            grp_fu_137_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_142_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_142_ce <= ap_const_logic_1;
        else 
            grp_fu_142_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_145_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_145_ce <= ap_const_logic_1;
        else 
            grp_fu_145_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_154_p_ce <= grp_fu_132_ce;
    grp_fu_154_p_din0 <= tmp_data_M_value_fu_191_p1;
    grp_fu_154_p_din1 <= ap_const_lv32_38800000;
    grp_fu_158_p_ce <= grp_fu_137_ce;
    grp_fu_158_p_din0 <= tmp_data_M_value_4_fu_195_p1;
    grp_fu_158_p_din1 <= ap_const_lv32_38800000;
    grp_fu_162_p_ce <= grp_fu_142_ce;
    grp_fu_162_p_din0 <= v_assign_reg_680;
    grp_fu_165_p_ce <= grp_fu_145_ce;
    grp_fu_165_p_din0 <= v_assign_1_reg_686;
    i_cast_fu_639_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_3_reg_651_pp0_iter9_reg),64));
    icmp_ln47_fu_156_p2 <= "1" when (ap_sig_allocacmp_i_3 = ap_const_lv11_400) else "0";
    icmp_ln606_2_fu_265_p2 <= "1" when (trunc_ln590_2_fu_239_p1 = ap_const_lv63_0) else "0";
    icmp_ln606_fu_229_p2 <= "1" when (trunc_ln590_fu_203_p1 = ap_const_lv63_0) else "0";
    icmp_ln616_2_fu_390_p2 <= "1" when (signed(F2_2_fu_384_p2) > signed(ap_const_lv12_18)) else "0";
    icmp_ln616_fu_304_p2 <= "1" when (signed(F2_fu_298_p2) > signed(ap_const_lv12_18)) else "0";
    icmp_ln617_2_fu_416_p2 <= "1" when (F2_2_fu_384_p2 = ap_const_lv12_18) else "0";
    icmp_ln617_fu_330_p2 <= "1" when (F2_fu_298_p2 = ap_const_lv12_18) else "0";
    icmp_ln620_2_fu_493_p2 <= "1" when (unsigned(sh_amt_2_reg_769) < unsigned(ap_const_lv12_36)) else "0";
    icmp_ln620_fu_446_p2 <= "1" when (unsigned(sh_amt_reg_741) < unsigned(ap_const_lv12_36)) else "0";
    icmp_ln638_2_fu_498_p2 <= "1" when (unsigned(sh_amt_2_reg_769) < unsigned(ap_const_lv12_1A)) else "0";
    icmp_ln638_fu_451_p2 <= "1" when (unsigned(sh_amt_reg_741) < unsigned(ap_const_lv12_1A)) else "0";

    input_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, input_r_TVALID, icmp_ln47_fu_156_p2, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln47_fu_156_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_r_TDATA_blk_n <= input_r_TVALID;
        else 
            input_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    input_r_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln47_fu_156_p2, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln47_fu_156_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_r_TREADY <= ap_const_logic_1;
        else 
            input_r_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    ireg_2_fu_235_p1 <= grp_fu_165_p_dout0;
    ireg_fu_199_p1 <= grp_fu_162_p_dout0;
    man_V_10_fu_377_p3 <= 
        man_V_9_fu_371_p2 when (p_Result_42_reg_714(0) = '1') else 
        zext_ln604_2_fu_367_p1;
    man_V_6_fu_285_p2 <= std_logic_vector(unsigned(ap_const_lv54_0) - unsigned(zext_ln604_fu_281_p1));
    man_V_7_fu_291_p3 <= 
        man_V_6_fu_285_p2 when (p_Result_s_reg_692(0) = '1') else 
        zext_ln604_fu_281_p1;
    man_V_9_fu_371_p2 <= std_logic_vector(unsigned(ap_const_lv54_0) - unsigned(zext_ln604_2_fu_367_p1));
    or_ln617_1_fu_426_p2 <= (icmp_ln617_2_fu_416_p2 or icmp_ln606_2_reg_729);
    or_ln617_fu_340_p2 <= (icmp_ln617_fu_330_p2 or icmp_ln606_reg_707);
    p_Result_41_fu_274_p3 <= (ap_const_lv1_1 & trunc_ln600_reg_702);
    p_Result_43_fu_360_p3 <= (ap_const_lv1_1 & trunc_ln600_2_reg_724);
    p_val_V_2_fu_632_p3 <= 
        ap_const_lv26_0 when (icmp_ln606_2_reg_729_pp0_iter8_reg(0) = '1') else 
        select_ln616_2_fu_626_p3;
    p_val_V_fu_581_p3 <= 
        ap_const_lv26_0 when (icmp_ln606_reg_707_pp0_iter8_reg(0) = '1') else 
        select_ln616_fu_575_p3;
    select_ln616_2_fu_626_p3 <= 
        select_ln620_2_fu_619_p3 when (and_ln616_1_reg_787_pp0_iter8_reg(0) = '1') else 
        select_ln617_1_reg_817;
    select_ln616_fu_575_p3 <= 
        select_ln620_fu_568_p3 when (and_ln616_reg_759_pp0_iter8_reg(0) = '1') else 
        select_ln617_reg_802;
    select_ln617_1_fu_530_p3 <= 
        trunc_ln618_2_reg_781 when (and_ln617_1_fu_525_p2(0) = '1') else 
        select_ln638_2_fu_512_p3;
    select_ln617_fu_483_p3 <= 
        trunc_ln618_reg_753 when (and_ln617_fu_478_p2(0) = '1') else 
        select_ln638_fu_465_p3;
    select_ln620_2_fu_619_p3 <= 
        trunc_ln621_2_fu_596_p1 when (icmp_ln620_2_reg_812(0) = '1') else 
        select_ln623_2_fu_611_p3;
    select_ln620_fu_568_p3 <= 
        trunc_ln621_fu_545_p1 when (icmp_ln620_reg_797(0) = '1') else 
        select_ln623_fu_560_p3;
    select_ln623_2_fu_611_p3 <= 
        ap_const_lv26_3FFFFFF when (tmp_16_fu_603_p3(0) = '1') else 
        ap_const_lv26_0;
    select_ln623_fu_560_p3 <= 
        ap_const_lv26_3FFFFFF when (tmp_fu_552_p3(0) = '1') else 
        ap_const_lv26_0;
    select_ln638_2_fu_512_p3 <= 
        shl_ln639_2_fu_507_p2 when (icmp_ln638_2_fu_498_p2(0) = '1') else 
        ap_const_lv26_0;
    select_ln638_fu_465_p3 <= 
        shl_ln639_fu_460_p2 when (icmp_ln638_fu_451_p2(0) = '1') else 
        ap_const_lv26_0;
        sext_ln616_1_fu_490_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sh_amt_2_reg_769),32));

    sext_ln616_1cast_fu_503_p1 <= sext_ln616_1_fu_490_p1(26 - 1 downto 0);
        sext_ln616_fu_443_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sh_amt_reg_741),32));

    sext_ln616cast_fu_456_p1 <= sext_ln616_fu_443_p1(26 - 1 downto 0);
    sh_amt_2_fu_408_p3 <= 
        add_ln616_2_fu_396_p2 when (icmp_ln616_2_fu_390_p2(0) = '1') else 
        sub_ln616_2_fu_402_p2;
    sh_amt_fu_322_p3 <= 
        add_ln616_fu_310_p2 when (icmp_ln616_fu_304_p2(0) = '1') else 
        sub_ln616_fu_316_p2;
    shl_ln639_2_fu_507_p2 <= std_logic_vector(shift_left(unsigned(trunc_ln618_2_reg_781),to_integer(unsigned('0' & sext_ln616_1cast_fu_503_p1(26-1 downto 0)))));
    shl_ln639_fu_460_p2 <= std_logic_vector(shift_left(unsigned(trunc_ln618_reg_753),to_integer(unsigned('0' & sext_ln616cast_fu_456_p1(26-1 downto 0)))));
    sub_ln616_2_fu_402_p2 <= std_logic_vector(unsigned(ap_const_lv12_18) - unsigned(F2_2_fu_384_p2));
    sub_ln616_fu_316_p2 <= std_logic_vector(unsigned(ap_const_lv12_18) - unsigned(F2_fu_298_p2));
    tmp_16_fu_603_p3 <= bitcast_ln768_4_fu_600_p1(31 downto 31);
    tmp_data_M_value_4_fu_195_p1 <= trunc_ln293_1_reg_665;
    tmp_data_M_value_fu_191_p1 <= trunc_ln293_reg_660;
    tmp_fu_552_p3 <= bitcast_ln768_fu_549_p1(31 downto 31);
    trunc_ln293_fu_172_p1 <= input_r_TDATA(32 - 1 downto 0);
    trunc_ln590_2_fu_239_p1 <= ireg_2_fu_235_p1(63 - 1 downto 0);
    trunc_ln590_fu_203_p1 <= ireg_fu_199_p1(63 - 1 downto 0);
    trunc_ln600_2_fu_261_p1 <= ireg_2_fu_235_p1(52 - 1 downto 0);
    trunc_ln600_fu_225_p1 <= ireg_fu_199_p1(52 - 1 downto 0);
    trunc_ln618_2_fu_422_p1 <= man_V_10_fu_377_p3(26 - 1 downto 0);
    trunc_ln618_fu_336_p1 <= man_V_7_fu_291_p3(26 - 1 downto 0);
    trunc_ln621_2_fu_596_p1 <= ashr_ln621_2_fu_591_p2(26 - 1 downto 0);
    trunc_ln621_fu_545_p1 <= ashr_ln621_fu_540_p2(26 - 1 downto 0);
    xor_ln606_1_fu_520_p2 <= (icmp_ln606_2_reg_729_pp0_iter7_reg xor ap_const_lv1_1);
    xor_ln606_fu_473_p2 <= (icmp_ln606_reg_707_pp0_iter7_reg xor ap_const_lv1_1);
    xor_ln617_1_fu_431_p2 <= (or_ln617_1_fu_426_p2 xor ap_const_lv1_1);
    xor_ln617_fu_345_p2 <= (or_ln617_fu_340_p2 xor ap_const_lv1_1);
    zext_ln501_2_fu_357_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_tmp_2_reg_719),12));
    zext_ln501_fu_271_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_tmp_reg_697),12));
    zext_ln604_2_fu_367_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_43_fu_360_p3),54));
    zext_ln604_fu_281_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_41_fu_274_p3),54));
    zext_ln621_2_fu_588_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln616_1_reg_807),54));
    zext_ln621_fu_537_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln616_reg_792),54));
end behav;
