// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="trigger_ip_trigger_ip,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=4.995000,HLS_SYN_LAT=2,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=161,HLS_SYN_LUT=182,HLS_VERSION=2022_1}" *)

module trigger_ip (
        ap_clk,
        ap_rst_n,
        s_axis_in_TVALID,
        m_axis_out_TREADY,
        s_axis_in_TDATA,
        s_axis_in_TREADY,
        s_axis_in_TKEEP,
        s_axis_in_TSTRB,
        s_axis_in_TLAST,
        m_axis_out_TDATA,
        m_axis_out_TVALID,
        m_axis_out_TKEEP,
        m_axis_out_TSTRB,
        m_axis_out_TLAST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axis_in_TVALID;
input   m_axis_out_TREADY;
input  [63:0] s_axis_in_TDATA;
output   s_axis_in_TREADY;
input  [7:0] s_axis_in_TKEEP;
input  [7:0] s_axis_in_TSTRB;
input  [0:0] s_axis_in_TLAST;
output  [63:0] m_axis_out_TDATA;
output   m_axis_out_TVALID;
output  [7:0] m_axis_out_TKEEP;
output  [7:0] m_axis_out_TSTRB;
output  [0:0] m_axis_out_TLAST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_ready;
wire   [0:0] sync_reset_read_read_fu_82_p2;
reg    ap_predicate_op27_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] sync_reset_read_reg_215;
reg   [0:0] done_V_load_reg_219;
reg    ap_predicate_op50_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
reg   [0:0] sync_reset_read_reg_215_pp0_iter1_reg;
reg   [0:0] done_V_load_reg_219_pp0_iter1_reg;
reg    ap_predicate_op55_write_state3;
wire    regslice_both_m_axis_out_V_data_V_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] sync_reset;
reg   [0:0] trigger_done;
reg    trigger_done_ap_vld;
reg   [15:0] samp_cnt_V;
reg   [4:0] batch_cnt_V;
reg   [0:0] done_V;
reg    ap_block_pp0_stage0_11001;
reg    s_axis_in_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    m_axis_out_TDATA_blk_n;
reg   [63:0] p_0_reg_223;
reg   [7:0] tmp_keep_V_reg_228;
reg   [7:0] tmp_strb_V_reg_233;
wire   [0:0] last_of_batch_fu_145_p2;
reg   [0:0] last_of_batch_reg_238;
wire   [0:0] icmp_ln1065_fu_173_p2;
reg   [0:0] icmp_ln1065_reg_243;
wire   [15:0] add_ln886_fu_151_p2;
wire   [4:0] add_ln886_1_fu_179_p2;
reg    ap_block_pp0_stage0_01001;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_s_axis_in_V_data_V_U_apdone_blk;
wire   [63:0] s_axis_in_TDATA_int_regslice;
wire    s_axis_in_TVALID_int_regslice;
reg    s_axis_in_TREADY_int_regslice;
wire    regslice_both_s_axis_in_V_data_V_U_ack_in;
wire    regslice_both_s_axis_in_V_keep_V_U_apdone_blk;
wire   [7:0] s_axis_in_TKEEP_int_regslice;
wire    regslice_both_s_axis_in_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_in_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_in_V_strb_V_U_apdone_blk;
wire   [7:0] s_axis_in_TSTRB_int_regslice;
wire    regslice_both_s_axis_in_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_in_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_in_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_in_TLAST_int_regslice;
wire    regslice_both_s_axis_in_V_last_V_U_vld_out;
wire    regslice_both_s_axis_in_V_last_V_U_ack_in;
reg    m_axis_out_TVALID_int_regslice;
wire    m_axis_out_TREADY_int_regslice;
wire    regslice_both_m_axis_out_V_data_V_U_vld_out;
wire    regslice_both_m_axis_out_V_keep_V_U_apdone_blk;
wire    regslice_both_m_axis_out_V_keep_V_U_ack_in_dummy;
wire    regslice_both_m_axis_out_V_keep_V_U_vld_out;
wire    regslice_both_m_axis_out_V_strb_V_U_apdone_blk;
wire    regslice_both_m_axis_out_V_strb_V_U_ack_in_dummy;
wire    regslice_both_m_axis_out_V_strb_V_U_vld_out;
wire    regslice_both_m_axis_out_V_last_V_U_apdone_blk;
wire    regslice_both_m_axis_out_V_last_V_U_ack_in_dummy;
wire    regslice_both_m_axis_out_V_last_V_U_vld_out;
reg    ap_condition_203;
reg    ap_condition_190;
reg    ap_condition_209;
reg    ap_condition_232;
reg    ap_condition_226;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 samp_cnt_V = 16'd0;
#0 batch_cnt_V = 5'd0;
#0 done_V = 1'd0;
end

trigger_ip_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .sync_reset(sync_reset),
    .trigger_done(trigger_done),
    .trigger_done_ap_vld(trigger_done_ap_vld),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

trigger_ip_regslice_both #(
    .DataWidth( 64 ))
regslice_both_s_axis_in_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_in_TDATA),
    .vld_in(s_axis_in_TVALID),
    .ack_in(regslice_both_s_axis_in_V_data_V_U_ack_in),
    .data_out(s_axis_in_TDATA_int_regslice),
    .vld_out(s_axis_in_TVALID_int_regslice),
    .ack_out(s_axis_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_in_V_data_V_U_apdone_blk)
);

trigger_ip_regslice_both #(
    .DataWidth( 8 ))
regslice_both_s_axis_in_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_in_TKEEP),
    .vld_in(s_axis_in_TVALID),
    .ack_in(regslice_both_s_axis_in_V_keep_V_U_ack_in),
    .data_out(s_axis_in_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_in_V_keep_V_U_vld_out),
    .ack_out(s_axis_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_in_V_keep_V_U_apdone_blk)
);

trigger_ip_regslice_both #(
    .DataWidth( 8 ))
regslice_both_s_axis_in_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_in_TSTRB),
    .vld_in(s_axis_in_TVALID),
    .ack_in(regslice_both_s_axis_in_V_strb_V_U_ack_in),
    .data_out(s_axis_in_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_in_V_strb_V_U_vld_out),
    .ack_out(s_axis_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_in_V_strb_V_U_apdone_blk)
);

trigger_ip_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_in_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_in_TLAST),
    .vld_in(s_axis_in_TVALID),
    .ack_in(regslice_both_s_axis_in_V_last_V_U_ack_in),
    .data_out(s_axis_in_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_in_V_last_V_U_vld_out),
    .ack_out(s_axis_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_in_V_last_V_U_apdone_blk)
);

trigger_ip_regslice_both #(
    .DataWidth( 64 ))
regslice_both_m_axis_out_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(p_0_reg_223),
    .vld_in(m_axis_out_TVALID_int_regslice),
    .ack_in(m_axis_out_TREADY_int_regslice),
    .data_out(m_axis_out_TDATA),
    .vld_out(regslice_both_m_axis_out_V_data_V_U_vld_out),
    .ack_out(m_axis_out_TREADY),
    .apdone_blk(regslice_both_m_axis_out_V_data_V_U_apdone_blk)
);

trigger_ip_regslice_both #(
    .DataWidth( 8 ))
regslice_both_m_axis_out_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_keep_V_reg_228),
    .vld_in(m_axis_out_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_out_V_keep_V_U_ack_in_dummy),
    .data_out(m_axis_out_TKEEP),
    .vld_out(regslice_both_m_axis_out_V_keep_V_U_vld_out),
    .ack_out(m_axis_out_TREADY),
    .apdone_blk(regslice_both_m_axis_out_V_keep_V_U_apdone_blk)
);

trigger_ip_regslice_both #(
    .DataWidth( 8 ))
regslice_both_m_axis_out_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_strb_V_reg_233),
    .vld_in(m_axis_out_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_out_V_strb_V_U_ack_in_dummy),
    .data_out(m_axis_out_TSTRB),
    .vld_out(regslice_both_m_axis_out_V_strb_V_U_vld_out),
    .ack_out(m_axis_out_TREADY),
    .apdone_blk(regslice_both_m_axis_out_V_strb_V_U_apdone_blk)
);

trigger_ip_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_out_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(last_of_batch_reg_238),
    .vld_in(m_axis_out_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_out_V_last_V_U_ack_in_dummy),
    .data_out(m_axis_out_TLAST),
    .vld_out(regslice_both_m_axis_out_V_last_V_U_vld_out),
    .ack_out(m_axis_out_TREADY),
    .apdone_blk(regslice_both_m_axis_out_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_190)) begin
        if ((sync_reset_read_read_fu_82_p2 == 1'd1)) begin
            batch_cnt_V <= 5'd0;
        end else if ((1'b1 == ap_condition_203)) begin
            batch_cnt_V <= add_ln886_1_fu_179_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_190)) begin
        if ((sync_reset_read_read_fu_82_p2 == 1'd1)) begin
            done_V <= 1'd0;
        end else if ((1'b1 == ap_condition_209)) begin
            done_V <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (done_V == 1'd0) & (sync_reset == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (last_of_batch_fu_145_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (sync_reset_read_read_fu_82_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        samp_cnt_V <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (done_V == 1'd0) & (sync_reset == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (last_of_batch_fu_145_p2 == 1'd0))) begin
        samp_cnt_V <= add_ln886_fu_151_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (sync_reset == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        done_V_load_reg_219 <= done_V;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        done_V_load_reg_219_pp0_iter1_reg <= done_V_load_reg_219;
        sync_reset_read_reg_215 <= sync_reset;
        sync_reset_read_reg_215_pp0_iter1_reg <= sync_reset_read_reg_215;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (done_V == 1'd0) & (sync_reset == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (last_of_batch_fu_145_p2 == 1'd1))) begin
        icmp_ln1065_reg_243 <= icmp_ln1065_fu_173_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (done_V == 1'd0) & (sync_reset == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        last_of_batch_reg_238 <= last_of_batch_fu_145_p2;
        p_0_reg_223 <= s_axis_in_TDATA_int_regslice;
        tmp_keep_V_reg_228 <= s_axis_in_TKEEP_int_regslice;
        tmp_strb_V_reg_233 <= s_axis_in_TSTRB_int_regslice;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op55_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op50_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        m_axis_out_TDATA_blk_n = m_axis_out_TREADY_int_regslice;
    end else begin
        m_axis_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op50_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axis_out_TVALID_int_regslice = 1'b1;
    end else begin
        m_axis_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op27_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_axis_in_TDATA_blk_n = s_axis_in_TVALID_int_regslice;
    end else begin
        s_axis_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op27_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_axis_in_TREADY_int_regslice = 1'b1;
    end else begin
        s_axis_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_226)) begin
        if ((sync_reset_read_reg_215 == 1'd1)) begin
            trigger_done = 1'd0;
        end else if ((1'b1 == ap_condition_232)) begin
            trigger_done = 1'd1;
        end else begin
            trigger_done = 'bx;
        end
    end else begin
        trigger_done = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (done_V_load_reg_219 == 1'd0) & (sync_reset_read_reg_215 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1065_reg_243 == 1'd1) & (last_of_batch_reg_238 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (sync_reset_read_reg_215 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        trigger_done_ap_vld = 1'b1;
    end else begin
        trigger_done_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln886_1_fu_179_p2 = (batch_cnt_V + 5'd1);

assign add_ln886_fu_151_p2 = (samp_cnt_V + 16'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((regslice_both_m_axis_out_V_data_V_U_apdone_blk == 1'b1) | ((ap_predicate_op55_write_state3 == 1'b1) & (m_axis_out_TREADY_int_regslice == 1'b0)))) | ((ap_predicate_op50_write_state2 == 1'b1) & (m_axis_out_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_predicate_op27_read_state1 == 1'b1) & (s_axis_in_TVALID_int_regslice == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((regslice_both_m_axis_out_V_data_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op55_write_state3 == 1'b1) & (m_axis_out_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op50_write_state2 == 1'b1) & (m_axis_out_TREADY_int_regslice == 1'b0)))) | ((ap_predicate_op27_read_state1 == 1'b1) & (s_axis_in_TVALID_int_regslice == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((regslice_both_m_axis_out_V_data_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op55_write_state3 == 1'b1) & (m_axis_out_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op50_write_state2 == 1'b1) & (m_axis_out_TREADY_int_regslice == 1'b0)))) | ((ap_predicate_op27_read_state1 == 1'b1) & (s_axis_in_TVALID_int_regslice == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_predicate_op27_read_state1 == 1'b1) & (s_axis_in_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2_io = ((ap_predicate_op50_write_state2 == 1'b1) & (m_axis_out_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op50_write_state2 == 1'b1) & (m_axis_out_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_io = ((ap_predicate_op55_write_state3 == 1'b1) & (m_axis_out_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((regslice_both_m_axis_out_V_data_V_U_apdone_blk == 1'b1) | ((ap_predicate_op55_write_state3 == 1'b1) & (m_axis_out_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_condition_190 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_203 = ((done_V == 1'd0) & (sync_reset == 1'd0) & (icmp_ln1065_fu_173_p2 == 1'd0) & (last_of_batch_fu_145_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_209 = ((done_V == 1'd0) & (sync_reset == 1'd0) & (icmp_ln1065_fu_173_p2 == 1'd1) & (last_of_batch_fu_145_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_226 = ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_232 = ((done_V_load_reg_219 == 1'd0) & (sync_reset_read_reg_215 == 1'd0) & (icmp_ln1065_reg_243 == 1'd1) & (last_of_batch_reg_238 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

always @ (*) begin
    ap_predicate_op27_read_state1 = ((done_V == 1'd0) & (sync_reset == 1'd0));
end

always @ (*) begin
    ap_predicate_op50_write_state2 = ((done_V_load_reg_219 == 1'd0) & (sync_reset_read_reg_215 == 1'd0));
end

always @ (*) begin
    ap_predicate_op55_write_state3 = ((done_V_load_reg_219_pp0_iter1_reg == 1'd0) & (sync_reset_read_reg_215_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign icmp_ln1065_fu_173_p2 = ((batch_cnt_V == 5'd15) ? 1'b1 : 1'b0);

assign last_of_batch_fu_145_p2 = ((samp_cnt_V == 16'd32767) ? 1'b1 : 1'b0);

assign m_axis_out_TVALID = regslice_both_m_axis_out_V_data_V_U_vld_out;

assign s_axis_in_TREADY = regslice_both_s_axis_in_V_data_V_U_ack_in;

assign sync_reset_read_read_fu_82_p2 = sync_reset;


reg find_kernel_block = 0;
// synthesis translate_off
`include "trigger_ip_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //trigger_ip

