
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xtrigger_ip.h"

/*
* The configuration table for devices
*/

XTrigger_ip_Config XTrigger_ip_ConfigTable[XPAR_XTRIGGER_IP_NUM_INSTANCES] =
{
	{
		XPAR_TRIGGER_IP_0_DEVICE_ID,
		XPAR_TRIGGER_IP_0_S_AXI_CONTROL_BASEADDR
	}
};


