// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fft_1024_top_fft_fast_Pipeline_VITIS_LOOP_21_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m2,
        trunc_ln20_1,
        trunc_ln20_2,
        x_M_real_address0,
        x_M_real_ce0,
        x_M_real_we0,
        x_M_real_d0,
        x_M_real_q0,
        x_M_real_address1,
        x_M_real_ce1,
        x_M_real_we1,
        x_M_real_d1,
        x_M_real_q1,
        x_M_imag_address0,
        x_M_imag_ce0,
        x_M_imag_we0,
        x_M_imag_d0,
        x_M_imag_q0,
        x_M_imag_address1,
        x_M_imag_ce1,
        x_M_imag_we1,
        x_M_imag_d1,
        x_M_imag_q1
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [9:0] m2;
input  [9:0] trunc_ln20_1;
input  [9:0] trunc_ln20_2;
output  [9:0] x_M_real_address0;
output   x_M_real_ce0;
output   x_M_real_we0;
output  [25:0] x_M_real_d0;
input  [25:0] x_M_real_q0;
output  [9:0] x_M_real_address1;
output   x_M_real_ce1;
output   x_M_real_we1;
output  [25:0] x_M_real_d1;
input  [25:0] x_M_real_q1;
output  [9:0] x_M_imag_address0;
output   x_M_imag_ce0;
output   x_M_imag_we0;
output  [25:0] x_M_imag_d0;
input  [25:0] x_M_imag_q0;
output  [9:0] x_M_imag_address1;
output   x_M_imag_ce1;
output   x_M_imag_we1;
output  [25:0] x_M_imag_d1;
input  [25:0] x_M_imag_q1;

reg ap_idle;
reg[9:0] x_M_real_address0;
reg x_M_real_ce0;
reg x_M_real_we0;
reg[9:0] x_M_real_address1;
reg x_M_real_ce1;
reg x_M_real_we1;
reg[9:0] x_M_imag_address0;
reg x_M_imag_ce0;
reg x_M_imag_we0;
reg[9:0] x_M_imag_address1;
reg x_M_imag_ce1;
reg x_M_imag_we1;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln21_fu_158_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state6;
wire    ap_block_state6_pp0_stage5_iter0;
wire   [9:0] tw_M_real_V_address0;
reg    tw_M_real_V_ce0;
wire   [23:0] tw_M_real_V_q0;
wire   [9:0] tw_M_imag_V_address0;
reg    tw_M_imag_V_ce0;
wire   [23:0] tw_M_imag_V_q0;
reg   [9:0] x_M_real_addr_reg_331;
reg   [9:0] x_M_imag_addr_reg_336;
reg   [9:0] x_M_real_addr_2_reg_341;
reg   [9:0] x_M_imag_addr_2_reg_346;
reg   [23:0] tw_M_real_V_load_reg_351;
wire    ap_CS_fsm_state2;
wire    ap_block_state2_pp0_stage1_iter0;
reg   [23:0] tw_M_imag_V_load_reg_356;
reg  signed [25:0] x_M_real_load_reg_361;
reg  signed [25:0] x_M_imag_load_reg_366;
reg   [25:0] u_M_real_V_reg_371;
reg   [25:0] u_M_imag_V_reg_377;
wire   [49:0] r_V_1_fu_232_p2;
reg   [49:0] r_V_1_reg_383;
wire    ap_CS_fsm_state3;
wire    ap_block_state3_pp0_stage2_iter0;
wire   [49:0] r_V_3_fu_245_p2;
reg   [49:0] r_V_3_reg_388;
wire   [49:0] r_V_4_fu_251_p2;
reg   [49:0] r_V_4_reg_393;
wire   [49:0] r_V_5_fu_257_p2;
reg   [49:0] r_V_5_reg_398;
reg   [25:0] tm_re_V_reg_403;
wire    ap_CS_fsm_state4;
wire    ap_block_state4_pp0_stage3_iter0;
reg   [25:0] tm_im_V_reg_409;
wire   [63:0] zext_ln883_fu_176_p1;
wire   [63:0] zext_ln24_1_fu_200_p1;
wire   [63:0] zext_ln24_fu_188_p1;
reg   [9:0] j_fu_52;
wire   [9:0] add_ln21_fu_164_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_j_1;
wire    ap_CS_fsm_state5;
wire    ap_block_state5_pp0_stage4_iter0;
wire   [9:0] add_ln22_fu_170_p2;
wire   [9:0] add_ln24_fu_182_p2;
wire   [9:0] add_ln24_1_fu_194_p2;
wire   [25:0] tw_re_fu_211_p3;
wire  signed [25:0] r_V_1_fu_232_p0;
wire  signed [49:0] sext_ln1319_fu_229_p1;
wire  signed [25:0] r_V_1_fu_232_p1;
wire  signed [49:0] sext_ln1316_fu_225_p1;
wire   [25:0] tw_im_V_fu_218_p3;
wire  signed [25:0] r_V_3_fu_245_p0;
wire  signed [49:0] sext_ln1319_1_fu_242_p1;
wire  signed [25:0] r_V_3_fu_245_p1;
wire  signed [49:0] sext_ln1316_1_fu_238_p1;
wire  signed [25:0] r_V_4_fu_251_p0;
wire  signed [25:0] r_V_4_fu_251_p1;
wire  signed [25:0] r_V_5_fu_257_p0;
wire  signed [25:0] r_V_5_fu_257_p1;
wire   [49:0] ret_V_fu_263_p2;
wire   [49:0] ret_V_1_fu_277_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 ap_done_reg = 1'b0;
end

fft_1024_top_fft_fast_Pipeline_VITIS_LOOP_21_4_tw_M_real_V_ROM_AUTO_1R #(
    .DataWidth( 24 ),
    .AddressRange( 1023 ),
    .AddressWidth( 10 ))
tw_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tw_M_real_V_address0),
    .ce0(tw_M_real_V_ce0),
    .q0(tw_M_real_V_q0)
);

fft_1024_top_fft_fast_Pipeline_VITIS_LOOP_21_4_tw_M_imag_V_ROM_AUTO_1R #(
    .DataWidth( 24 ),
    .AddressRange( 1023 ),
    .AddressWidth( 10 ))
tw_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tw_M_imag_V_address0),
    .ce0(tw_M_imag_V_ce0),
    .q0(tw_M_imag_V_q0)
);

fft_1024_top_mul_26s_26s_50_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 50 ))
mul_26s_26s_50_1_1_U24(
    .din0(r_V_1_fu_232_p0),
    .din1(r_V_1_fu_232_p1),
    .dout(r_V_1_fu_232_p2)
);

fft_1024_top_mul_26s_26s_50_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 50 ))
mul_26s_26s_50_1_1_U25(
    .din0(r_V_3_fu_245_p0),
    .din1(r_V_3_fu_245_p1),
    .dout(r_V_3_fu_245_p2)
);

fft_1024_top_mul_26s_26s_50_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 50 ))
mul_26s_26s_50_1_1_U26(
    .din0(r_V_4_fu_251_p0),
    .din1(r_V_4_fu_251_p1),
    .dout(r_V_4_fu_251_p2)
);

fft_1024_top_mul_26s_26s_50_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 50 ))
mul_26s_26s_50_1_1_U27(
    .din0(r_V_5_fu_257_p0),
    .din1(r_V_5_fu_257_p1),
    .dout(r_V_5_fu_257_p2)
);

fft_1024_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln21_fu_158_p2 == 1'd0)) begin
            j_fu_52 <= add_ln21_fu_164_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_52 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        r_V_1_reg_383 <= r_V_1_fu_232_p2;
        r_V_3_reg_388 <= r_V_3_fu_245_p2;
        r_V_4_reg_393 <= r_V_4_fu_251_p2;
        r_V_5_reg_398 <= r_V_5_fu_257_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tm_im_V_reg_409 <= {{ret_V_1_fu_277_p2[49:24]}};
        tm_re_V_reg_403 <= {{ret_V_fu_263_p2[49:24]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tw_M_imag_V_load_reg_356 <= tw_M_imag_V_q0;
        tw_M_real_V_load_reg_351 <= tw_M_real_V_q0;
        u_M_imag_V_reg_377 <= x_M_imag_q0;
        u_M_real_V_reg_371 <= x_M_real_q0;
        x_M_imag_load_reg_366 <= x_M_imag_q1;
        x_M_real_load_reg_361 <= x_M_real_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_158_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        x_M_imag_addr_2_reg_346 <= zext_ln24_fu_188_p1;
        x_M_imag_addr_reg_336 <= zext_ln24_1_fu_200_p1;
        x_M_real_addr_2_reg_341 <= zext_ln24_fu_188_p1;
        x_M_real_addr_reg_331 <= zext_ln24_1_fu_200_p1;
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln21_fu_158_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_1 = 10'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_52;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        tw_M_imag_V_ce0 = 1'b1;
    end else begin
        tw_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        tw_M_real_V_ce0 = 1'b1;
    end else begin
        tw_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_M_imag_address0 = x_M_imag_addr_2_reg_346;
    end else if (((icmp_ln21_fu_158_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        x_M_imag_address0 = zext_ln24_fu_188_p1;
    end else begin
        x_M_imag_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_M_imag_address1 = x_M_imag_addr_reg_336;
    end else if (((icmp_ln21_fu_158_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        x_M_imag_address1 = zext_ln24_1_fu_200_p1;
    end else begin
        x_M_imag_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((icmp_ln21_fu_158_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        x_M_imag_ce0 = 1'b1;
    end else begin
        x_M_imag_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((icmp_ln21_fu_158_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        x_M_imag_ce1 = 1'b1;
    end else begin
        x_M_imag_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_M_imag_we0 = 1'b1;
    end else begin
        x_M_imag_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_M_imag_we1 = 1'b1;
    end else begin
        x_M_imag_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_M_real_address0 = x_M_real_addr_2_reg_341;
    end else if (((icmp_ln21_fu_158_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        x_M_real_address0 = zext_ln24_fu_188_p1;
    end else begin
        x_M_real_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_M_real_address1 = x_M_real_addr_reg_331;
    end else if (((icmp_ln21_fu_158_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        x_M_real_address1 = zext_ln24_1_fu_200_p1;
    end else begin
        x_M_real_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((icmp_ln21_fu_158_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        x_M_real_ce0 = 1'b1;
    end else begin
        x_M_real_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((icmp_ln21_fu_158_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        x_M_real_ce1 = 1'b1;
    end else begin
        x_M_real_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_M_real_we0 = 1'b1;
    end else begin
        x_M_real_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_M_real_we1 = 1'b1;
    end else begin
        x_M_real_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln21_fu_158_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln21_fu_164_p2 = (ap_sig_allocacmp_j_1 + 10'd1);

assign add_ln22_fu_170_p2 = (ap_sig_allocacmp_j_1 + trunc_ln20_1);

assign add_ln24_1_fu_194_p2 = (add_ln24_fu_182_p2 + m2);

assign add_ln24_fu_182_p2 = (ap_sig_allocacmp_j_1 + trunc_ln20_2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln21_fu_158_p2 = ((ap_sig_allocacmp_j_1 == m2) ? 1'b1 : 1'b0);

assign r_V_1_fu_232_p0 = sext_ln1319_fu_229_p1;

assign r_V_1_fu_232_p1 = sext_ln1316_fu_225_p1;

assign r_V_3_fu_245_p0 = sext_ln1319_1_fu_242_p1;

assign r_V_3_fu_245_p1 = sext_ln1316_1_fu_238_p1;

assign r_V_4_fu_251_p0 = sext_ln1319_1_fu_242_p1;

assign r_V_4_fu_251_p1 = sext_ln1316_fu_225_p1;

assign r_V_5_fu_257_p0 = sext_ln1316_1_fu_238_p1;

assign r_V_5_fu_257_p1 = sext_ln1319_fu_229_p1;

assign ret_V_1_fu_277_p2 = (r_V_4_reg_393 + r_V_5_reg_398);

assign ret_V_fu_263_p2 = (r_V_1_reg_383 - r_V_3_reg_388);

assign sext_ln1316_1_fu_238_p1 = $signed(tw_im_V_fu_218_p3);

assign sext_ln1316_fu_225_p1 = $signed(tw_re_fu_211_p3);

assign sext_ln1319_1_fu_242_p1 = x_M_imag_load_reg_366;

assign sext_ln1319_fu_229_p1 = x_M_real_load_reg_361;

assign tw_M_imag_V_address0 = zext_ln883_fu_176_p1;

assign tw_M_real_V_address0 = zext_ln883_fu_176_p1;

assign tw_im_V_fu_218_p3 = {{tw_M_imag_V_load_reg_356}, {2'd0}};

assign tw_re_fu_211_p3 = {{tw_M_real_V_load_reg_351}, {2'd0}};

assign x_M_imag_d0 = (u_M_imag_V_reg_377 + tm_im_V_reg_409);

assign x_M_imag_d1 = (u_M_imag_V_reg_377 - tm_im_V_reg_409);

assign x_M_real_d0 = (u_M_real_V_reg_371 + tm_re_V_reg_403);

assign x_M_real_d1 = (u_M_real_V_reg_371 - tm_re_V_reg_403);

assign zext_ln24_1_fu_200_p1 = add_ln24_1_fu_194_p2;

assign zext_ln24_fu_188_p1 = add_ln24_fu_182_p2;

assign zext_ln883_fu_176_p1 = add_ln22_fu_170_p2;

endmodule //fft_1024_top_fft_fast_Pipeline_VITIS_LOOP_21_4
