-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity corr_multiplication is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    input_r_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    input_r_TVALID : IN STD_LOGIC;
    input_r_TREADY : OUT STD_LOGIC;
    input_r_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    input_r_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    input_r_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    output_r_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_r_TVALID : OUT STD_LOGIC;
    output_r_TREADY : IN STD_LOGIC;
    output_r_TKEEP : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_r_TSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_r_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of corr_multiplication is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "corr_multiplication_corr_multiplication,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.256000,HLS_SYN_LAT=2076,HLS_SYN_TPT=none,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=1825,HLS_SYN_LUT=2700,HLS_VERSION=2022_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";

    signal ap_rst_n_inv : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_ap_start : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_ap_done : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_ap_idle : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_ap_ready : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TREADY : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_input_r_TREADY : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TVALID : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TKEEP : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TSTRB : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_100_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_100_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_100_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_100_p_ce : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_104_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_104_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_104_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_104_p_ce : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_108_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_108_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_108_p_ce : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_112_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_112_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_112_p_ce : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_116_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_116_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_116_p_ce : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_120_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_120_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_120_p_ce : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_ap_start : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_ap_done : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_ap_idle : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_ap_ready : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TREADY : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_input_r_TREADY : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TVALID : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TKEEP : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TSTRB : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_100_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_100_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_100_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_100_p_ce : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_104_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_104_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_104_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_104_p_ce : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_108_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_108_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_108_p_ce : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_112_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_112_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_112_p_ce : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_116_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_116_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_116_p_ce : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_120_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_120_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_120_p_ce : STD_LOGIC;
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_fu_100_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_100_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_100_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_100_ce : STD_LOGIC;
    signal grp_fu_104_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_104_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_104_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_104_ce : STD_LOGIC;
    signal grp_fu_108_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_108_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_108_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_108_ce : STD_LOGIC;
    signal grp_fu_112_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_112_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_112_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_112_ce : STD_LOGIC;
    signal grp_fu_116_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_116_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_116_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_116_ce : STD_LOGIC;
    signal grp_fu_120_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_120_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_120_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_120_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal regslice_both_output_r_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal regslice_both_input_r_V_data_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal input_r_TVALID_int_regslice : STD_LOGIC;
    signal input_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_input_r_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_r_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TKEEP_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_input_r_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_r_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_r_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TSTRB_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_input_r_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_r_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_r_V_last_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_input_r_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_r_V_last_V_U_ack_in : STD_LOGIC;
    signal output_r_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal output_r_TVALID_int_regslice : STD_LOGIC;
    signal output_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_output_r_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_output_r_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal output_r_TKEEP_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_output_r_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_output_r_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_output_r_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal output_r_TSTRB_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_output_r_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_output_r_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_output_r_V_last_V_U_apdone_blk : STD_LOGIC;
    signal output_r_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_output_r_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_output_r_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component corr_multiplication_corr_multiplication_Pipeline_VITIS_LOOP_27_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_r_TVALID : IN STD_LOGIC;
        output_r_TREADY : IN STD_LOGIC;
        input_r_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        input_r_TREADY : OUT STD_LOGIC;
        input_r_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
        input_r_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
        input_r_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        output_r_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        output_r_TVALID : OUT STD_LOGIC;
        output_r_TKEEP : OUT STD_LOGIC_VECTOR (7 downto 0);
        output_r_TSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
        output_r_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        grp_fu_100_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_100_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_100_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_100_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_100_p_ce : OUT STD_LOGIC;
        grp_fu_104_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_104_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_104_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_104_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_104_p_ce : OUT STD_LOGIC;
        grp_fu_108_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_108_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_108_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_108_p_ce : OUT STD_LOGIC;
        grp_fu_112_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_112_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_112_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_112_p_ce : OUT STD_LOGIC;
        grp_fu_116_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_116_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_116_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_116_p_ce : OUT STD_LOGIC;
        grp_fu_120_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_120_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_120_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_120_p_ce : OUT STD_LOGIC );
    end component;


    component corr_multiplication_corr_multiplication_Pipeline_VITIS_LOOP_45_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_r_TVALID : IN STD_LOGIC;
        output_r_TREADY : IN STD_LOGIC;
        input_r_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        input_r_TREADY : OUT STD_LOGIC;
        input_r_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
        input_r_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
        input_r_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        output_r_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        output_r_TVALID : OUT STD_LOGIC;
        output_r_TKEEP : OUT STD_LOGIC_VECTOR (7 downto 0);
        output_r_TSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
        output_r_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        grp_fu_100_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_100_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_100_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_100_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_100_p_ce : OUT STD_LOGIC;
        grp_fu_104_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_104_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_104_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_104_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_104_p_ce : OUT STD_LOGIC;
        grp_fu_108_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_108_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_108_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_108_p_ce : OUT STD_LOGIC;
        grp_fu_112_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_112_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_112_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_112_p_ce : OUT STD_LOGIC;
        grp_fu_116_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_116_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_116_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_116_p_ce : OUT STD_LOGIC;
        grp_fu_120_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_120_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_120_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_120_p_ce : OUT STD_LOGIC );
    end component;


    component corr_multiplication_fsub_32ns_32ns_32_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component corr_multiplication_fadd_32ns_32ns_32_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component corr_multiplication_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component corr_multiplication_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52 : component corr_multiplication_corr_multiplication_Pipeline_VITIS_LOOP_27_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_ap_start,
        ap_done => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_ap_done,
        ap_idle => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_ap_idle,
        ap_ready => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_ap_ready,
        input_r_TVALID => input_r_TVALID_int_regslice,
        output_r_TREADY => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TREADY,
        input_r_TDATA => input_r_TDATA_int_regslice,
        input_r_TREADY => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_input_r_TREADY,
        input_r_TKEEP => input_r_TKEEP_int_regslice,
        input_r_TSTRB => input_r_TSTRB_int_regslice,
        input_r_TLAST => input_r_TLAST_int_regslice,
        output_r_TDATA => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TDATA,
        output_r_TVALID => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TVALID,
        output_r_TKEEP => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TKEEP,
        output_r_TSTRB => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TSTRB,
        output_r_TLAST => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TLAST,
        grp_fu_100_p_din0 => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_100_p_din0,
        grp_fu_100_p_din1 => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_100_p_din1,
        grp_fu_100_p_opcode => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_100_p_opcode,
        grp_fu_100_p_dout0 => grp_fu_100_p2,
        grp_fu_100_p_ce => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_100_p_ce,
        grp_fu_104_p_din0 => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_104_p_din0,
        grp_fu_104_p_din1 => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_104_p_din1,
        grp_fu_104_p_opcode => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_104_p_opcode,
        grp_fu_104_p_dout0 => grp_fu_104_p2,
        grp_fu_104_p_ce => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_104_p_ce,
        grp_fu_108_p_din0 => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_108_p_din0,
        grp_fu_108_p_din1 => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_108_p_din1,
        grp_fu_108_p_dout0 => grp_fu_108_p2,
        grp_fu_108_p_ce => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_108_p_ce,
        grp_fu_112_p_din0 => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_112_p_din0,
        grp_fu_112_p_din1 => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_112_p_din1,
        grp_fu_112_p_dout0 => grp_fu_112_p2,
        grp_fu_112_p_ce => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_112_p_ce,
        grp_fu_116_p_din0 => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_116_p_din0,
        grp_fu_116_p_din1 => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_116_p_din1,
        grp_fu_116_p_dout0 => grp_fu_116_p2,
        grp_fu_116_p_ce => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_116_p_ce,
        grp_fu_120_p_din0 => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_120_p_din0,
        grp_fu_120_p_din1 => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_120_p_din1,
        grp_fu_120_p_dout0 => grp_fu_120_p2,
        grp_fu_120_p_ce => grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_120_p_ce);

    grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76 : component corr_multiplication_corr_multiplication_Pipeline_VITIS_LOOP_45_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_ap_start,
        ap_done => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_ap_done,
        ap_idle => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_ap_idle,
        ap_ready => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_ap_ready,
        input_r_TVALID => input_r_TVALID_int_regslice,
        output_r_TREADY => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TREADY,
        input_r_TDATA => input_r_TDATA_int_regslice,
        input_r_TREADY => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_input_r_TREADY,
        input_r_TKEEP => input_r_TKEEP_int_regslice,
        input_r_TSTRB => input_r_TSTRB_int_regslice,
        input_r_TLAST => input_r_TLAST_int_regslice,
        output_r_TDATA => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TDATA,
        output_r_TVALID => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TVALID,
        output_r_TKEEP => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TKEEP,
        output_r_TSTRB => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TSTRB,
        output_r_TLAST => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TLAST,
        grp_fu_100_p_din0 => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_100_p_din0,
        grp_fu_100_p_din1 => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_100_p_din1,
        grp_fu_100_p_opcode => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_100_p_opcode,
        grp_fu_100_p_dout0 => grp_fu_100_p2,
        grp_fu_100_p_ce => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_100_p_ce,
        grp_fu_104_p_din0 => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_104_p_din0,
        grp_fu_104_p_din1 => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_104_p_din1,
        grp_fu_104_p_opcode => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_104_p_opcode,
        grp_fu_104_p_dout0 => grp_fu_104_p2,
        grp_fu_104_p_ce => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_104_p_ce,
        grp_fu_108_p_din0 => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_108_p_din0,
        grp_fu_108_p_din1 => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_108_p_din1,
        grp_fu_108_p_dout0 => grp_fu_108_p2,
        grp_fu_108_p_ce => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_108_p_ce,
        grp_fu_112_p_din0 => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_112_p_din0,
        grp_fu_112_p_din1 => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_112_p_din1,
        grp_fu_112_p_dout0 => grp_fu_112_p2,
        grp_fu_112_p_ce => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_112_p_ce,
        grp_fu_116_p_din0 => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_116_p_din0,
        grp_fu_116_p_din1 => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_116_p_din1,
        grp_fu_116_p_dout0 => grp_fu_116_p2,
        grp_fu_116_p_ce => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_116_p_ce,
        grp_fu_120_p_din0 => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_120_p_din0,
        grp_fu_120_p_din1 => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_120_p_din1,
        grp_fu_120_p_dout0 => grp_fu_120_p2,
        grp_fu_120_p_ce => grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_120_p_ce);

    fsub_32ns_32ns_32_5_full_dsp_1_U33 : component corr_multiplication_fsub_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_100_p0,
        din1 => grp_fu_100_p1,
        ce => grp_fu_100_ce,
        dout => grp_fu_100_p2);

    fadd_32ns_32ns_32_5_full_dsp_1_U34 : component corr_multiplication_fadd_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_104_p0,
        din1 => grp_fu_104_p1,
        ce => grp_fu_104_ce,
        dout => grp_fu_104_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U35 : component corr_multiplication_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_108_p0,
        din1 => grp_fu_108_p1,
        ce => grp_fu_108_ce,
        dout => grp_fu_108_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U36 : component corr_multiplication_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_112_p0,
        din1 => grp_fu_112_p1,
        ce => grp_fu_112_ce,
        dout => grp_fu_112_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U37 : component corr_multiplication_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_116_p0,
        din1 => grp_fu_116_p1,
        ce => grp_fu_116_ce,
        dout => grp_fu_116_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U38 : component corr_multiplication_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_120_p0,
        din1 => grp_fu_120_p1,
        ce => grp_fu_120_ce,
        dout => grp_fu_120_p2);

    regslice_both_input_r_V_data_V_U : component corr_multiplication_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_r_TDATA,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_data_V_U_ack_in,
        data_out => input_r_TDATA_int_regslice,
        vld_out => input_r_TVALID_int_regslice,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_data_V_U_apdone_blk);

    regslice_both_input_r_V_keep_V_U : component corr_multiplication_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_r_TKEEP,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_keep_V_U_ack_in,
        data_out => input_r_TKEEP_int_regslice,
        vld_out => regslice_both_input_r_V_keep_V_U_vld_out,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_keep_V_U_apdone_blk);

    regslice_both_input_r_V_strb_V_U : component corr_multiplication_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_r_TSTRB,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_strb_V_U_ack_in,
        data_out => input_r_TSTRB_int_regslice,
        vld_out => regslice_both_input_r_V_strb_V_U_vld_out,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_strb_V_U_apdone_blk);

    regslice_both_input_r_V_last_V_U : component corr_multiplication_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_r_TLAST,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_last_V_U_ack_in,
        data_out => input_r_TLAST_int_regslice,
        vld_out => regslice_both_input_r_V_last_V_U_vld_out,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_last_V_U_apdone_blk);

    regslice_both_output_r_V_data_V_U : component corr_multiplication_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => output_r_TDATA_int_regslice,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => output_r_TREADY_int_regslice,
        data_out => output_r_TDATA,
        vld_out => regslice_both_output_r_V_data_V_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_V_data_V_U_apdone_blk);

    regslice_both_output_r_V_keep_V_U : component corr_multiplication_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => output_r_TKEEP_int_regslice,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => regslice_both_output_r_V_keep_V_U_ack_in_dummy,
        data_out => output_r_TKEEP,
        vld_out => regslice_both_output_r_V_keep_V_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_V_keep_V_U_apdone_blk);

    regslice_both_output_r_V_strb_V_U : component corr_multiplication_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => output_r_TSTRB_int_regslice,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => regslice_both_output_r_V_strb_V_U_ack_in_dummy,
        data_out => output_r_TSTRB,
        vld_out => regslice_both_output_r_V_strb_V_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_V_strb_V_U_apdone_blk);

    regslice_both_output_r_V_last_V_U : component corr_multiplication_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => output_r_TLAST_int_regslice,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => regslice_both_output_r_V_last_V_U_ack_in_dummy,
        data_out => output_r_TLAST,
        vld_out => regslice_both_output_r_V_last_V_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_ap_ready = ap_const_logic_1)) then 
                    grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_ap_ready = ap_const_logic_1)) then 
                    grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_ap_done, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_ap_done, ap_CS_fsm, ap_CS_fsm_state3, ap_CS_fsm_state6, regslice_both_output_r_V_data_V_U_apdone_blk, ap_CS_fsm_state7)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                if (((regslice_both_output_r_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_ap_done)
    begin
        if ((grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_ap_done)
    begin
        if ((grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state7_blk_assign_proc : process(regslice_both_output_r_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_output_r_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_ap_start <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_ap_start_reg;
    grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TREADY <= (output_r_TREADY_int_regslice and ap_CS_fsm_state3);
    grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_ap_start <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_ap_start_reg;
    grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TREADY <= (output_r_TREADY_int_regslice and ap_CS_fsm_state6);

    grp_fu_100_ce_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_100_p_ce, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_100_p_ce, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_100_ce <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_100_p_ce;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_100_ce <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_100_p_ce;
        else 
            grp_fu_100_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_100_p0_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_100_p_din0, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_100_p_din0, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_100_p0 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_100_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_100_p0 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_100_p_din0;
        else 
            grp_fu_100_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_100_p1_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_100_p_din1, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_100_p_din1, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_100_p1 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_100_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_100_p1 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_100_p_din1;
        else 
            grp_fu_100_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_104_ce_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_104_p_ce, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_104_p_ce, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_104_ce <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_104_p_ce;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_104_ce <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_104_p_ce;
        else 
            grp_fu_104_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_104_p0_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_104_p_din0, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_104_p_din0, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_104_p0 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_104_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_104_p0 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_104_p_din0;
        else 
            grp_fu_104_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_104_p1_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_104_p_din1, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_104_p_din1, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_104_p1 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_104_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_104_p1 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_104_p_din1;
        else 
            grp_fu_104_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_108_ce_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_108_p_ce, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_108_p_ce, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_108_ce <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_108_p_ce;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_108_ce <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_108_p_ce;
        else 
            grp_fu_108_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_108_p0_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_108_p_din0, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_108_p_din0, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_108_p0 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_108_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_108_p0 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_108_p_din0;
        else 
            grp_fu_108_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_108_p1_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_108_p_din1, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_108_p_din1, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_108_p1 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_108_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_108_p1 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_108_p_din1;
        else 
            grp_fu_108_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_112_ce_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_112_p_ce, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_112_p_ce, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_112_ce <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_112_p_ce;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_112_ce <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_112_p_ce;
        else 
            grp_fu_112_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_112_p0_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_112_p_din0, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_112_p_din0, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_112_p0 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_112_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_112_p0 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_112_p_din0;
        else 
            grp_fu_112_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_112_p1_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_112_p_din1, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_112_p_din1, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_112_p1 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_112_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_112_p1 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_112_p_din1;
        else 
            grp_fu_112_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_116_ce_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_116_p_ce, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_116_p_ce, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_116_ce <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_116_p_ce;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_116_ce <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_116_p_ce;
        else 
            grp_fu_116_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_116_p0_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_116_p_din0, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_116_p_din0, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_116_p0 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_116_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_116_p0 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_116_p_din0;
        else 
            grp_fu_116_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_116_p1_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_116_p_din1, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_116_p_din1, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_116_p1 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_116_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_116_p1 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_116_p_din1;
        else 
            grp_fu_116_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_120_ce_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_120_p_ce, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_120_p_ce, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_120_ce <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_120_p_ce;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_120_ce <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_120_p_ce;
        else 
            grp_fu_120_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_120_p0_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_120_p_din0, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_120_p_din0, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_120_p0 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_120_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_120_p0 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_120_p_din0;
        else 
            grp_fu_120_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_120_p1_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_120_p_din1, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_120_p_din1, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_120_p1 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_grp_fu_120_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_120_p1 <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_grp_fu_120_p_din1;
        else 
            grp_fu_120_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    input_r_TREADY <= regslice_both_input_r_V_data_V_U_ack_in;

    input_r_TREADY_int_regslice_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_input_r_TREADY, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_input_r_TREADY, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            input_r_TREADY_int_regslice <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_input_r_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_r_TREADY_int_regslice <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_input_r_TREADY;
        else 
            input_r_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    output_r_TDATA_int_regslice_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TDATA, grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TVALID, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TDATA, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TVALID, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if (((grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            output_r_TDATA_int_regslice <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TDATA;
        elsif (((grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            output_r_TDATA_int_regslice <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TDATA;
        else 
            output_r_TDATA_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    output_r_TKEEP_int_regslice_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TVALID, grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TKEEP, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TVALID, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TKEEP, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if (((grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            output_r_TKEEP_int_regslice <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TKEEP;
        elsif (((grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            output_r_TKEEP_int_regslice <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TKEEP;
        else 
            output_r_TKEEP_int_regslice <= "XXXXXXXX";
        end if; 
    end process;


    output_r_TLAST_int_regslice_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TVALID, grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TLAST, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TVALID, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TLAST, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if (((grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            output_r_TLAST_int_regslice <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TLAST;
        elsif (((grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            output_r_TLAST_int_regslice <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TLAST;
        else 
            output_r_TLAST_int_regslice <= "X";
        end if; 
    end process;


    output_r_TSTRB_int_regslice_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TVALID, grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TSTRB, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TVALID, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TSTRB, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if (((grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            output_r_TSTRB_int_regslice <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TSTRB;
        elsif (((grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            output_r_TSTRB_int_regslice <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TSTRB;
        else 
            output_r_TSTRB_int_regslice <= "XXXXXXXX";
        end if; 
    end process;

    output_r_TVALID <= regslice_both_output_r_V_data_V_U_vld_out;

    output_r_TVALID_int_regslice_assign_proc : process(grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TVALID, grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TVALID, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            output_r_TVALID_int_regslice <= grp_corr_multiplication_Pipeline_VITIS_LOOP_45_2_fu_76_output_r_TVALID;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            output_r_TVALID_int_regslice <= grp_corr_multiplication_Pipeline_VITIS_LOOP_27_1_fu_52_output_r_TVALID;
        else 
            output_r_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

end behav;
