// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ifft_1024_top_ifft_1024_top,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.221929,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=18,HLS_SYN_DSP=0,HLS_SYN_FF=5243,HLS_SYN_LUT=8727,HLS_VERSION=2022_1}" *)

module ifft_1024_top (
        ap_clk,
        ap_rst_n,
        input_r_TDATA,
        input_r_TVALID,
        input_r_TREADY,
        input_r_TKEEP,
        input_r_TSTRB,
        input_r_TLAST,
        output_r_TDATA,
        output_r_TVALID,
        output_r_TREADY,
        output_r_TKEEP,
        output_r_TSTRB,
        output_r_TLAST
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst_n;
input  [63:0] input_r_TDATA;
input   input_r_TVALID;
output   input_r_TREADY;
input  [7:0] input_r_TKEEP;
input  [7:0] input_r_TSTRB;
input  [0:0] input_r_TLAST;
output  [63:0] output_r_TDATA;
output   output_r_TVALID;
input   output_r_TREADY;
output  [7:0] output_r_TKEEP;
output  [7:0] output_r_TSTRB;
output  [0:0] output_r_TLAST;

 reg    ap_rst_n_inv;
reg   [9:0] ga_M_real_V_address0;
reg    ga_M_real_V_ce0;
reg    ga_M_real_V_we0;
reg   [23:0] ga_M_real_V_d0;
wire   [23:0] ga_M_real_V_q0;
reg    ga_M_real_V_ce1;
reg    ga_M_real_V_we1;
wire   [23:0] ga_M_real_V_q1;
reg   [9:0] ga_M_imag_V_address0;
reg    ga_M_imag_V_ce0;
reg    ga_M_imag_V_we0;
reg   [23:0] ga_M_imag_V_d0;
wire   [23:0] ga_M_imag_V_q0;
reg    ga_M_imag_V_ce1;
reg    ga_M_imag_V_we1;
wire   [23:0] ga_M_imag_V_q1;
reg   [9:0] gb_M_real_V_address0;
reg    gb_M_real_V_ce0;
reg    gb_M_real_V_we0;
reg   [23:0] gb_M_real_V_d0;
wire   [23:0] gb_M_real_V_q0;
reg    gb_M_real_V_ce1;
reg    gb_M_real_V_we1;
wire   [23:0] gb_M_real_V_q1;
reg   [9:0] gb_M_imag_V_address0;
reg    gb_M_imag_V_ce0;
reg    gb_M_imag_V_we0;
reg   [23:0] gb_M_imag_V_d0;
wire   [23:0] gb_M_imag_V_q0;
reg    gb_M_imag_V_ce1;
reg    gb_M_imag_V_we1;
wire   [23:0] gb_M_imag_V_q1;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ap_start;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ap_done;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ap_idle;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ap_ready;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_input_r_TREADY;
wire   [9:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_real_V_address0;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_real_V_ce0;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_real_V_we0;
wire   [23:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_real_V_d0;
wire   [9:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_imag_V_address0;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_imag_V_ce0;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_imag_V_we0;
wire   [23:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_imag_V_d0;
wire   [31:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_140_p_din0;
wire   [31:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_140_p_din1;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_140_p_ce;
wire   [31:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_144_p_din0;
wire   [31:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_144_p_din1;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_144_p_ce;
wire   [31:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_148_p_din0;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_148_p_ce;
wire   [31:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_151_p_din0;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_151_p_ce;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_ap_start;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_ap_done;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_ap_idle;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_ap_ready;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_input_r_TREADY;
wire   [9:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_real_V_address0;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_real_V_ce0;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_real_V_we0;
wire   [23:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_real_V_d0;
wire   [9:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_imag_V_address0;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_imag_V_ce0;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_imag_V_we0;
wire   [23:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_imag_V_d0;
wire   [31:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_140_p_din0;
wire   [31:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_140_p_din1;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_140_p_ce;
wire   [31:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_144_p_din0;
wire   [31:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_144_p_din1;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_144_p_ce;
wire   [31:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_148_p_din0;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_148_p_ce;
wire   [31:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_151_p_din0;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_151_p_ce;
wire    grp_ifft_fast_fu_100_ap_start;
wire    grp_ifft_fast_fu_100_ap_done;
wire    grp_ifft_fast_fu_100_ap_idle;
wire    grp_ifft_fast_fu_100_ap_ready;
wire   [9:0] grp_ifft_fast_fu_100_x_M_real_address0;
wire    grp_ifft_fast_fu_100_x_M_real_ce0;
wire    grp_ifft_fast_fu_100_x_M_real_we0;
wire   [23:0] grp_ifft_fast_fu_100_x_M_real_d0;
wire   [9:0] grp_ifft_fast_fu_100_x_M_real_address1;
wire    grp_ifft_fast_fu_100_x_M_real_ce1;
wire    grp_ifft_fast_fu_100_x_M_real_we1;
wire   [23:0] grp_ifft_fast_fu_100_x_M_real_d1;
wire   [9:0] grp_ifft_fast_fu_100_x_M_imag_address0;
wire    grp_ifft_fast_fu_100_x_M_imag_ce0;
wire    grp_ifft_fast_fu_100_x_M_imag_we0;
wire   [23:0] grp_ifft_fast_fu_100_x_M_imag_d0;
wire   [9:0] grp_ifft_fast_fu_100_x_M_imag_address1;
wire    grp_ifft_fast_fu_100_x_M_imag_ce1;
wire    grp_ifft_fast_fu_100_x_M_imag_we1;
wire   [23:0] grp_ifft_fast_fu_100_x_M_imag_d1;
wire    grp_ifft_fast_fu_112_ap_start;
wire    grp_ifft_fast_fu_112_ap_done;
wire    grp_ifft_fast_fu_112_ap_idle;
wire    grp_ifft_fast_fu_112_ap_ready;
wire   [9:0] grp_ifft_fast_fu_112_x_M_real_address0;
wire    grp_ifft_fast_fu_112_x_M_real_ce0;
wire    grp_ifft_fast_fu_112_x_M_real_we0;
wire   [23:0] grp_ifft_fast_fu_112_x_M_real_d0;
wire   [9:0] grp_ifft_fast_fu_112_x_M_real_address1;
wire    grp_ifft_fast_fu_112_x_M_real_ce1;
wire    grp_ifft_fast_fu_112_x_M_real_we1;
wire   [23:0] grp_ifft_fast_fu_112_x_M_real_d1;
wire   [9:0] grp_ifft_fast_fu_112_x_M_imag_address0;
wire    grp_ifft_fast_fu_112_x_M_imag_ce0;
wire    grp_ifft_fast_fu_112_x_M_imag_we0;
wire   [23:0] grp_ifft_fast_fu_112_x_M_imag_d0;
wire   [9:0] grp_ifft_fast_fu_112_x_M_imag_address1;
wire    grp_ifft_fast_fu_112_x_M_imag_ce1;
wire    grp_ifft_fast_fu_112_x_M_imag_we1;
wire   [23:0] grp_ifft_fast_fu_112_x_M_imag_d1;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ap_start;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ap_done;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ap_idle;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ap_ready;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TREADY;
wire   [9:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ga_M_real_V_address0;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ga_M_real_V_ce0;
wire   [9:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_gb_M_real_V_address0;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_gb_M_real_V_ce0;
wire   [9:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ga_M_imag_V_address0;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ga_M_imag_V_ce0;
wire   [9:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_gb_M_imag_V_address0;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_gb_M_imag_V_ce0;
wire   [63:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TDATA;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TVALID;
wire   [7:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TKEEP;
wire   [7:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TSTRB;
wire   [0:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TLAST;
wire   [31:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_grp_fu_140_p_din0;
wire   [31:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_grp_fu_140_p_din1;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_grp_fu_140_p_ce;
wire   [31:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_grp_fu_144_p_din0;
wire   [31:0] grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_grp_fu_144_p_din1;
wire    grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_grp_fu_144_p_ce;
reg    grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ap_start_reg;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_ifft_fast_fu_100_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_ifft_fast_fu_112_ap_start_reg;
reg    grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire   [31:0] grp_fu_140_p2;
reg   [31:0] grp_fu_140_p0;
reg   [31:0] grp_fu_140_p1;
reg    grp_fu_140_ce;
wire   [31:0] grp_fu_144_p2;
reg   [31:0] grp_fu_144_p0;
reg   [31:0] grp_fu_144_p1;
reg    grp_fu_144_ce;
wire   [63:0] grp_fu_148_p1;
reg   [31:0] grp_fu_148_p0;
reg    grp_fu_148_ce;
wire   [63:0] grp_fu_151_p1;
reg   [31:0] grp_fu_151_p0;
reg    grp_fu_151_ce;
reg   [10:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_block_state8_on_subcall_done;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    regslice_both_output_r_V_data_V_U_apdone_blk;
wire    ap_CS_fsm_state11;
wire    regslice_both_input_r_V_data_V_U_apdone_blk;
wire   [63:0] input_r_TDATA_int_regslice;
wire    input_r_TVALID_int_regslice;
reg    input_r_TREADY_int_regslice;
wire    regslice_both_input_r_V_data_V_U_ack_in;
wire    regslice_both_input_r_V_keep_V_U_apdone_blk;
wire   [7:0] input_r_TKEEP_int_regslice;
wire    regslice_both_input_r_V_keep_V_U_vld_out;
wire    regslice_both_input_r_V_keep_V_U_ack_in;
wire    regslice_both_input_r_V_strb_V_U_apdone_blk;
wire   [7:0] input_r_TSTRB_int_regslice;
wire    regslice_both_input_r_V_strb_V_U_vld_out;
wire    regslice_both_input_r_V_strb_V_U_ack_in;
wire    regslice_both_input_r_V_last_V_U_apdone_blk;
wire   [0:0] input_r_TLAST_int_regslice;
wire    regslice_both_input_r_V_last_V_U_vld_out;
wire    regslice_both_input_r_V_last_V_U_ack_in;
wire    output_r_TVALID_int_regslice;
wire    output_r_TREADY_int_regslice;
wire    regslice_both_output_r_V_data_V_U_vld_out;
wire    regslice_both_output_r_V_keep_V_U_apdone_blk;
wire    regslice_both_output_r_V_keep_V_U_ack_in_dummy;
wire    regslice_both_output_r_V_keep_V_U_vld_out;
wire    regslice_both_output_r_V_strb_V_U_apdone_blk;
wire    regslice_both_output_r_V_strb_V_U_ack_in_dummy;
wire    regslice_both_output_r_V_strb_V_U_vld_out;
wire    regslice_both_output_r_V_last_V_U_apdone_blk;
wire    regslice_both_output_r_V_last_V_U_ack_in_dummy;
wire    regslice_both_output_r_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ap_start_reg = 1'b0;
#0 ap_CS_fsm = 11'd1;
#0 grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_ap_start_reg = 1'b0;
#0 grp_ifft_fast_fu_100_ap_start_reg = 1'b0;
#0 grp_ifft_fast_fu_112_ap_start_reg = 1'b0;
#0 grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ap_start_reg = 1'b0;
end

ifft_1024_top_ga_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
ga_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(ga_M_real_V_address0),
    .ce0(ga_M_real_V_ce0),
    .we0(ga_M_real_V_we0),
    .d0(ga_M_real_V_d0),
    .q0(ga_M_real_V_q0),
    .address1(grp_ifft_fast_fu_100_x_M_real_address1),
    .ce1(ga_M_real_V_ce1),
    .we1(ga_M_real_V_we1),
    .d1(grp_ifft_fast_fu_100_x_M_real_d1),
    .q1(ga_M_real_V_q1)
);

ifft_1024_top_ga_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
ga_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(ga_M_imag_V_address0),
    .ce0(ga_M_imag_V_ce0),
    .we0(ga_M_imag_V_we0),
    .d0(ga_M_imag_V_d0),
    .q0(ga_M_imag_V_q0),
    .address1(grp_ifft_fast_fu_100_x_M_imag_address1),
    .ce1(ga_M_imag_V_ce1),
    .we1(ga_M_imag_V_we1),
    .d1(grp_ifft_fast_fu_100_x_M_imag_d1),
    .q1(ga_M_imag_V_q1)
);

ifft_1024_top_ga_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
gb_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(gb_M_real_V_address0),
    .ce0(gb_M_real_V_ce0),
    .we0(gb_M_real_V_we0),
    .d0(gb_M_real_V_d0),
    .q0(gb_M_real_V_q0),
    .address1(grp_ifft_fast_fu_112_x_M_real_address1),
    .ce1(gb_M_real_V_ce1),
    .we1(gb_M_real_V_we1),
    .d1(grp_ifft_fast_fu_112_x_M_real_d1),
    .q1(gb_M_real_V_q1)
);

ifft_1024_top_ga_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
gb_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(gb_M_imag_V_address0),
    .ce0(gb_M_imag_V_ce0),
    .we0(gb_M_imag_V_we0),
    .d0(gb_M_imag_V_d0),
    .q0(gb_M_imag_V_q0),
    .address1(grp_ifft_fast_fu_112_x_M_imag_address1),
    .ce1(gb_M_imag_V_ce1),
    .we1(gb_M_imag_V_we1),
    .d1(grp_ifft_fast_fu_112_x_M_imag_d1),
    .q1(gb_M_imag_V_q1)
);

ifft_1024_top_ifft_1024_top_Pipeline_VITIS_LOOP_57_1 grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ap_start),
    .ap_done(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ap_done),
    .ap_idle(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ap_idle),
    .ap_ready(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ap_ready),
    .input_r_TVALID(input_r_TVALID_int_regslice),
    .input_r_TDATA(input_r_TDATA_int_regslice),
    .input_r_TREADY(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_input_r_TREADY),
    .input_r_TKEEP(input_r_TKEEP_int_regslice),
    .input_r_TSTRB(input_r_TSTRB_int_regslice),
    .input_r_TLAST(input_r_TLAST_int_regslice),
    .ga_M_real_V_address0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_real_V_address0),
    .ga_M_real_V_ce0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_real_V_ce0),
    .ga_M_real_V_we0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_real_V_we0),
    .ga_M_real_V_d0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_real_V_d0),
    .ga_M_imag_V_address0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_imag_V_address0),
    .ga_M_imag_V_ce0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_imag_V_ce0),
    .ga_M_imag_V_we0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_imag_V_we0),
    .ga_M_imag_V_d0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_imag_V_d0),
    .grp_fu_140_p_din0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_140_p_din0),
    .grp_fu_140_p_din1(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_140_p_din1),
    .grp_fu_140_p_dout0(grp_fu_140_p2),
    .grp_fu_140_p_ce(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_140_p_ce),
    .grp_fu_144_p_din0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_144_p_din0),
    .grp_fu_144_p_din1(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_144_p_din1),
    .grp_fu_144_p_dout0(grp_fu_144_p2),
    .grp_fu_144_p_ce(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_144_p_ce),
    .grp_fu_148_p_din0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_148_p_din0),
    .grp_fu_148_p_dout0(grp_fu_148_p1),
    .grp_fu_148_p_ce(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_148_p_ce),
    .grp_fu_151_p_din0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_151_p_din0),
    .grp_fu_151_p_dout0(grp_fu_151_p1),
    .grp_fu_151_p_ce(grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_151_p_ce)
);

ifft_1024_top_ifft_1024_top_Pipeline_VITIS_LOOP_63_2 grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_ap_start),
    .ap_done(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_ap_done),
    .ap_idle(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_ap_idle),
    .ap_ready(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_ap_ready),
    .input_r_TVALID(input_r_TVALID_int_regslice),
    .input_r_TDATA(input_r_TDATA_int_regslice),
    .input_r_TREADY(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_input_r_TREADY),
    .input_r_TKEEP(input_r_TKEEP_int_regslice),
    .input_r_TSTRB(input_r_TSTRB_int_regslice),
    .input_r_TLAST(input_r_TLAST_int_regslice),
    .gb_M_real_V_address0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_real_V_address0),
    .gb_M_real_V_ce0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_real_V_ce0),
    .gb_M_real_V_we0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_real_V_we0),
    .gb_M_real_V_d0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_real_V_d0),
    .gb_M_imag_V_address0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_imag_V_address0),
    .gb_M_imag_V_ce0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_imag_V_ce0),
    .gb_M_imag_V_we0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_imag_V_we0),
    .gb_M_imag_V_d0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_imag_V_d0),
    .grp_fu_140_p_din0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_140_p_din0),
    .grp_fu_140_p_din1(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_140_p_din1),
    .grp_fu_140_p_dout0(grp_fu_140_p2),
    .grp_fu_140_p_ce(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_140_p_ce),
    .grp_fu_144_p_din0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_144_p_din0),
    .grp_fu_144_p_din1(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_144_p_din1),
    .grp_fu_144_p_dout0(grp_fu_144_p2),
    .grp_fu_144_p_ce(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_144_p_ce),
    .grp_fu_148_p_din0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_148_p_din0),
    .grp_fu_148_p_dout0(grp_fu_148_p1),
    .grp_fu_148_p_ce(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_148_p_ce),
    .grp_fu_151_p_din0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_151_p_din0),
    .grp_fu_151_p_dout0(grp_fu_151_p1),
    .grp_fu_151_p_ce(grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_151_p_ce)
);

ifft_1024_top_ifft_fast grp_ifft_fast_fu_100(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_ifft_fast_fu_100_ap_start),
    .ap_done(grp_ifft_fast_fu_100_ap_done),
    .ap_idle(grp_ifft_fast_fu_100_ap_idle),
    .ap_ready(grp_ifft_fast_fu_100_ap_ready),
    .x_M_real_address0(grp_ifft_fast_fu_100_x_M_real_address0),
    .x_M_real_ce0(grp_ifft_fast_fu_100_x_M_real_ce0),
    .x_M_real_we0(grp_ifft_fast_fu_100_x_M_real_we0),
    .x_M_real_d0(grp_ifft_fast_fu_100_x_M_real_d0),
    .x_M_real_q0(ga_M_real_V_q0),
    .x_M_real_address1(grp_ifft_fast_fu_100_x_M_real_address1),
    .x_M_real_ce1(grp_ifft_fast_fu_100_x_M_real_ce1),
    .x_M_real_we1(grp_ifft_fast_fu_100_x_M_real_we1),
    .x_M_real_d1(grp_ifft_fast_fu_100_x_M_real_d1),
    .x_M_real_q1(ga_M_real_V_q1),
    .x_M_imag_address0(grp_ifft_fast_fu_100_x_M_imag_address0),
    .x_M_imag_ce0(grp_ifft_fast_fu_100_x_M_imag_ce0),
    .x_M_imag_we0(grp_ifft_fast_fu_100_x_M_imag_we0),
    .x_M_imag_d0(grp_ifft_fast_fu_100_x_M_imag_d0),
    .x_M_imag_q0(ga_M_imag_V_q0),
    .x_M_imag_address1(grp_ifft_fast_fu_100_x_M_imag_address1),
    .x_M_imag_ce1(grp_ifft_fast_fu_100_x_M_imag_ce1),
    .x_M_imag_we1(grp_ifft_fast_fu_100_x_M_imag_we1),
    .x_M_imag_d1(grp_ifft_fast_fu_100_x_M_imag_d1),
    .x_M_imag_q1(ga_M_imag_V_q1)
);

ifft_1024_top_ifft_fast grp_ifft_fast_fu_112(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_ifft_fast_fu_112_ap_start),
    .ap_done(grp_ifft_fast_fu_112_ap_done),
    .ap_idle(grp_ifft_fast_fu_112_ap_idle),
    .ap_ready(grp_ifft_fast_fu_112_ap_ready),
    .x_M_real_address0(grp_ifft_fast_fu_112_x_M_real_address0),
    .x_M_real_ce0(grp_ifft_fast_fu_112_x_M_real_ce0),
    .x_M_real_we0(grp_ifft_fast_fu_112_x_M_real_we0),
    .x_M_real_d0(grp_ifft_fast_fu_112_x_M_real_d0),
    .x_M_real_q0(gb_M_real_V_q0),
    .x_M_real_address1(grp_ifft_fast_fu_112_x_M_real_address1),
    .x_M_real_ce1(grp_ifft_fast_fu_112_x_M_real_ce1),
    .x_M_real_we1(grp_ifft_fast_fu_112_x_M_real_we1),
    .x_M_real_d1(grp_ifft_fast_fu_112_x_M_real_d1),
    .x_M_real_q1(gb_M_real_V_q1),
    .x_M_imag_address0(grp_ifft_fast_fu_112_x_M_imag_address0),
    .x_M_imag_ce0(grp_ifft_fast_fu_112_x_M_imag_ce0),
    .x_M_imag_we0(grp_ifft_fast_fu_112_x_M_imag_we0),
    .x_M_imag_d0(grp_ifft_fast_fu_112_x_M_imag_d0),
    .x_M_imag_q0(gb_M_imag_V_q0),
    .x_M_imag_address1(grp_ifft_fast_fu_112_x_M_imag_address1),
    .x_M_imag_ce1(grp_ifft_fast_fu_112_x_M_imag_ce1),
    .x_M_imag_we1(grp_ifft_fast_fu_112_x_M_imag_we1),
    .x_M_imag_d1(grp_ifft_fast_fu_112_x_M_imag_d1),
    .x_M_imag_q1(gb_M_imag_V_q1)
);

ifft_1024_top_ifft_1024_top_Pipeline_VITIS_LOOP_72_3 grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ap_start),
    .ap_done(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ap_done),
    .ap_idle(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ap_idle),
    .ap_ready(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ap_ready),
    .output_r_TREADY(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TREADY),
    .ga_M_real_V_address0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ga_M_real_V_address0),
    .ga_M_real_V_ce0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ga_M_real_V_ce0),
    .ga_M_real_V_q0(ga_M_real_V_q0),
    .gb_M_real_V_address0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_gb_M_real_V_address0),
    .gb_M_real_V_ce0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_gb_M_real_V_ce0),
    .gb_M_real_V_q0(gb_M_real_V_q0),
    .ga_M_imag_V_address0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ga_M_imag_V_address0),
    .ga_M_imag_V_ce0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ga_M_imag_V_ce0),
    .ga_M_imag_V_q0(ga_M_imag_V_q0),
    .gb_M_imag_V_address0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_gb_M_imag_V_address0),
    .gb_M_imag_V_ce0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_gb_M_imag_V_ce0),
    .gb_M_imag_V_q0(gb_M_imag_V_q0),
    .output_r_TDATA(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TDATA),
    .output_r_TVALID(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TVALID),
    .output_r_TKEEP(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TKEEP),
    .output_r_TSTRB(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TSTRB),
    .output_r_TLAST(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TLAST),
    .grp_fu_140_p_din0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_grp_fu_140_p_din0),
    .grp_fu_140_p_din1(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_grp_fu_140_p_din1),
    .grp_fu_140_p_dout0(grp_fu_140_p2),
    .grp_fu_140_p_ce(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_grp_fu_140_p_ce),
    .grp_fu_144_p_din0(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_grp_fu_144_p_din0),
    .grp_fu_144_p_din1(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_grp_fu_144_p_din1),
    .grp_fu_144_p_dout0(grp_fu_144_p2),
    .grp_fu_144_p_ce(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_grp_fu_144_p_ce)
);

ifft_1024_top_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U49(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_140_p0),
    .din1(grp_fu_140_p1),
    .ce(grp_fu_140_ce),
    .dout(grp_fu_140_p2)
);

ifft_1024_top_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U50(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_144_p0),
    .din1(grp_fu_144_p1),
    .ce(grp_fu_144_ce),
    .dout(grp_fu_144_p2)
);

ifft_1024_top_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U51(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_148_p0),
    .ce(grp_fu_148_ce),
    .dout(grp_fu_148_p1)
);

ifft_1024_top_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U52(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_151_p0),
    .ce(grp_fu_151_ce),
    .dout(grp_fu_151_p1)
);

ifft_1024_top_regslice_both #(
    .DataWidth( 64 ))
regslice_both_input_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TDATA),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_data_V_U_ack_in),
    .data_out(input_r_TDATA_int_regslice),
    .vld_out(input_r_TVALID_int_regslice),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_data_V_U_apdone_blk)
);

ifft_1024_top_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TKEEP),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_keep_V_U_ack_in),
    .data_out(input_r_TKEEP_int_regslice),
    .vld_out(regslice_both_input_r_V_keep_V_U_vld_out),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_keep_V_U_apdone_blk)
);

ifft_1024_top_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TSTRB),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_strb_V_U_ack_in),
    .data_out(input_r_TSTRB_int_regslice),
    .vld_out(regslice_both_input_r_V_strb_V_U_vld_out),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_strb_V_U_apdone_blk)
);

ifft_1024_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TLAST),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_last_V_U_ack_in),
    .data_out(input_r_TLAST_int_regslice),
    .vld_out(regslice_both_input_r_V_last_V_U_vld_out),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_last_V_U_apdone_blk)
);

ifft_1024_top_regslice_both #(
    .DataWidth( 64 ))
regslice_both_output_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TDATA),
    .vld_in(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TVALID),
    .ack_in(output_r_TREADY_int_regslice),
    .data_out(output_r_TDATA),
    .vld_out(regslice_both_output_r_V_data_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_data_V_U_apdone_blk)
);

ifft_1024_top_regslice_both #(
    .DataWidth( 8 ))
regslice_both_output_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TKEEP),
    .vld_in(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TVALID),
    .ack_in(regslice_both_output_r_V_keep_V_U_ack_in_dummy),
    .data_out(output_r_TKEEP),
    .vld_out(regslice_both_output_r_V_keep_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_keep_V_U_apdone_blk)
);

ifft_1024_top_regslice_both #(
    .DataWidth( 8 ))
regslice_both_output_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TSTRB),
    .vld_in(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TVALID),
    .ack_in(regslice_both_output_r_V_strb_V_U_ack_in_dummy),
    .data_out(output_r_TSTRB),
    .vld_out(regslice_both_output_r_V_strb_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_strb_V_U_apdone_blk)
);

ifft_1024_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_output_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TLAST),
    .vld_in(grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TVALID),
    .ack_in(regslice_both_output_r_V_last_V_U_ack_in_dummy),
    .data_out(output_r_TLAST),
    .vld_out(regslice_both_output_r_V_last_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ap_start_reg <= 1'b1;
        end else if ((grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ap_ready == 1'b1)) begin
            grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_ap_start_reg <= 1'b1;
        end else if ((grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_ap_ready == 1'b1)) begin
            grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ap_start_reg <= 1'b1;
        end else if ((grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ap_ready == 1'b1)) begin
            grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_ifft_fast_fu_100_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_ifft_fast_fu_100_ap_start_reg <= 1'b1;
        end else if ((grp_ifft_fast_fu_100_ap_ready == 1'b1)) begin
            grp_ifft_fast_fu_100_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_ifft_fast_fu_112_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_ifft_fast_fu_112_ap_start_reg <= 1'b1;
        end else if ((grp_ifft_fast_fu_112_ap_ready == 1'b1)) begin
            grp_ifft_fast_fu_112_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state8_on_subcall_done)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ga_M_imag_V_address0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ga_M_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        ga_M_imag_V_address0 = grp_ifft_fast_fu_100_x_M_imag_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        ga_M_imag_V_address0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_imag_V_address0;
    end else begin
        ga_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ga_M_imag_V_ce0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ga_M_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        ga_M_imag_V_ce0 = grp_ifft_fast_fu_100_x_M_imag_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        ga_M_imag_V_ce0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_imag_V_ce0;
    end else begin
        ga_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ga_M_imag_V_ce1 = grp_ifft_fast_fu_100_x_M_imag_ce1;
    end else begin
        ga_M_imag_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ga_M_imag_V_d0 = grp_ifft_fast_fu_100_x_M_imag_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        ga_M_imag_V_d0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_imag_V_d0;
    end else begin
        ga_M_imag_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ga_M_imag_V_we0 = grp_ifft_fast_fu_100_x_M_imag_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        ga_M_imag_V_we0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_imag_V_we0;
    end else begin
        ga_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ga_M_imag_V_we1 = grp_ifft_fast_fu_100_x_M_imag_we1;
    end else begin
        ga_M_imag_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ga_M_real_V_address0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ga_M_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        ga_M_real_V_address0 = grp_ifft_fast_fu_100_x_M_real_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        ga_M_real_V_address0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_real_V_address0;
    end else begin
        ga_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ga_M_real_V_ce0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ga_M_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        ga_M_real_V_ce0 = grp_ifft_fast_fu_100_x_M_real_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        ga_M_real_V_ce0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_real_V_ce0;
    end else begin
        ga_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ga_M_real_V_ce1 = grp_ifft_fast_fu_100_x_M_real_ce1;
    end else begin
        ga_M_real_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ga_M_real_V_d0 = grp_ifft_fast_fu_100_x_M_real_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        ga_M_real_V_d0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_real_V_d0;
    end else begin
        ga_M_real_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ga_M_real_V_we0 = grp_ifft_fast_fu_100_x_M_real_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        ga_M_real_V_we0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ga_M_real_V_we0;
    end else begin
        ga_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ga_M_real_V_we1 = grp_ifft_fast_fu_100_x_M_real_we1;
    end else begin
        ga_M_real_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        gb_M_imag_V_address0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_gb_M_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        gb_M_imag_V_address0 = grp_ifft_fast_fu_112_x_M_imag_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        gb_M_imag_V_address0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_imag_V_address0;
    end else begin
        gb_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        gb_M_imag_V_ce0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_gb_M_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        gb_M_imag_V_ce0 = grp_ifft_fast_fu_112_x_M_imag_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        gb_M_imag_V_ce0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_imag_V_ce0;
    end else begin
        gb_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        gb_M_imag_V_ce1 = grp_ifft_fast_fu_112_x_M_imag_ce1;
    end else begin
        gb_M_imag_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        gb_M_imag_V_d0 = grp_ifft_fast_fu_112_x_M_imag_d0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        gb_M_imag_V_d0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_imag_V_d0;
    end else begin
        gb_M_imag_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        gb_M_imag_V_we0 = grp_ifft_fast_fu_112_x_M_imag_we0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        gb_M_imag_V_we0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_imag_V_we0;
    end else begin
        gb_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        gb_M_imag_V_we1 = grp_ifft_fast_fu_112_x_M_imag_we1;
    end else begin
        gb_M_imag_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        gb_M_real_V_address0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_gb_M_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        gb_M_real_V_address0 = grp_ifft_fast_fu_112_x_M_real_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        gb_M_real_V_address0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_real_V_address0;
    end else begin
        gb_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        gb_M_real_V_ce0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_gb_M_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        gb_M_real_V_ce0 = grp_ifft_fast_fu_112_x_M_real_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        gb_M_real_V_ce0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_real_V_ce0;
    end else begin
        gb_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        gb_M_real_V_ce1 = grp_ifft_fast_fu_112_x_M_real_ce1;
    end else begin
        gb_M_real_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        gb_M_real_V_d0 = grp_ifft_fast_fu_112_x_M_real_d0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        gb_M_real_V_d0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_real_V_d0;
    end else begin
        gb_M_real_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        gb_M_real_V_we0 = grp_ifft_fast_fu_112_x_M_real_we0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        gb_M_real_V_we0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_gb_M_real_V_we0;
    end else begin
        gb_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        gb_M_real_V_we1 = grp_ifft_fast_fu_112_x_M_real_we1;
    end else begin
        gb_M_real_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_140_ce = grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_grp_fu_140_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_140_ce = grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_140_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_140_ce = grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_140_p_ce;
    end else begin
        grp_fu_140_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_140_p0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_grp_fu_140_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_140_p0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_140_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_140_p0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_140_p_din0;
    end else begin
        grp_fu_140_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_140_p1 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_grp_fu_140_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_140_p1 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_140_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_140_p1 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_140_p_din1;
    end else begin
        grp_fu_140_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_144_ce = grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_grp_fu_144_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_144_ce = grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_144_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_144_ce = grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_144_p_ce;
    end else begin
        grp_fu_144_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_144_p0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_grp_fu_144_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_144_p0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_144_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_144_p0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_144_p_din0;
    end else begin
        grp_fu_144_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_144_p1 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_grp_fu_144_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_144_p1 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_144_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_144_p1 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_144_p_din1;
    end else begin
        grp_fu_144_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_148_ce = grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_148_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_148_ce = grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_148_p_ce;
    end else begin
        grp_fu_148_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_148_p0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_148_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_148_p0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_148_p_din0;
    end else begin
        grp_fu_148_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_151_ce = grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_151_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_151_ce = grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_151_p_ce;
    end else begin
        grp_fu_151_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_151_p0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_grp_fu_151_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_151_p0 = grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_grp_fu_151_p_din0;
    end else begin
        grp_fu_151_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        input_r_TREADY_int_regslice = grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_input_r_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_r_TREADY_int_regslice = grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_input_r_TREADY;
    end else begin
        input_r_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((regslice_both_output_r_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state8_on_subcall_done = ((grp_ifft_fast_fu_112_ap_done == 1'b0) | (grp_ifft_fast_fu_100_ap_done == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ap_start = grp_ifft_1024_top_Pipeline_VITIS_LOOP_57_1_fu_72_ap_start_reg;

assign grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_ap_start = grp_ifft_1024_top_Pipeline_VITIS_LOOP_63_2_fu_86_ap_start_reg;

assign grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ap_start = grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_ap_start_reg;

assign grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TREADY = (output_r_TREADY_int_regslice & ap_CS_fsm_state10);

assign grp_ifft_fast_fu_100_ap_start = grp_ifft_fast_fu_100_ap_start_reg;

assign grp_ifft_fast_fu_112_ap_start = grp_ifft_fast_fu_112_ap_start_reg;

assign input_r_TREADY = regslice_both_input_r_V_data_V_U_ack_in;

assign output_r_TVALID = regslice_both_output_r_V_data_V_U_vld_out;

assign output_r_TVALID_int_regslice = grp_ifft_1024_top_Pipeline_VITIS_LOOP_72_3_fu_124_output_r_TVALID;

endmodule //ifft_1024_top
