// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ifft_1024_top_ifft_1024_top_Pipeline_VITIS_LOOP_72_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        output_r_TREADY,
        ga_M_real_V_address0,
        ga_M_real_V_ce0,
        ga_M_real_V_q0,
        gb_M_real_V_address0,
        gb_M_real_V_ce0,
        gb_M_real_V_q0,
        ga_M_imag_V_address0,
        ga_M_imag_V_ce0,
        ga_M_imag_V_q0,
        gb_M_imag_V_address0,
        gb_M_imag_V_ce0,
        gb_M_imag_V_q0,
        output_r_TDATA,
        output_r_TVALID,
        output_r_TKEEP,
        output_r_TSTRB,
        output_r_TLAST,
        grp_fu_140_p_din0,
        grp_fu_140_p_din1,
        grp_fu_140_p_dout0,
        grp_fu_140_p_ce,
        grp_fu_144_p_din0,
        grp_fu_144_p_din1,
        grp_fu_144_p_dout0,
        grp_fu_144_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   output_r_TREADY;
output  [9:0] ga_M_real_V_address0;
output   ga_M_real_V_ce0;
input  [23:0] ga_M_real_V_q0;
output  [9:0] gb_M_real_V_address0;
output   gb_M_real_V_ce0;
input  [23:0] gb_M_real_V_q0;
output  [9:0] ga_M_imag_V_address0;
output   ga_M_imag_V_ce0;
input  [23:0] ga_M_imag_V_q0;
output  [9:0] gb_M_imag_V_address0;
output   gb_M_imag_V_ce0;
input  [23:0] gb_M_imag_V_q0;
output  [63:0] output_r_TDATA;
output   output_r_TVALID;
output  [7:0] output_r_TKEEP;
output  [7:0] output_r_TSTRB;
output  [0:0] output_r_TLAST;
output  [31:0] grp_fu_140_p_din0;
output  [31:0] grp_fu_140_p_din1;
input  [31:0] grp_fu_140_p_dout0;
output   grp_fu_140_p_ce;
output  [31:0] grp_fu_144_p_din0;
output  [31:0] grp_fu_144_p_din1;
input  [31:0] grp_fu_144_p_dout0;
output   grp_fu_144_p_ce;

reg ap_idle;
reg ga_M_real_V_ce0;
reg gb_M_real_V_ce0;
reg ga_M_imag_V_ce0;
reg gb_M_imag_V_ce0;
reg output_r_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
reg    ap_block_state10_pp0_stage0_iter9;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln72_fu_212_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    output_r_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] tmp_last_V_fu_232_p2;
reg   [0:0] tmp_last_V_reg_905;
reg   [0:0] tmp_last_V_reg_905_pp0_iter1_reg;
reg   [0:0] tmp_last_V_reg_905_pp0_iter2_reg;
reg   [0:0] tmp_last_V_reg_905_pp0_iter3_reg;
reg   [0:0] tmp_last_V_reg_905_pp0_iter4_reg;
reg   [0:0] tmp_last_V_reg_905_pp0_iter5_reg;
reg   [0:0] tmp_last_V_reg_905_pp0_iter6_reg;
reg   [0:0] tmp_last_V_reg_905_pp0_iter7_reg;
reg   [0:0] tmp_last_V_reg_905_pp0_iter8_reg;
wire   [24:0] ret_V_fu_251_p2;
reg   [24:0] ret_V_reg_910;
reg   [0:0] p_Result_14_reg_917;
reg   [0:0] p_Result_14_reg_917_pp0_iter2_reg;
reg   [0:0] p_Result_14_reg_917_pp0_iter3_reg;
reg   [0:0] p_Result_14_reg_917_pp0_iter4_reg;
wire   [24:0] ret_V_6_fu_273_p2;
reg   [24:0] ret_V_6_reg_923;
reg   [0:0] p_Result_17_reg_930;
reg   [0:0] p_Result_17_reg_930_pp0_iter2_reg;
reg   [0:0] p_Result_17_reg_930_pp0_iter3_reg;
reg   [0:0] p_Result_17_reg_930_pp0_iter4_reg;
wire   [0:0] icmp_ln1136_fu_287_p2;
reg   [0:0] icmp_ln1136_reg_936;
reg   [0:0] icmp_ln1136_reg_936_pp0_iter3_reg;
reg   [0:0] icmp_ln1136_reg_936_pp0_iter4_reg;
reg   [0:0] icmp_ln1136_reg_936_pp0_iter5_reg;
reg   [0:0] icmp_ln1136_reg_936_pp0_iter6_reg;
reg   [0:0] icmp_ln1136_reg_936_pp0_iter7_reg;
reg   [0:0] icmp_ln1136_reg_936_pp0_iter8_reg;
wire   [24:0] tmp_V_4_fu_297_p3;
reg   [24:0] tmp_V_4_reg_941;
reg   [24:0] tmp_V_4_reg_941_pp0_iter3_reg;
reg   [31:0] l_fu_325_p3;
reg   [31:0] l_reg_948;
reg   [31:0] l_reg_948_pp0_iter3_reg;
wire   [31:0] sub_ln1145_fu_333_p2;
reg   [31:0] sub_ln1145_reg_953;
reg   [31:0] sub_ln1145_reg_953_pp0_iter3_reg;
wire   [24:0] trunc_ln1145_fu_339_p1;
reg   [24:0] trunc_ln1145_reg_959;
wire   [4:0] trunc_ln1148_fu_343_p1;
reg   [4:0] trunc_ln1148_reg_964;
wire   [7:0] trunc_ln1144_fu_347_p1;
reg   [7:0] trunc_ln1144_reg_969;
reg   [7:0] trunc_ln1144_reg_969_pp0_iter3_reg;
reg   [7:0] trunc_ln1144_reg_969_pp0_iter4_reg;
wire   [0:0] icmp_ln1136_1_fu_351_p2;
reg   [0:0] icmp_ln1136_1_reg_974;
reg   [0:0] icmp_ln1136_1_reg_974_pp0_iter3_reg;
reg   [0:0] icmp_ln1136_1_reg_974_pp0_iter4_reg;
reg   [0:0] icmp_ln1136_1_reg_974_pp0_iter5_reg;
reg   [0:0] icmp_ln1136_1_reg_974_pp0_iter6_reg;
reg   [0:0] icmp_ln1136_1_reg_974_pp0_iter7_reg;
reg   [0:0] icmp_ln1136_1_reg_974_pp0_iter8_reg;
wire   [24:0] tmp_V_5_fu_361_p3;
reg   [24:0] tmp_V_5_reg_979;
reg   [24:0] tmp_V_5_reg_979_pp0_iter3_reg;
reg   [31:0] l_1_fu_389_p3;
reg   [31:0] l_1_reg_986;
reg   [31:0] l_1_reg_986_pp0_iter3_reg;
wire   [31:0] sub_ln1145_1_fu_397_p2;
reg   [31:0] sub_ln1145_1_reg_991;
reg   [31:0] sub_ln1145_1_reg_991_pp0_iter3_reg;
wire   [24:0] trunc_ln1145_1_fu_403_p1;
reg   [24:0] trunc_ln1145_1_reg_997;
wire   [4:0] trunc_ln1148_1_fu_407_p1;
reg   [4:0] trunc_ln1148_1_reg_1002;
wire   [7:0] trunc_ln1144_1_fu_411_p1;
reg   [7:0] trunc_ln1144_1_reg_1007;
reg   [7:0] trunc_ln1144_1_reg_1007_pp0_iter3_reg;
reg   [7:0] trunc_ln1144_1_reg_1007_pp0_iter4_reg;
wire   [1:0] or_ln_fu_506_p3;
reg   [1:0] or_ln_reg_1012;
wire   [0:0] icmp_ln1159_fu_514_p2;
reg   [0:0] icmp_ln1159_reg_1017;
wire   [1:0] or_ln1150_1_fu_611_p3;
reg   [1:0] or_ln1150_1_reg_1022;
wire   [0:0] icmp_ln1159_1_fu_619_p2;
reg   [0:0] icmp_ln1159_1_reg_1027;
reg   [62:0] m_9_reg_1032;
reg   [0:0] p_Result_5_reg_1037;
reg   [62:0] m_reg_1042;
reg   [0:0] p_Result_12_reg_1047;
wire   [31:0] LD_fu_787_p1;
reg   [31:0] LD_reg_1052;
wire   [31:0] LD_1_fu_831_p1;
reg   [31:0] LD_1_reg_1057;
wire   [31:0] bitcast_ln810_fu_835_p1;
wire   [31:0] bitcast_ln810_1_fu_839_p1;
wire   [63:0] i_2_cast_fu_224_p1;
reg   [10:0] i_fu_120;
wire   [10:0] add_ln72_fu_218_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_i_2;
reg    ap_block_pp0_stage0_01001;
wire  signed [24:0] sext_ln859_1_fu_247_p1;
wire  signed [24:0] sext_ln859_fu_243_p1;
wire  signed [24:0] sext_ln859_3_fu_269_p1;
wire  signed [24:0] sext_ln859_2_fu_265_p1;
wire   [24:0] tmp_V_fu_292_p2;
reg   [24:0] p_Result_s_fu_303_p4;
wire   [25:0] p_Result_15_fu_313_p3;
wire  signed [31:0] sext_ln1244_fu_321_p1;
wire   [24:0] tmp_V_2_fu_356_p2;
reg   [24:0] p_Result_8_fu_367_p4;
wire   [25:0] p_Result_18_fu_377_p3;
wire  signed [31:0] sext_ln1244_1_fu_385_p1;
wire   [31:0] lsb_index_fu_415_p2;
wire   [30:0] tmp_fu_420_p4;
wire   [4:0] sub_ln1148_fu_436_p2;
wire   [24:0] zext_ln1148_fu_441_p1;
wire   [24:0] lshr_ln1148_fu_445_p2;
wire   [24:0] p_Result_3_fu_451_p2;
wire   [0:0] icmp_ln1147_fu_430_p2;
wire   [0:0] icmp_ln1148_fu_456_p2;
wire   [0:0] tmp_1_fu_468_p3;
wire   [24:0] add_ln1150_fu_482_p2;
wire   [0:0] p_Result_4_fu_487_p3;
wire   [0:0] xor_ln1150_fu_476_p2;
wire   [0:0] and_ln1150_fu_494_p2;
wire   [0:0] a_fu_462_p2;
wire   [0:0] or_ln1150_2_fu_500_p2;
wire   [31:0] lsb_index_1_fu_520_p2;
wire   [30:0] tmp_5_fu_525_p4;
wire   [4:0] sub_ln1148_1_fu_541_p2;
wire   [24:0] zext_ln1148_1_fu_546_p1;
wire   [24:0] lshr_ln1148_1_fu_550_p2;
wire   [24:0] p_Result_10_fu_556_p2;
wire   [0:0] icmp_ln1147_1_fu_535_p2;
wire   [0:0] icmp_ln1148_1_fu_561_p2;
wire   [0:0] tmp_6_fu_573_p3;
wire   [24:0] add_ln1150_1_fu_587_p2;
wire   [0:0] p_Result_11_fu_592_p3;
wire   [0:0] xor_ln1150_1_fu_581_p2;
wire   [0:0] and_ln1150_1_fu_599_p2;
wire   [0:0] a_1_fu_567_p2;
wire   [0:0] or_ln1150_fu_605_p2;
wire   [31:0] add_ln1159_fu_628_p2;
wire   [63:0] zext_ln1158_fu_625_p1;
wire   [63:0] zext_ln1159_fu_633_p1;
wire   [63:0] zext_ln1160_fu_643_p1;
wire   [63:0] lshr_ln1159_fu_637_p2;
wire   [63:0] shl_ln1160_fu_646_p2;
wire   [63:0] m_2_fu_652_p3;
wire   [63:0] zext_ln1162_fu_659_p1;
wire   [63:0] m_3_fu_662_p2;
wire   [31:0] add_ln1159_1_fu_689_p2;
wire   [63:0] zext_ln1158_1_fu_686_p1;
wire   [63:0] zext_ln1159_1_fu_694_p1;
wire   [63:0] zext_ln1160_1_fu_704_p1;
wire   [63:0] lshr_ln1159_1_fu_698_p2;
wire   [63:0] shl_ln1160_1_fu_707_p2;
wire   [63:0] m_5_fu_713_p3;
wire   [63:0] zext_ln1162_1_fu_720_p1;
wire   [63:0] m_6_fu_723_p2;
wire   [7:0] sub_ln1165_fu_757_p2;
wire   [7:0] select_ln1144_fu_750_p3;
wire   [7:0] add_ln1170_fu_762_p2;
wire   [63:0] zext_ln1163_fu_747_p1;
wire   [8:0] tmp_9_fu_768_p3;
wire   [63:0] p_Result_16_fu_775_p5;
wire   [7:0] sub_ln1165_1_fu_801_p2;
wire   [7:0] select_ln1144_1_fu_794_p3;
wire   [7:0] add_ln1170_1_fu_806_p2;
wire   [63:0] zext_ln1163_1_fu_791_p1;
wire   [8:0] tmp_2_fu_812_p3;
wire   [63:0] p_Result_19_fu_819_p5;
wire   [31:0] bitcast_ln304_1_fu_843_p1;
wire   [31:0] bitcast_ln304_fu_854_p1;
wire   [31:0] select_ln304_1_fu_858_p3;
wire   [31:0] select_ln304_fu_847_p3;
reg    grp_fu_194_ce;
reg    grp_fu_199_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_done_reg = 1'b0;
end

ifft_1024_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln72_fu_212_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_120 <= add_ln72_fu_218_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_120 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1136_1_reg_974_pp0_iter4_reg == 1'd0))) begin
        LD_1_reg_1057 <= LD_1_fu_831_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1136_reg_936_pp0_iter4_reg == 1'd0))) begin
        LD_reg_1052 <= LD_fu_787_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        p_Result_14_reg_917 <= ret_V_fu_251_p2[32'd24];
        p_Result_17_reg_930 <= ret_V_6_fu_273_p2[32'd24];
        ret_V_6_reg_923 <= ret_V_6_fu_273_p2;
        ret_V_reg_910 <= ret_V_fu_251_p2;
        tmp_last_V_reg_905_pp0_iter1_reg <= tmp_last_V_reg_905;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        icmp_ln1136_1_reg_974 <= icmp_ln1136_1_fu_351_p2;
        icmp_ln1136_1_reg_974_pp0_iter3_reg <= icmp_ln1136_1_reg_974;
        icmp_ln1136_1_reg_974_pp0_iter4_reg <= icmp_ln1136_1_reg_974_pp0_iter3_reg;
        icmp_ln1136_1_reg_974_pp0_iter5_reg <= icmp_ln1136_1_reg_974_pp0_iter4_reg;
        icmp_ln1136_1_reg_974_pp0_iter6_reg <= icmp_ln1136_1_reg_974_pp0_iter5_reg;
        icmp_ln1136_1_reg_974_pp0_iter7_reg <= icmp_ln1136_1_reg_974_pp0_iter6_reg;
        icmp_ln1136_1_reg_974_pp0_iter8_reg <= icmp_ln1136_1_reg_974_pp0_iter7_reg;
        icmp_ln1136_reg_936 <= icmp_ln1136_fu_287_p2;
        icmp_ln1136_reg_936_pp0_iter3_reg <= icmp_ln1136_reg_936;
        icmp_ln1136_reg_936_pp0_iter4_reg <= icmp_ln1136_reg_936_pp0_iter3_reg;
        icmp_ln1136_reg_936_pp0_iter5_reg <= icmp_ln1136_reg_936_pp0_iter4_reg;
        icmp_ln1136_reg_936_pp0_iter6_reg <= icmp_ln1136_reg_936_pp0_iter5_reg;
        icmp_ln1136_reg_936_pp0_iter7_reg <= icmp_ln1136_reg_936_pp0_iter6_reg;
        icmp_ln1136_reg_936_pp0_iter8_reg <= icmp_ln1136_reg_936_pp0_iter7_reg;
        l_1_reg_986 <= l_1_fu_389_p3;
        l_1_reg_986_pp0_iter3_reg <= l_1_reg_986;
        l_reg_948 <= l_fu_325_p3;
        l_reg_948_pp0_iter3_reg <= l_reg_948;
        p_Result_14_reg_917_pp0_iter2_reg <= p_Result_14_reg_917;
        p_Result_14_reg_917_pp0_iter3_reg <= p_Result_14_reg_917_pp0_iter2_reg;
        p_Result_14_reg_917_pp0_iter4_reg <= p_Result_14_reg_917_pp0_iter3_reg;
        p_Result_17_reg_930_pp0_iter2_reg <= p_Result_17_reg_930;
        p_Result_17_reg_930_pp0_iter3_reg <= p_Result_17_reg_930_pp0_iter2_reg;
        p_Result_17_reg_930_pp0_iter4_reg <= p_Result_17_reg_930_pp0_iter3_reg;
        sub_ln1145_1_reg_991 <= sub_ln1145_1_fu_397_p2;
        sub_ln1145_1_reg_991_pp0_iter3_reg <= sub_ln1145_1_reg_991;
        sub_ln1145_reg_953 <= sub_ln1145_fu_333_p2;
        sub_ln1145_reg_953_pp0_iter3_reg <= sub_ln1145_reg_953;
        tmp_V_4_reg_941 <= tmp_V_4_fu_297_p3;
        tmp_V_4_reg_941_pp0_iter3_reg <= tmp_V_4_reg_941;
        tmp_V_5_reg_979 <= tmp_V_5_fu_361_p3;
        tmp_V_5_reg_979_pp0_iter3_reg <= tmp_V_5_reg_979;
        tmp_last_V_reg_905_pp0_iter2_reg <= tmp_last_V_reg_905_pp0_iter1_reg;
        tmp_last_V_reg_905_pp0_iter3_reg <= tmp_last_V_reg_905_pp0_iter2_reg;
        tmp_last_V_reg_905_pp0_iter4_reg <= tmp_last_V_reg_905_pp0_iter3_reg;
        tmp_last_V_reg_905_pp0_iter5_reg <= tmp_last_V_reg_905_pp0_iter4_reg;
        tmp_last_V_reg_905_pp0_iter6_reg <= tmp_last_V_reg_905_pp0_iter5_reg;
        tmp_last_V_reg_905_pp0_iter7_reg <= tmp_last_V_reg_905_pp0_iter6_reg;
        tmp_last_V_reg_905_pp0_iter8_reg <= tmp_last_V_reg_905_pp0_iter7_reg;
        trunc_ln1144_1_reg_1007 <= trunc_ln1144_1_fu_411_p1;
        trunc_ln1144_1_reg_1007_pp0_iter3_reg <= trunc_ln1144_1_reg_1007;
        trunc_ln1144_1_reg_1007_pp0_iter4_reg <= trunc_ln1144_1_reg_1007_pp0_iter3_reg;
        trunc_ln1144_reg_969 <= trunc_ln1144_fu_347_p1;
        trunc_ln1144_reg_969_pp0_iter3_reg <= trunc_ln1144_reg_969;
        trunc_ln1144_reg_969_pp0_iter4_reg <= trunc_ln1144_reg_969_pp0_iter3_reg;
        trunc_ln1145_1_reg_997 <= trunc_ln1145_1_fu_403_p1;
        trunc_ln1145_reg_959 <= trunc_ln1145_fu_339_p1;
        trunc_ln1148_1_reg_1002 <= trunc_ln1148_1_fu_407_p1;
        trunc_ln1148_reg_964 <= trunc_ln1148_fu_343_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1136_1_reg_974 == 1'd0))) begin
        icmp_ln1159_1_reg_1027 <= icmp_ln1159_1_fu_619_p2;
        or_ln1150_1_reg_1022[0] <= or_ln1150_1_fu_611_p3[0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1136_reg_936 == 1'd0))) begin
        icmp_ln1159_reg_1017 <= icmp_ln1159_fu_514_p2;
        or_ln_reg_1012[0] <= or_ln_fu_506_p3[0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1136_reg_936_pp0_iter3_reg == 1'd0))) begin
        m_9_reg_1032 <= {{m_3_fu_662_p2[63:1]}};
        p_Result_5_reg_1037 <= m_3_fu_662_p2[32'd25];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1136_1_reg_974_pp0_iter3_reg == 1'd0))) begin
        m_reg_1042 <= {{m_6_fu_723_p2[63:1]}};
        p_Result_12_reg_1047 <= m_6_fu_723_p2[32'd25];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln72_fu_212_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_last_V_reg_905 <= tmp_last_V_fu_232_p2;
    end
end

always @ (*) begin
    if (((icmp_ln72_fu_212_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_2 = 11'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_120;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ga_M_imag_V_ce0 = 1'b1;
    end else begin
        ga_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ga_M_real_V_ce0 = 1'b1;
    end else begin
        ga_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gb_M_imag_V_ce0 = 1'b1;
    end else begin
        gb_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gb_M_real_V_ce0 = 1'b1;
    end else begin
        gb_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_194_ce = 1'b1;
    end else begin
        grp_fu_194_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_199_ce = 1'b1;
    end else begin
        grp_fu_199_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        output_r_TDATA_blk_n = output_r_TREADY;
    end else begin
        output_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        output_r_TVALID = 1'b1;
    end else begin
        output_r_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LD_1_fu_831_p1 = p_Result_19_fu_819_p5[31:0];

assign LD_fu_787_p1 = p_Result_16_fu_775_p5[31:0];

assign a_1_fu_567_p2 = (icmp_ln1148_1_fu_561_p2 & icmp_ln1147_1_fu_535_p2);

assign a_fu_462_p2 = (icmp_ln1148_fu_456_p2 & icmp_ln1147_fu_430_p2);

assign add_ln1150_1_fu_587_p2 = ($signed(trunc_ln1145_1_reg_997) + $signed(25'd33554408));

assign add_ln1150_fu_482_p2 = ($signed(trunc_ln1145_reg_959) + $signed(25'd33554408));

assign add_ln1159_1_fu_689_p2 = ($signed(sub_ln1145_1_reg_991_pp0_iter3_reg) + $signed(32'd4294967271));

assign add_ln1159_fu_628_p2 = ($signed(sub_ln1145_reg_953_pp0_iter3_reg) + $signed(32'd4294967271));

assign add_ln1170_1_fu_806_p2 = (sub_ln1165_1_fu_801_p2 + select_ln1144_1_fu_794_p3);

assign add_ln1170_fu_762_p2 = (sub_ln1165_fu_757_p2 + select_ln1144_fu_750_p3);

assign add_ln72_fu_218_p2 = (ap_sig_allocacmp_i_2 + 11'd1);

assign and_ln1150_1_fu_599_p2 = (xor_ln1150_1_fu_581_p2 & p_Result_11_fu_592_p3);

assign and_ln1150_fu_494_p2 = (xor_ln1150_fu_476_p2 & p_Result_4_fu_487_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((output_r_TREADY == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((output_r_TREADY == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((output_r_TREADY == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter9 = (output_r_TREADY == 1'b0);
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bitcast_ln304_1_fu_843_p1 = grp_fu_140_p_dout0;

assign bitcast_ln304_fu_854_p1 = grp_fu_144_p_dout0;

assign bitcast_ln810_1_fu_839_p1 = LD_1_reg_1057;

assign bitcast_ln810_fu_835_p1 = LD_reg_1052;

assign ga_M_imag_V_address0 = i_2_cast_fu_224_p1;

assign ga_M_real_V_address0 = i_2_cast_fu_224_p1;

assign gb_M_imag_V_address0 = i_2_cast_fu_224_p1;

assign gb_M_real_V_address0 = i_2_cast_fu_224_p1;

assign grp_fu_140_p_ce = grp_fu_194_ce;

assign grp_fu_140_p_din0 = bitcast_ln810_fu_835_p1;

assign grp_fu_140_p_din1 = 32'd1216348160;

assign grp_fu_144_p_ce = grp_fu_199_ce;

assign grp_fu_144_p_din0 = bitcast_ln810_1_fu_839_p1;

assign grp_fu_144_p_din1 = 32'd1216348160;

assign i_2_cast_fu_224_p1 = ap_sig_allocacmp_i_2;

assign icmp_ln1136_1_fu_351_p2 = ((ret_V_6_reg_923 == 25'd0) ? 1'b1 : 1'b0);

assign icmp_ln1136_fu_287_p2 = ((ret_V_reg_910 == 25'd0) ? 1'b1 : 1'b0);

assign icmp_ln1147_1_fu_535_p2 = (($signed(tmp_5_fu_525_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1147_fu_430_p2 = (($signed(tmp_fu_420_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1148_1_fu_561_p2 = ((p_Result_10_fu_556_p2 != 25'd0) ? 1'b1 : 1'b0);

assign icmp_ln1148_fu_456_p2 = ((p_Result_3_fu_451_p2 != 25'd0) ? 1'b1 : 1'b0);

assign icmp_ln1159_1_fu_619_p2 = (($signed(lsb_index_1_fu_520_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1159_fu_514_p2 = (($signed(lsb_index_fu_415_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln72_fu_212_p2 = ((ap_sig_allocacmp_i_2 == 11'd1024) ? 1'b1 : 1'b0);


always @ (sext_ln1244_1_fu_385_p1) begin
    if (sext_ln1244_1_fu_385_p1[0] == 1'b1) begin
        l_1_fu_389_p3 = 32'd0;
    end else if (sext_ln1244_1_fu_385_p1[1] == 1'b1) begin
        l_1_fu_389_p3 = 32'd1;
    end else if (sext_ln1244_1_fu_385_p1[2] == 1'b1) begin
        l_1_fu_389_p3 = 32'd2;
    end else if (sext_ln1244_1_fu_385_p1[3] == 1'b1) begin
        l_1_fu_389_p3 = 32'd3;
    end else if (sext_ln1244_1_fu_385_p1[4] == 1'b1) begin
        l_1_fu_389_p3 = 32'd4;
    end else if (sext_ln1244_1_fu_385_p1[5] == 1'b1) begin
        l_1_fu_389_p3 = 32'd5;
    end else if (sext_ln1244_1_fu_385_p1[6] == 1'b1) begin
        l_1_fu_389_p3 = 32'd6;
    end else if (sext_ln1244_1_fu_385_p1[7] == 1'b1) begin
        l_1_fu_389_p3 = 32'd7;
    end else if (sext_ln1244_1_fu_385_p1[8] == 1'b1) begin
        l_1_fu_389_p3 = 32'd8;
    end else if (sext_ln1244_1_fu_385_p1[9] == 1'b1) begin
        l_1_fu_389_p3 = 32'd9;
    end else if (sext_ln1244_1_fu_385_p1[10] == 1'b1) begin
        l_1_fu_389_p3 = 32'd10;
    end else if (sext_ln1244_1_fu_385_p1[11] == 1'b1) begin
        l_1_fu_389_p3 = 32'd11;
    end else if (sext_ln1244_1_fu_385_p1[12] == 1'b1) begin
        l_1_fu_389_p3 = 32'd12;
    end else if (sext_ln1244_1_fu_385_p1[13] == 1'b1) begin
        l_1_fu_389_p3 = 32'd13;
    end else if (sext_ln1244_1_fu_385_p1[14] == 1'b1) begin
        l_1_fu_389_p3 = 32'd14;
    end else if (sext_ln1244_1_fu_385_p1[15] == 1'b1) begin
        l_1_fu_389_p3 = 32'd15;
    end else if (sext_ln1244_1_fu_385_p1[16] == 1'b1) begin
        l_1_fu_389_p3 = 32'd16;
    end else if (sext_ln1244_1_fu_385_p1[17] == 1'b1) begin
        l_1_fu_389_p3 = 32'd17;
    end else if (sext_ln1244_1_fu_385_p1[18] == 1'b1) begin
        l_1_fu_389_p3 = 32'd18;
    end else if (sext_ln1244_1_fu_385_p1[19] == 1'b1) begin
        l_1_fu_389_p3 = 32'd19;
    end else if (sext_ln1244_1_fu_385_p1[20] == 1'b1) begin
        l_1_fu_389_p3 = 32'd20;
    end else if (sext_ln1244_1_fu_385_p1[21] == 1'b1) begin
        l_1_fu_389_p3 = 32'd21;
    end else if (sext_ln1244_1_fu_385_p1[22] == 1'b1) begin
        l_1_fu_389_p3 = 32'd22;
    end else if (sext_ln1244_1_fu_385_p1[23] == 1'b1) begin
        l_1_fu_389_p3 = 32'd23;
    end else if (sext_ln1244_1_fu_385_p1[24] == 1'b1) begin
        l_1_fu_389_p3 = 32'd24;
    end else if (sext_ln1244_1_fu_385_p1[25] == 1'b1) begin
        l_1_fu_389_p3 = 32'd25;
    end else if (sext_ln1244_1_fu_385_p1[26] == 1'b1) begin
        l_1_fu_389_p3 = 32'd26;
    end else if (sext_ln1244_1_fu_385_p1[27] == 1'b1) begin
        l_1_fu_389_p3 = 32'd27;
    end else if (sext_ln1244_1_fu_385_p1[28] == 1'b1) begin
        l_1_fu_389_p3 = 32'd28;
    end else if (sext_ln1244_1_fu_385_p1[29] == 1'b1) begin
        l_1_fu_389_p3 = 32'd29;
    end else if (sext_ln1244_1_fu_385_p1[30] == 1'b1) begin
        l_1_fu_389_p3 = 32'd30;
    end else if (sext_ln1244_1_fu_385_p1[31] == 1'b1) begin
        l_1_fu_389_p3 = 32'd31;
    end else begin
        l_1_fu_389_p3 = 32'd32;
    end
end


always @ (sext_ln1244_fu_321_p1) begin
    if (sext_ln1244_fu_321_p1[0] == 1'b1) begin
        l_fu_325_p3 = 32'd0;
    end else if (sext_ln1244_fu_321_p1[1] == 1'b1) begin
        l_fu_325_p3 = 32'd1;
    end else if (sext_ln1244_fu_321_p1[2] == 1'b1) begin
        l_fu_325_p3 = 32'd2;
    end else if (sext_ln1244_fu_321_p1[3] == 1'b1) begin
        l_fu_325_p3 = 32'd3;
    end else if (sext_ln1244_fu_321_p1[4] == 1'b1) begin
        l_fu_325_p3 = 32'd4;
    end else if (sext_ln1244_fu_321_p1[5] == 1'b1) begin
        l_fu_325_p3 = 32'd5;
    end else if (sext_ln1244_fu_321_p1[6] == 1'b1) begin
        l_fu_325_p3 = 32'd6;
    end else if (sext_ln1244_fu_321_p1[7] == 1'b1) begin
        l_fu_325_p3 = 32'd7;
    end else if (sext_ln1244_fu_321_p1[8] == 1'b1) begin
        l_fu_325_p3 = 32'd8;
    end else if (sext_ln1244_fu_321_p1[9] == 1'b1) begin
        l_fu_325_p3 = 32'd9;
    end else if (sext_ln1244_fu_321_p1[10] == 1'b1) begin
        l_fu_325_p3 = 32'd10;
    end else if (sext_ln1244_fu_321_p1[11] == 1'b1) begin
        l_fu_325_p3 = 32'd11;
    end else if (sext_ln1244_fu_321_p1[12] == 1'b1) begin
        l_fu_325_p3 = 32'd12;
    end else if (sext_ln1244_fu_321_p1[13] == 1'b1) begin
        l_fu_325_p3 = 32'd13;
    end else if (sext_ln1244_fu_321_p1[14] == 1'b1) begin
        l_fu_325_p3 = 32'd14;
    end else if (sext_ln1244_fu_321_p1[15] == 1'b1) begin
        l_fu_325_p3 = 32'd15;
    end else if (sext_ln1244_fu_321_p1[16] == 1'b1) begin
        l_fu_325_p3 = 32'd16;
    end else if (sext_ln1244_fu_321_p1[17] == 1'b1) begin
        l_fu_325_p3 = 32'd17;
    end else if (sext_ln1244_fu_321_p1[18] == 1'b1) begin
        l_fu_325_p3 = 32'd18;
    end else if (sext_ln1244_fu_321_p1[19] == 1'b1) begin
        l_fu_325_p3 = 32'd19;
    end else if (sext_ln1244_fu_321_p1[20] == 1'b1) begin
        l_fu_325_p3 = 32'd20;
    end else if (sext_ln1244_fu_321_p1[21] == 1'b1) begin
        l_fu_325_p3 = 32'd21;
    end else if (sext_ln1244_fu_321_p1[22] == 1'b1) begin
        l_fu_325_p3 = 32'd22;
    end else if (sext_ln1244_fu_321_p1[23] == 1'b1) begin
        l_fu_325_p3 = 32'd23;
    end else if (sext_ln1244_fu_321_p1[24] == 1'b1) begin
        l_fu_325_p3 = 32'd24;
    end else if (sext_ln1244_fu_321_p1[25] == 1'b1) begin
        l_fu_325_p3 = 32'd25;
    end else if (sext_ln1244_fu_321_p1[26] == 1'b1) begin
        l_fu_325_p3 = 32'd26;
    end else if (sext_ln1244_fu_321_p1[27] == 1'b1) begin
        l_fu_325_p3 = 32'd27;
    end else if (sext_ln1244_fu_321_p1[28] == 1'b1) begin
        l_fu_325_p3 = 32'd28;
    end else if (sext_ln1244_fu_321_p1[29] == 1'b1) begin
        l_fu_325_p3 = 32'd29;
    end else if (sext_ln1244_fu_321_p1[30] == 1'b1) begin
        l_fu_325_p3 = 32'd30;
    end else if (sext_ln1244_fu_321_p1[31] == 1'b1) begin
        l_fu_325_p3 = 32'd31;
    end else begin
        l_fu_325_p3 = 32'd32;
    end
end

assign lsb_index_1_fu_520_p2 = ($signed(sub_ln1145_1_reg_991) + $signed(32'd4294967272));

assign lsb_index_fu_415_p2 = ($signed(sub_ln1145_reg_953) + $signed(32'd4294967272));

assign lshr_ln1148_1_fu_550_p2 = 25'd33554431 >> zext_ln1148_1_fu_546_p1;

assign lshr_ln1148_fu_445_p2 = 25'd33554431 >> zext_ln1148_fu_441_p1;

assign lshr_ln1159_1_fu_698_p2 = zext_ln1158_1_fu_686_p1 >> zext_ln1159_1_fu_694_p1;

assign lshr_ln1159_fu_637_p2 = zext_ln1158_fu_625_p1 >> zext_ln1159_fu_633_p1;

assign m_2_fu_652_p3 = ((icmp_ln1159_reg_1017[0:0] == 1'b1) ? lshr_ln1159_fu_637_p2 : shl_ln1160_fu_646_p2);

assign m_3_fu_662_p2 = (m_2_fu_652_p3 + zext_ln1162_fu_659_p1);

assign m_5_fu_713_p3 = ((icmp_ln1159_1_reg_1027[0:0] == 1'b1) ? lshr_ln1159_1_fu_698_p2 : shl_ln1160_1_fu_707_p2);

assign m_6_fu_723_p2 = (m_5_fu_713_p3 + zext_ln1162_1_fu_720_p1);

assign or_ln1150_1_fu_611_p3 = {{1'd0}, {or_ln1150_fu_605_p2}};

assign or_ln1150_2_fu_500_p2 = (and_ln1150_fu_494_p2 | a_fu_462_p2);

assign or_ln1150_fu_605_p2 = (and_ln1150_1_fu_599_p2 | a_1_fu_567_p2);

assign or_ln_fu_506_p3 = {{1'd0}, {or_ln1150_2_fu_500_p2}};

assign output_r_TDATA = {{select_ln304_1_fu_858_p3}, {select_ln304_fu_847_p3}};

assign output_r_TKEEP = 8'd255;

assign output_r_TLAST = tmp_last_V_reg_905_pp0_iter8_reg;

assign output_r_TSTRB = 8'd0;

assign p_Result_10_fu_556_p2 = (tmp_V_5_reg_979 & lshr_ln1148_1_fu_550_p2);

assign p_Result_11_fu_592_p3 = tmp_V_5_reg_979[add_ln1150_1_fu_587_p2];

assign p_Result_15_fu_313_p3 = {{1'd1}, {p_Result_s_fu_303_p4}};

assign p_Result_16_fu_775_p5 = {{zext_ln1163_fu_747_p1[63:32]}, {tmp_9_fu_768_p3}, {zext_ln1163_fu_747_p1[22:0]}};

assign p_Result_18_fu_377_p3 = {{1'd1}, {p_Result_8_fu_367_p4}};

assign p_Result_19_fu_819_p5 = {{zext_ln1163_1_fu_791_p1[63:32]}, {tmp_2_fu_812_p3}, {zext_ln1163_1_fu_791_p1[22:0]}};

assign p_Result_3_fu_451_p2 = (tmp_V_4_reg_941 & lshr_ln1148_fu_445_p2);

assign p_Result_4_fu_487_p3 = tmp_V_4_reg_941[add_ln1150_fu_482_p2];

integer ap_tvar_int_0;

always @ (tmp_V_5_fu_361_p3) begin
    for (ap_tvar_int_0 = 25 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 24 - 0) begin
            p_Result_8_fu_367_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_8_fu_367_p4[ap_tvar_int_0] = tmp_V_5_fu_361_p3[24 - ap_tvar_int_0];
        end
    end
end

integer ap_tvar_int_1;

always @ (tmp_V_4_fu_297_p3) begin
    for (ap_tvar_int_1 = 25 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 24 - 0) begin
            p_Result_s_fu_303_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            p_Result_s_fu_303_p4[ap_tvar_int_1] = tmp_V_4_fu_297_p3[24 - ap_tvar_int_1];
        end
    end
end

assign ret_V_6_fu_273_p2 = ($signed(sext_ln859_3_fu_269_p1) + $signed(sext_ln859_2_fu_265_p1));

assign ret_V_fu_251_p2 = ($signed(sext_ln859_1_fu_247_p1) + $signed(sext_ln859_fu_243_p1));

assign select_ln1144_1_fu_794_p3 = ((p_Result_12_reg_1047[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign select_ln1144_fu_750_p3 = ((p_Result_5_reg_1037[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign select_ln304_1_fu_858_p3 = ((icmp_ln1136_1_reg_974_pp0_iter8_reg[0:0] == 1'b1) ? 32'd0 : bitcast_ln304_fu_854_p1);

assign select_ln304_fu_847_p3 = ((icmp_ln1136_reg_936_pp0_iter8_reg[0:0] == 1'b1) ? 32'd0 : bitcast_ln304_1_fu_843_p1);

assign sext_ln1244_1_fu_385_p1 = $signed(p_Result_18_fu_377_p3);

assign sext_ln1244_fu_321_p1 = $signed(p_Result_15_fu_313_p3);

assign sext_ln859_1_fu_247_p1 = $signed(gb_M_real_V_q0);

assign sext_ln859_2_fu_265_p1 = $signed(ga_M_imag_V_q0);

assign sext_ln859_3_fu_269_p1 = $signed(gb_M_imag_V_q0);

assign sext_ln859_fu_243_p1 = $signed(ga_M_real_V_q0);

assign shl_ln1160_1_fu_707_p2 = zext_ln1158_1_fu_686_p1 << zext_ln1160_1_fu_704_p1;

assign shl_ln1160_fu_646_p2 = zext_ln1158_fu_625_p1 << zext_ln1160_fu_643_p1;

assign sub_ln1145_1_fu_397_p2 = (32'd25 - l_1_fu_389_p3);

assign sub_ln1145_fu_333_p2 = (32'd25 - l_fu_325_p3);

assign sub_ln1148_1_fu_541_p2 = ($signed(5'd18) - $signed(trunc_ln1148_1_reg_1002));

assign sub_ln1148_fu_436_p2 = ($signed(5'd18) - $signed(trunc_ln1148_reg_964));

assign sub_ln1165_1_fu_801_p2 = (8'd3 - trunc_ln1144_1_reg_1007_pp0_iter4_reg);

assign sub_ln1165_fu_757_p2 = (8'd3 - trunc_ln1144_reg_969_pp0_iter4_reg);

assign tmp_1_fu_468_p3 = lsb_index_fu_415_p2[32'd31];

assign tmp_2_fu_812_p3 = {{p_Result_17_reg_930_pp0_iter4_reg}, {add_ln1170_1_fu_806_p2}};

assign tmp_5_fu_525_p4 = {{lsb_index_1_fu_520_p2[31:1]}};

assign tmp_6_fu_573_p3 = lsb_index_1_fu_520_p2[32'd31];

assign tmp_9_fu_768_p3 = {{p_Result_14_reg_917_pp0_iter4_reg}, {add_ln1170_fu_762_p2}};

assign tmp_V_2_fu_356_p2 = (25'd0 - ret_V_6_reg_923);

assign tmp_V_4_fu_297_p3 = ((p_Result_14_reg_917[0:0] == 1'b1) ? tmp_V_fu_292_p2 : ret_V_reg_910);

assign tmp_V_5_fu_361_p3 = ((p_Result_17_reg_930[0:0] == 1'b1) ? tmp_V_2_fu_356_p2 : ret_V_6_reg_923);

assign tmp_V_fu_292_p2 = (25'd0 - ret_V_reg_910);

assign tmp_fu_420_p4 = {{lsb_index_fu_415_p2[31:1]}};

assign tmp_last_V_fu_232_p2 = ((ap_sig_allocacmp_i_2 == 11'd1023) ? 1'b1 : 1'b0);

assign trunc_ln1144_1_fu_411_p1 = l_1_fu_389_p3[7:0];

assign trunc_ln1144_fu_347_p1 = l_fu_325_p3[7:0];

assign trunc_ln1145_1_fu_403_p1 = sub_ln1145_1_fu_397_p2[24:0];

assign trunc_ln1145_fu_339_p1 = sub_ln1145_fu_333_p2[24:0];

assign trunc_ln1148_1_fu_407_p1 = sub_ln1145_1_fu_397_p2[4:0];

assign trunc_ln1148_fu_343_p1 = sub_ln1145_fu_333_p2[4:0];

assign xor_ln1150_1_fu_581_p2 = (tmp_6_fu_573_p3 ^ 1'd1);

assign xor_ln1150_fu_476_p2 = (tmp_1_fu_468_p3 ^ 1'd1);

assign zext_ln1148_1_fu_546_p1 = sub_ln1148_1_fu_541_p2;

assign zext_ln1148_fu_441_p1 = sub_ln1148_fu_436_p2;

assign zext_ln1158_1_fu_686_p1 = tmp_V_5_reg_979_pp0_iter3_reg;

assign zext_ln1158_fu_625_p1 = tmp_V_4_reg_941_pp0_iter3_reg;

assign zext_ln1159_1_fu_694_p1 = add_ln1159_1_fu_689_p2;

assign zext_ln1159_fu_633_p1 = add_ln1159_fu_628_p2;

assign zext_ln1160_1_fu_704_p1 = l_1_reg_986_pp0_iter3_reg;

assign zext_ln1160_fu_643_p1 = l_reg_948_pp0_iter3_reg;

assign zext_ln1162_1_fu_720_p1 = or_ln1150_1_reg_1022;

assign zext_ln1162_fu_659_p1 = or_ln_reg_1012;

assign zext_ln1163_1_fu_791_p1 = m_reg_1042;

assign zext_ln1163_fu_747_p1 = m_9_reg_1032;

always @ (posedge ap_clk) begin
    or_ln_reg_1012[1] <= 1'b0;
    or_ln1150_1_reg_1022[1] <= 1'b0;
end

endmodule //ifft_1024_top_ifft_1024_top_Pipeline_VITIS_LOOP_72_3
