-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft_1024_top_fft_fast_Pipeline_VITIS_LOOP_21_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m2 : IN STD_LOGIC_VECTOR (9 downto 0);
    trunc_ln20_1 : IN STD_LOGIC_VECTOR (9 downto 0);
    trunc_ln20_2 : IN STD_LOGIC_VECTOR (9 downto 0);
    x_M_real_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    x_M_real_ce0 : OUT STD_LOGIC;
    x_M_real_we0 : OUT STD_LOGIC;
    x_M_real_d0 : OUT STD_LOGIC_VECTOR (25 downto 0);
    x_M_real_q0 : IN STD_LOGIC_VECTOR (25 downto 0);
    x_M_real_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    x_M_real_ce1 : OUT STD_LOGIC;
    x_M_real_we1 : OUT STD_LOGIC;
    x_M_real_d1 : OUT STD_LOGIC_VECTOR (25 downto 0);
    x_M_real_q1 : IN STD_LOGIC_VECTOR (25 downto 0);
    x_M_imag_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    x_M_imag_ce0 : OUT STD_LOGIC;
    x_M_imag_we0 : OUT STD_LOGIC;
    x_M_imag_d0 : OUT STD_LOGIC_VECTOR (25 downto 0);
    x_M_imag_q0 : IN STD_LOGIC_VECTOR (25 downto 0);
    x_M_imag_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    x_M_imag_ce1 : OUT STD_LOGIC;
    x_M_imag_we1 : OUT STD_LOGIC;
    x_M_imag_d1 : OUT STD_LOGIC_VECTOR (25 downto 0);
    x_M_imag_q1 : IN STD_LOGIC_VECTOR (25 downto 0) );
end;


architecture behav of fft_1024_top_fft_fast_Pipeline_VITIS_LOOP_21_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln21_fu_158_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_block_state6_pp0_stage5_iter0 : BOOLEAN;
    signal tw_M_real_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal tw_M_real_V_ce0 : STD_LOGIC;
    signal tw_M_real_V_q0 : STD_LOGIC_VECTOR (23 downto 0);
    signal tw_M_imag_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal tw_M_imag_V_ce0 : STD_LOGIC;
    signal tw_M_imag_V_q0 : STD_LOGIC_VECTOR (23 downto 0);
    signal x_M_real_addr_reg_331 : STD_LOGIC_VECTOR (9 downto 0);
    signal x_M_imag_addr_reg_336 : STD_LOGIC_VECTOR (9 downto 0);
    signal x_M_real_addr_2_reg_341 : STD_LOGIC_VECTOR (9 downto 0);
    signal x_M_imag_addr_2_reg_346 : STD_LOGIC_VECTOR (9 downto 0);
    signal tw_M_real_V_load_reg_351 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal tw_M_imag_V_load_reg_356 : STD_LOGIC_VECTOR (23 downto 0);
    signal x_M_real_load_reg_361 : STD_LOGIC_VECTOR (25 downto 0);
    signal x_M_imag_load_reg_366 : STD_LOGIC_VECTOR (25 downto 0);
    signal u_M_real_V_reg_371 : STD_LOGIC_VECTOR (25 downto 0);
    signal u_M_imag_V_reg_377 : STD_LOGIC_VECTOR (25 downto 0);
    signal r_V_1_fu_232_p2 : STD_LOGIC_VECTOR (49 downto 0);
    signal r_V_1_reg_383 : STD_LOGIC_VECTOR (49 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal r_V_3_fu_245_p2 : STD_LOGIC_VECTOR (49 downto 0);
    signal r_V_3_reg_388 : STD_LOGIC_VECTOR (49 downto 0);
    signal r_V_4_fu_251_p2 : STD_LOGIC_VECTOR (49 downto 0);
    signal r_V_4_reg_393 : STD_LOGIC_VECTOR (49 downto 0);
    signal r_V_5_fu_257_p2 : STD_LOGIC_VECTOR (49 downto 0);
    signal r_V_5_reg_398 : STD_LOGIC_VECTOR (49 downto 0);
    signal tm_re_V_reg_403 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_block_state4_pp0_stage3_iter0 : BOOLEAN;
    signal tm_im_V_reg_409 : STD_LOGIC_VECTOR (25 downto 0);
    signal zext_ln883_fu_176_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln24_1_fu_200_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln24_fu_188_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_52 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln21_fu_164_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_block_state5_pp0_stage4_iter0 : BOOLEAN;
    signal add_ln22_fu_170_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln24_fu_182_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln24_1_fu_194_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tw_re_fu_211_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal r_V_1_fu_232_p0 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1319_fu_229_p1 : STD_LOGIC_VECTOR (49 downto 0);
    signal r_V_1_fu_232_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1316_fu_225_p1 : STD_LOGIC_VECTOR (49 downto 0);
    signal tw_im_V_fu_218_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal r_V_3_fu_245_p0 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1319_1_fu_242_p1 : STD_LOGIC_VECTOR (49 downto 0);
    signal r_V_3_fu_245_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1316_1_fu_238_p1 : STD_LOGIC_VECTOR (49 downto 0);
    signal r_V_4_fu_251_p0 : STD_LOGIC_VECTOR (25 downto 0);
    signal r_V_4_fu_251_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal r_V_5_fu_257_p0 : STD_LOGIC_VECTOR (25 downto 0);
    signal r_V_5_fu_257_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal ret_V_fu_263_p2 : STD_LOGIC_VECTOR (49 downto 0);
    signal ret_V_1_fu_277_p2 : STD_LOGIC_VECTOR (49 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fft_1024_top_mul_26s_26s_50_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (25 downto 0);
        din1 : IN STD_LOGIC_VECTOR (25 downto 0);
        dout : OUT STD_LOGIC_VECTOR (49 downto 0) );
    end component;


    component fft_1024_top_fft_fast_Pipeline_VITIS_LOOP_21_4_tw_M_real_V_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component fft_1024_top_fft_fast_Pipeline_VITIS_LOOP_21_4_tw_M_imag_V_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component fft_1024_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    tw_M_real_V_U : component fft_1024_top_fft_fast_Pipeline_VITIS_LOOP_21_4_tw_M_real_V_ROM_AUTO_1R
    generic map (
        DataWidth => 24,
        AddressRange => 1023,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => tw_M_real_V_address0,
        ce0 => tw_M_real_V_ce0,
        q0 => tw_M_real_V_q0);

    tw_M_imag_V_U : component fft_1024_top_fft_fast_Pipeline_VITIS_LOOP_21_4_tw_M_imag_V_ROM_AUTO_1R
    generic map (
        DataWidth => 24,
        AddressRange => 1023,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => tw_M_imag_V_address0,
        ce0 => tw_M_imag_V_ce0,
        q0 => tw_M_imag_V_q0);

    mul_26s_26s_50_1_1_U24 : component fft_1024_top_mul_26s_26s_50_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 26,
        din1_WIDTH => 26,
        dout_WIDTH => 50)
    port map (
        din0 => r_V_1_fu_232_p0,
        din1 => r_V_1_fu_232_p1,
        dout => r_V_1_fu_232_p2);

    mul_26s_26s_50_1_1_U25 : component fft_1024_top_mul_26s_26s_50_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 26,
        din1_WIDTH => 26,
        dout_WIDTH => 50)
    port map (
        din0 => r_V_3_fu_245_p0,
        din1 => r_V_3_fu_245_p1,
        dout => r_V_3_fu_245_p2);

    mul_26s_26s_50_1_1_U26 : component fft_1024_top_mul_26s_26s_50_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 26,
        din1_WIDTH => 26,
        dout_WIDTH => 50)
    port map (
        din0 => r_V_4_fu_251_p0,
        din1 => r_V_4_fu_251_p1,
        dout => r_V_4_fu_251_p2);

    mul_26s_26s_50_1_1_U27 : component fft_1024_top_mul_26s_26s_50_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 26,
        din1_WIDTH => 26,
        dout_WIDTH => 50)
    port map (
        din0 => r_V_5_fu_257_p0,
        din1 => r_V_5_fu_257_p1,
        dout => r_V_5_fu_257_p2);

    flow_control_loop_pipe_sequential_init_U : component fft_1024_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    j_fu_52_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln21_fu_158_p2 = ap_const_lv1_0)) then 
                    j_fu_52 <= add_ln21_fu_164_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_52 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                r_V_1_reg_383 <= r_V_1_fu_232_p2;
                r_V_3_reg_388 <= r_V_3_fu_245_p2;
                r_V_4_reg_393 <= r_V_4_fu_251_p2;
                r_V_5_reg_398 <= r_V_5_fu_257_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                tm_im_V_reg_409 <= ret_V_1_fu_277_p2(49 downto 24);
                tm_re_V_reg_403 <= ret_V_fu_263_p2(49 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                tw_M_imag_V_load_reg_356 <= tw_M_imag_V_q0;
                tw_M_real_V_load_reg_351 <= tw_M_real_V_q0;
                u_M_imag_V_reg_377 <= x_M_imag_q0;
                u_M_real_V_reg_371 <= x_M_real_q0;
                x_M_imag_load_reg_366 <= x_M_imag_q1;
                x_M_real_load_reg_361 <= x_M_real_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln21_fu_158_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                x_M_imag_addr_2_reg_346 <= zext_ln24_fu_188_p1(10 - 1 downto 0);
                x_M_imag_addr_reg_336 <= zext_ln24_1_fu_200_p1(10 - 1 downto 0);
                x_M_real_addr_2_reg_341 <= zext_ln24_fu_188_p1(10 - 1 downto 0);
                x_M_real_addr_reg_331 <= zext_ln24_1_fu_200_p1(10 - 1 downto 0);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, icmp_ln21_fu_158_p2, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln21_fu_158_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln21_fu_164_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_1) + unsigned(ap_const_lv10_1));
    add_ln22_fu_170_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_1) + unsigned(trunc_ln20_1));
    add_ln24_1_fu_194_p2 <= std_logic_vector(unsigned(add_ln24_fu_182_p2) + unsigned(m2));
    add_ln24_fu_182_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_1) + unsigned(trunc_ln20_2));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start_int)
    begin
        if ((ap_start_int = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;

        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage2_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage3_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage4_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage5_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_158_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_158_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_1_assign_proc : process(ap_CS_fsm_state1, j_fu_52, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j_1 <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_j_1 <= j_fu_52;
        end if; 
    end process;

    icmp_ln21_fu_158_p2 <= "1" when (ap_sig_allocacmp_j_1 = m2) else "0";
    r_V_1_fu_232_p0 <= sext_ln1319_fu_229_p1(26 - 1 downto 0);
    r_V_1_fu_232_p1 <= sext_ln1316_fu_225_p1(26 - 1 downto 0);
    r_V_3_fu_245_p0 <= sext_ln1319_1_fu_242_p1(26 - 1 downto 0);
    r_V_3_fu_245_p1 <= sext_ln1316_1_fu_238_p1(26 - 1 downto 0);
    r_V_4_fu_251_p0 <= sext_ln1319_1_fu_242_p1(26 - 1 downto 0);
    r_V_4_fu_251_p1 <= sext_ln1316_fu_225_p1(26 - 1 downto 0);
    r_V_5_fu_257_p0 <= sext_ln1316_1_fu_238_p1(26 - 1 downto 0);
    r_V_5_fu_257_p1 <= sext_ln1319_fu_229_p1(26 - 1 downto 0);
    ret_V_1_fu_277_p2 <= std_logic_vector(unsigned(r_V_4_reg_393) + unsigned(r_V_5_reg_398));
    ret_V_fu_263_p2 <= std_logic_vector(unsigned(r_V_1_reg_383) - unsigned(r_V_3_reg_388));
        sext_ln1316_1_fu_238_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tw_im_V_fu_218_p3),50));

        sext_ln1316_fu_225_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tw_re_fu_211_p3),50));

        sext_ln1319_1_fu_242_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_M_imag_load_reg_366),50));

        sext_ln1319_fu_229_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_M_real_load_reg_361),50));

    tw_M_imag_V_address0 <= zext_ln883_fu_176_p1(10 - 1 downto 0);

    tw_M_imag_V_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            tw_M_imag_V_ce0 <= ap_const_logic_1;
        else 
            tw_M_imag_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    tw_M_real_V_address0 <= zext_ln883_fu_176_p1(10 - 1 downto 0);

    tw_M_real_V_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            tw_M_real_V_ce0 <= ap_const_logic_1;
        else 
            tw_M_real_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    tw_im_V_fu_218_p3 <= (tw_M_imag_V_load_reg_356 & ap_const_lv2_0);
    tw_re_fu_211_p3 <= (tw_M_real_V_load_reg_351 & ap_const_lv2_0);

    x_M_imag_address0_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_158_p2, x_M_imag_addr_2_reg_346, zext_ln24_fu_188_p1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            x_M_imag_address0 <= x_M_imag_addr_2_reg_346;
        elsif (((icmp_ln21_fu_158_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            x_M_imag_address0 <= zext_ln24_fu_188_p1(10 - 1 downto 0);
        else 
            x_M_imag_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    x_M_imag_address1_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_158_p2, ap_CS_fsm_state6, x_M_imag_addr_reg_336, zext_ln24_1_fu_200_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_M_imag_address1 <= x_M_imag_addr_reg_336;
        elsif (((icmp_ln21_fu_158_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            x_M_imag_address1 <= zext_ln24_1_fu_200_p1(10 - 1 downto 0);
        else 
            x_M_imag_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    x_M_imag_ce0_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_158_p2, ap_CS_fsm_state5, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((icmp_ln21_fu_158_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            x_M_imag_ce0 <= ap_const_logic_1;
        else 
            x_M_imag_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    x_M_imag_ce1_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_158_p2, ap_CS_fsm_state6, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or ((icmp_ln21_fu_158_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            x_M_imag_ce1 <= ap_const_logic_1;
        else 
            x_M_imag_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    x_M_imag_d0 <= std_logic_vector(unsigned(u_M_imag_V_reg_377) + unsigned(tm_im_V_reg_409));
    x_M_imag_d1 <= std_logic_vector(unsigned(u_M_imag_V_reg_377) - unsigned(tm_im_V_reg_409));

    x_M_imag_we0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            x_M_imag_we0 <= ap_const_logic_1;
        else 
            x_M_imag_we0 <= ap_const_logic_0;
        end if; 
    end process;


    x_M_imag_we1_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_M_imag_we1 <= ap_const_logic_1;
        else 
            x_M_imag_we1 <= ap_const_logic_0;
        end if; 
    end process;


    x_M_real_address0_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_158_p2, x_M_real_addr_2_reg_341, zext_ln24_fu_188_p1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            x_M_real_address0 <= x_M_real_addr_2_reg_341;
        elsif (((icmp_ln21_fu_158_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            x_M_real_address0 <= zext_ln24_fu_188_p1(10 - 1 downto 0);
        else 
            x_M_real_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    x_M_real_address1_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_158_p2, ap_CS_fsm_state6, x_M_real_addr_reg_331, zext_ln24_1_fu_200_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_M_real_address1 <= x_M_real_addr_reg_331;
        elsif (((icmp_ln21_fu_158_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            x_M_real_address1 <= zext_ln24_1_fu_200_p1(10 - 1 downto 0);
        else 
            x_M_real_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    x_M_real_ce0_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_158_p2, ap_CS_fsm_state5, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((icmp_ln21_fu_158_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            x_M_real_ce0 <= ap_const_logic_1;
        else 
            x_M_real_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    x_M_real_ce1_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_158_p2, ap_CS_fsm_state6, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or ((icmp_ln21_fu_158_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            x_M_real_ce1 <= ap_const_logic_1;
        else 
            x_M_real_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    x_M_real_d0 <= std_logic_vector(unsigned(u_M_real_V_reg_371) + unsigned(tm_re_V_reg_403));
    x_M_real_d1 <= std_logic_vector(unsigned(u_M_real_V_reg_371) - unsigned(tm_re_V_reg_403));

    x_M_real_we0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            x_M_real_we0 <= ap_const_logic_1;
        else 
            x_M_real_we0 <= ap_const_logic_0;
        end if; 
    end process;


    x_M_real_we1_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_M_real_we1 <= ap_const_logic_1;
        else 
            x_M_real_we1 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln24_1_fu_200_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln24_1_fu_194_p2),64));
    zext_ln24_fu_188_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln24_fu_182_p2),64));
    zext_ln883_fu_176_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln22_fu_170_p2),64));
end behav;
