-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft_1024_top_fft_fast is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x_M_real_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    x_M_real_ce0 : OUT STD_LOGIC;
    x_M_real_we0 : OUT STD_LOGIC;
    x_M_real_d0 : OUT STD_LOGIC_VECTOR (25 downto 0);
    x_M_real_q0 : IN STD_LOGIC_VECTOR (25 downto 0);
    x_M_real_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    x_M_real_ce1 : OUT STD_LOGIC;
    x_M_real_we1 : OUT STD_LOGIC;
    x_M_real_d1 : OUT STD_LOGIC_VECTOR (25 downto 0);
    x_M_real_q1 : IN STD_LOGIC_VECTOR (25 downto 0);
    x_M_imag_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    x_M_imag_ce0 : OUT STD_LOGIC;
    x_M_imag_we0 : OUT STD_LOGIC;
    x_M_imag_d0 : OUT STD_LOGIC_VECTOR (25 downto 0);
    x_M_imag_q0 : IN STD_LOGIC_VECTOR (25 downto 0);
    x_M_imag_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    x_M_imag_ce1 : OUT STD_LOGIC;
    x_M_imag_we1 : OUT STD_LOGIC;
    x_M_imag_d1 : OUT STD_LOGIC_VECTOR (25 downto 0);
    x_M_imag_q1 : IN STD_LOGIC_VECTOR (25 downto 0) );
end;


architecture behav of fft_1024_top_fft_fast is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv54_1 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000000000000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal m2_fu_122_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal m2_reg_209 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln17_fu_106_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln19_fu_132_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln19_reg_214 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln20_fu_136_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln20_reg_219 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln20_fu_140_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_reg_224 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln20_1_fu_160_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln20_1_reg_232 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln20_fu_154_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln20_fu_164_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln20_reg_237 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_ap_start : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_ap_done : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_ap_idle : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_ap_ready : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_ce0 : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_we0 : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_d0 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_ce1 : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_we1 : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_d1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_ce0 : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_we0 : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_d0 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_ce1 : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_we1 : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_d1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_ap_start : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_ap_done : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_ap_idle : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_ap_ready : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_ce0 : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_we0 : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_d0 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_ce1 : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_we1 : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_d1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_ce0 : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_we0 : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_d0 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_ce1 : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_we1 : STD_LOGIC;
    signal grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_d1 : STD_LOGIC_VECTOR (25 downto 0);
    signal k_reg_54 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ti_fu_46 : STD_LOGIC_VECTOR (12 downto 0);
    signal ti_1_fu_169_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal s_fu_50 : STD_LOGIC_VECTOR (3 downto 0);
    signal s_3_fu_174_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln17_fu_112_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal m_fu_116_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_fu_144_p4 : STD_LOGIC_VECTOR (53 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fft_1024_top_fft_fast_Pipeline_VITIS_LOOP_7_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        x_M_real_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        x_M_real_ce0 : OUT STD_LOGIC;
        x_M_real_we0 : OUT STD_LOGIC;
        x_M_real_d0 : OUT STD_LOGIC_VECTOR (25 downto 0);
        x_M_real_q0 : IN STD_LOGIC_VECTOR (25 downto 0);
        x_M_real_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        x_M_real_ce1 : OUT STD_LOGIC;
        x_M_real_we1 : OUT STD_LOGIC;
        x_M_real_d1 : OUT STD_LOGIC_VECTOR (25 downto 0);
        x_M_real_q1 : IN STD_LOGIC_VECTOR (25 downto 0);
        x_M_imag_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        x_M_imag_ce0 : OUT STD_LOGIC;
        x_M_imag_we0 : OUT STD_LOGIC;
        x_M_imag_d0 : OUT STD_LOGIC_VECTOR (25 downto 0);
        x_M_imag_q0 : IN STD_LOGIC_VECTOR (25 downto 0);
        x_M_imag_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        x_M_imag_ce1 : OUT STD_LOGIC;
        x_M_imag_we1 : OUT STD_LOGIC;
        x_M_imag_d1 : OUT STD_LOGIC_VECTOR (25 downto 0);
        x_M_imag_q1 : IN STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component fft_1024_top_fft_fast_Pipeline_VITIS_LOOP_21_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m2 : IN STD_LOGIC_VECTOR (9 downto 0);
        trunc_ln20_1 : IN STD_LOGIC_VECTOR (9 downto 0);
        trunc_ln20_2 : IN STD_LOGIC_VECTOR (9 downto 0);
        x_M_real_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        x_M_real_ce0 : OUT STD_LOGIC;
        x_M_real_we0 : OUT STD_LOGIC;
        x_M_real_d0 : OUT STD_LOGIC_VECTOR (25 downto 0);
        x_M_real_q0 : IN STD_LOGIC_VECTOR (25 downto 0);
        x_M_real_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        x_M_real_ce1 : OUT STD_LOGIC;
        x_M_real_we1 : OUT STD_LOGIC;
        x_M_real_d1 : OUT STD_LOGIC_VECTOR (25 downto 0);
        x_M_real_q1 : IN STD_LOGIC_VECTOR (25 downto 0);
        x_M_imag_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        x_M_imag_ce0 : OUT STD_LOGIC;
        x_M_imag_we0 : OUT STD_LOGIC;
        x_M_imag_d0 : OUT STD_LOGIC_VECTOR (25 downto 0);
        x_M_imag_q0 : IN STD_LOGIC_VECTOR (25 downto 0);
        x_M_imag_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        x_M_imag_ce1 : OUT STD_LOGIC;
        x_M_imag_we1 : OUT STD_LOGIC;
        x_M_imag_d1 : OUT STD_LOGIC_VECTOR (25 downto 0);
        x_M_imag_q1 : IN STD_LOGIC_VECTOR (25 downto 0) );
    end component;



begin
    grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65 : component fft_1024_top_fft_fast_Pipeline_VITIS_LOOP_7_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_ap_start,
        ap_done => grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_ap_done,
        ap_idle => grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_ap_idle,
        ap_ready => grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_ap_ready,
        x_M_real_address0 => grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_address0,
        x_M_real_ce0 => grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_ce0,
        x_M_real_we0 => grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_we0,
        x_M_real_d0 => grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_d0,
        x_M_real_q0 => x_M_real_q0,
        x_M_real_address1 => grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_address1,
        x_M_real_ce1 => grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_ce1,
        x_M_real_we1 => grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_we1,
        x_M_real_d1 => grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_d1,
        x_M_real_q1 => x_M_real_q1,
        x_M_imag_address0 => grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_address0,
        x_M_imag_ce0 => grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_ce0,
        x_M_imag_we0 => grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_we0,
        x_M_imag_d0 => grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_d0,
        x_M_imag_q0 => x_M_imag_q0,
        x_M_imag_address1 => grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_address1,
        x_M_imag_ce1 => grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_ce1,
        x_M_imag_we1 => grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_we1,
        x_M_imag_d1 => grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_d1,
        x_M_imag_q1 => x_M_imag_q1);

    grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75 : component fft_1024_top_fft_fast_Pipeline_VITIS_LOOP_21_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_ap_start,
        ap_done => grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_ap_done,
        ap_idle => grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_ap_idle,
        ap_ready => grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_ap_ready,
        m2 => m2_reg_209,
        trunc_ln20_1 => trunc_ln20_reg_219,
        trunc_ln20_2 => trunc_ln20_1_reg_232,
        x_M_real_address0 => grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_address0,
        x_M_real_ce0 => grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_ce0,
        x_M_real_we0 => grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_we0,
        x_M_real_d0 => grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_d0,
        x_M_real_q0 => x_M_real_q0,
        x_M_real_address1 => grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_address1,
        x_M_real_ce1 => grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_ce1,
        x_M_real_we1 => grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_we1,
        x_M_real_d1 => grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_d1,
        x_M_real_q1 => x_M_real_q1,
        x_M_imag_address0 => grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_address0,
        x_M_imag_ce0 => grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_ce0,
        x_M_imag_we0 => grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_we0,
        x_M_imag_d0 => grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_d0,
        x_M_imag_q0 => x_M_imag_q0,
        x_M_imag_address1 => grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_address1,
        x_M_imag_ce1 => grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_ce1,
        x_M_imag_we1 => grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_we1,
        x_M_imag_d1 => grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_d1,
        x_M_imag_q1 => x_M_imag_q1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_ap_ready = ap_const_logic_1)) then 
                    grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_ap_ready = ap_const_logic_1)) then 
                    grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    k_reg_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln17_fu_106_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                k_reg_54 <= ap_const_lv64_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_ap_done = ap_const_logic_1))) then 
                k_reg_54 <= add_ln20_reg_237;
            end if; 
        end if;
    end process;

    s_fu_50_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                s_fu_50 <= ap_const_lv4_1;
            elsif (((icmp_ln20_fu_154_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                s_fu_50 <= s_3_fu_174_p2;
            end if; 
        end if;
    end process;

    ti_fu_46_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                ti_fu_46 <= ap_const_lv13_0;
            elsif (((icmp_ln20_fu_154_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                ti_fu_46 <= ti_1_fu_169_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_fu_154_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                add_ln20_reg_237 <= add_ln20_fu_164_p2;
                trunc_ln20_1_reg_232 <= trunc_ln20_1_fu_160_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln17_fu_106_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                m2_reg_209 <= m_fu_116_p2(10 downto 1);
                trunc_ln20_reg_219 <= trunc_ln20_fu_136_p1;
                    zext_ln19_reg_214(9 downto 0) <= zext_ln19_fu_132_p1(9 downto 0);
                    zext_ln20_reg_224(10 downto 0) <= zext_ln20_fu_140_p1(10 downto 0);
            end if;
        end if;
    end process;
    zext_ln19_reg_214(12 downto 10) <= "000";
    zext_ln20_reg_224(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, icmp_ln17_fu_106_p2, ap_CS_fsm_state4, icmp_ln20_fu_154_p2, grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_ap_done, grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_ap_done, ap_CS_fsm_state6, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln17_fu_106_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln20_fu_154_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln20_fu_164_p2 <= std_logic_vector(unsigned(zext_ln20_reg_224) + unsigned(k_reg_54));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_ap_done)
    begin
        if ((grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_ap_done)
    begin
        if ((grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state3, icmp_ln17_fu_106_p2)
    begin
        if ((((icmp_ln17_fu_106_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, icmp_ln17_fu_106_p2)
    begin
        if (((icmp_ln17_fu_106_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_ap_start <= grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_ap_start_reg;
    grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_ap_start <= grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_ap_start_reg;
    icmp_ln17_fu_106_p2 <= "1" when (s_fu_50 = ap_const_lv4_B) else "0";
    icmp_ln20_fu_154_p2 <= "1" when (signed(tmp_fu_144_p4) < signed(ap_const_lv54_1)) else "0";
    m2_fu_122_p4 <= m_fu_116_p2(10 downto 1);
    m_fu_116_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv11_1),to_integer(unsigned('0' & zext_ln17_fu_112_p1(11-1 downto 0)))));
    s_3_fu_174_p2 <= std_logic_vector(unsigned(s_fu_50) + unsigned(ap_const_lv4_1));
    ti_1_fu_169_p2 <= std_logic_vector(unsigned(zext_ln19_reg_214) + unsigned(ti_fu_46));
    tmp_fu_144_p4 <= k_reg_54(63 downto 10);
    trunc_ln20_1_fu_160_p1 <= k_reg_54(10 - 1 downto 0);
    trunc_ln20_fu_136_p1 <= ti_fu_46(10 - 1 downto 0);

    x_M_imag_address0_assign_proc : process(grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_address0, grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_address0, ap_CS_fsm_state6, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_M_imag_address0 <= grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_M_imag_address0 <= grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_address0;
        else 
            x_M_imag_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    x_M_imag_address1_assign_proc : process(grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_address1, grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_address1, ap_CS_fsm_state6, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_M_imag_address1 <= grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_M_imag_address1 <= grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_address1;
        else 
            x_M_imag_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    x_M_imag_ce0_assign_proc : process(grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_ce0, grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_ce0, ap_CS_fsm_state6, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_M_imag_ce0 <= grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_M_imag_ce0 <= grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_ce0;
        else 
            x_M_imag_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    x_M_imag_ce1_assign_proc : process(grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_ce1, grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_ce1, ap_CS_fsm_state6, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_M_imag_ce1 <= grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_M_imag_ce1 <= grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_ce1;
        else 
            x_M_imag_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    x_M_imag_d0_assign_proc : process(grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_d0, grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_d0, ap_CS_fsm_state6, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_M_imag_d0 <= grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_M_imag_d0 <= grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_d0;
        else 
            x_M_imag_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    x_M_imag_d1_assign_proc : process(grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_d1, grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_d1, ap_CS_fsm_state6, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_M_imag_d1 <= grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_d1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_M_imag_d1 <= grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_d1;
        else 
            x_M_imag_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    x_M_imag_we0_assign_proc : process(grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_we0, grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_we0, ap_CS_fsm_state6, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_M_imag_we0 <= grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_M_imag_we0 <= grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_we0;
        else 
            x_M_imag_we0 <= ap_const_logic_0;
        end if; 
    end process;


    x_M_imag_we1_assign_proc : process(grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_we1, grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_we1, ap_CS_fsm_state6, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_M_imag_we1 <= grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_imag_we1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_M_imag_we1 <= grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_imag_we1;
        else 
            x_M_imag_we1 <= ap_const_logic_0;
        end if; 
    end process;


    x_M_real_address0_assign_proc : process(grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_address0, grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_address0, ap_CS_fsm_state6, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_M_real_address0 <= grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_M_real_address0 <= grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_address0;
        else 
            x_M_real_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    x_M_real_address1_assign_proc : process(grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_address1, grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_address1, ap_CS_fsm_state6, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_M_real_address1 <= grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_M_real_address1 <= grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_address1;
        else 
            x_M_real_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    x_M_real_ce0_assign_proc : process(grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_ce0, grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_ce0, ap_CS_fsm_state6, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_M_real_ce0 <= grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_M_real_ce0 <= grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_ce0;
        else 
            x_M_real_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    x_M_real_ce1_assign_proc : process(grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_ce1, grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_ce1, ap_CS_fsm_state6, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_M_real_ce1 <= grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_M_real_ce1 <= grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_ce1;
        else 
            x_M_real_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    x_M_real_d0_assign_proc : process(grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_d0, grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_d0, ap_CS_fsm_state6, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_M_real_d0 <= grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_M_real_d0 <= grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_d0;
        else 
            x_M_real_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    x_M_real_d1_assign_proc : process(grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_d1, grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_d1, ap_CS_fsm_state6, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_M_real_d1 <= grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_d1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_M_real_d1 <= grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_d1;
        else 
            x_M_real_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    x_M_real_we0_assign_proc : process(grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_we0, grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_we0, ap_CS_fsm_state6, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_M_real_we0 <= grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_M_real_we0 <= grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_we0;
        else 
            x_M_real_we0 <= ap_const_logic_0;
        end if; 
    end process;


    x_M_real_we1_assign_proc : process(grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_we1, grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_we1, ap_CS_fsm_state6, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_M_real_we1 <= grp_fft_fast_Pipeline_VITIS_LOOP_21_4_fu_75_x_M_real_we1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_M_real_we1 <= grp_fft_fast_Pipeline_VITIS_LOOP_7_1_fu_65_x_M_real_we1;
        else 
            x_M_real_we1 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln17_fu_112_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(s_fu_50),11));
    zext_ln19_fu_132_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(m2_fu_122_p4),13));
    zext_ln20_fu_140_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(m_fu_116_p2),64));
end behav;
