// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="doppler_fft_256_doppler_fft_256,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.221929,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=7,HLS_SYN_DSP=0,HLS_SYN_FF=3361,HLS_SYN_LUT=6924,HLS_VERSION=2022_1}" *)

module doppler_fft_256 (
        ap_clk,
        ap_rst_n,
        input_r_TDATA,
        input_r_TVALID,
        input_r_TREADY,
        input_r_TKEEP,
        input_r_TSTRB,
        input_r_TLAST,
        output_r_TDATA,
        output_r_TVALID,
        output_r_TREADY,
        output_r_TKEEP,
        output_r_TSTRB,
        output_r_TLAST
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst_n;
input  [63:0] input_r_TDATA;
input   input_r_TVALID;
output   input_r_TREADY;
input  [7:0] input_r_TKEEP;
input  [7:0] input_r_TSTRB;
input  [0:0] input_r_TLAST;
output  [63:0] output_r_TDATA;
output   output_r_TVALID;
input   output_r_TREADY;
output  [7:0] output_r_TKEEP;
output  [7:0] output_r_TSTRB;
output  [0:0] output_r_TLAST;

 reg    ap_rst_n_inv;
reg   [7:0] buf_M_real_V_address0;
reg    buf_M_real_V_ce0;
reg    buf_M_real_V_we0;
reg   [18:0] buf_M_real_V_d0;
wire   [18:0] buf_M_real_V_q0;
reg   [7:0] buf_M_real_V_address1;
reg    buf_M_real_V_ce1;
reg    buf_M_real_V_we1;
reg   [18:0] buf_M_real_V_d1;
wire   [18:0] buf_M_real_V_q1;
reg   [7:0] buf_M_imag_V_address0;
reg    buf_M_imag_V_ce0;
reg    buf_M_imag_V_we0;
reg   [18:0] buf_M_imag_V_d0;
wire   [18:0] buf_M_imag_V_q0;
reg   [7:0] buf_M_imag_V_address1;
reg    buf_M_imag_V_ce1;
reg    buf_M_imag_V_we1;
reg   [18:0] buf_M_imag_V_d1;
wire   [18:0] buf_M_imag_V_q1;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_ap_start;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_ap_done;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_ap_idle;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_ap_ready;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_input_r_TREADY;
wire   [7:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_real_V_address0;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_real_V_ce0;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_real_V_we0;
wire   [18:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_real_V_d0;
wire   [7:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_imag_V_address0;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_imag_V_ce0;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_imag_V_we0;
wire   [18:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_imag_V_d0;
wire   [31:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_110_p_din0;
wire   [31:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_110_p_din1;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_110_p_ce;
wire   [31:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_114_p_din0;
wire   [31:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_114_p_din1;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_114_p_ce;
wire   [31:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_118_p_din0;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_118_p_ce;
wire    grp_fft_fast_fu_78_ap_start;
wire    grp_fft_fast_fu_78_ap_done;
wire    grp_fft_fast_fu_78_ap_idle;
wire    grp_fft_fast_fu_78_ap_ready;
wire   [7:0] grp_fft_fast_fu_78_x_M_real_address0;
wire    grp_fft_fast_fu_78_x_M_real_ce0;
wire    grp_fft_fast_fu_78_x_M_real_we0;
wire   [18:0] grp_fft_fast_fu_78_x_M_real_d0;
wire   [7:0] grp_fft_fast_fu_78_x_M_real_address1;
wire    grp_fft_fast_fu_78_x_M_real_ce1;
wire    grp_fft_fast_fu_78_x_M_real_we1;
wire   [18:0] grp_fft_fast_fu_78_x_M_real_d1;
wire   [7:0] grp_fft_fast_fu_78_x_M_imag_address0;
wire    grp_fft_fast_fu_78_x_M_imag_ce0;
wire    grp_fft_fast_fu_78_x_M_imag_we0;
wire   [18:0] grp_fft_fast_fu_78_x_M_imag_d0;
wire   [7:0] grp_fft_fast_fu_78_x_M_imag_address1;
wire    grp_fft_fast_fu_78_x_M_imag_ce1;
wire    grp_fft_fast_fu_78_x_M_imag_we1;
wire   [18:0] grp_fft_fast_fu_78_x_M_imag_d1;
wire   [31:0] grp_fft_fast_fu_78_grp_fu_118_p_din0;
wire    grp_fft_fast_fu_78_grp_fu_118_p_ce;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_ap_start;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_ap_done;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_ap_idle;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_ap_ready;
wire   [7:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_address0;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_ce0;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_we0;
wire   [18:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_d0;
wire   [7:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_address1;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_ce1;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_we1;
wire   [18:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_d1;
wire   [7:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_address0;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_ce0;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_we0;
wire   [18:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_d0;
wire   [7:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_address1;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_ce1;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_we1;
wire   [18:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_d1;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_ap_start;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_ap_done;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_ap_idle;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_ap_ready;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TREADY;
wire   [7:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_buf_M_real_V_address0;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_buf_M_real_V_ce0;
wire   [7:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_buf_M_imag_V_address0;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_buf_M_imag_V_ce0;
wire   [63:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TDATA;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TVALID;
wire   [7:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TKEEP;
wire   [7:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TSTRB;
wire   [0:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TLAST;
wire   [31:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_grp_fu_110_p_din0;
wire   [31:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_grp_fu_110_p_din1;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_grp_fu_110_p_ce;
wire   [31:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_grp_fu_114_p_din0;
wire   [31:0] grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_grp_fu_114_p_din1;
wire    grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_grp_fu_114_p_ce;
reg    grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_ap_start_reg;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_fft_fast_fu_78_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire   [31:0] grp_fu_110_p2;
reg   [31:0] grp_fu_110_p0;
reg   [31:0] grp_fu_110_p1;
reg    grp_fu_110_ce;
wire   [31:0] grp_fu_114_p2;
reg   [31:0] grp_fu_114_p0;
reg   [31:0] grp_fu_114_p1;
reg    grp_fu_114_ce;
wire   [63:0] grp_fu_118_p1;
reg   [31:0] grp_fu_118_p0;
reg    grp_fu_118_ce;
reg   [9:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    regslice_both_output_r_V_data_V_U_apdone_blk;
wire    ap_CS_fsm_state10;
wire    regslice_both_input_r_V_data_V_U_apdone_blk;
wire   [63:0] input_r_TDATA_int_regslice;
wire    input_r_TVALID_int_regslice;
reg    input_r_TREADY_int_regslice;
wire    regslice_both_input_r_V_data_V_U_ack_in;
wire    regslice_both_input_r_V_keep_V_U_apdone_blk;
wire   [7:0] input_r_TKEEP_int_regslice;
wire    regslice_both_input_r_V_keep_V_U_vld_out;
wire    regslice_both_input_r_V_keep_V_U_ack_in;
wire    regslice_both_input_r_V_strb_V_U_apdone_blk;
wire   [7:0] input_r_TSTRB_int_regslice;
wire    regslice_both_input_r_V_strb_V_U_vld_out;
wire    regslice_both_input_r_V_strb_V_U_ack_in;
wire    regslice_both_input_r_V_last_V_U_apdone_blk;
wire   [0:0] input_r_TLAST_int_regslice;
wire    regslice_both_input_r_V_last_V_U_vld_out;
wire    regslice_both_input_r_V_last_V_U_ack_in;
wire    output_r_TVALID_int_regslice;
wire    output_r_TREADY_int_regslice;
wire    regslice_both_output_r_V_data_V_U_vld_out;
wire    regslice_both_output_r_V_keep_V_U_apdone_blk;
wire    regslice_both_output_r_V_keep_V_U_ack_in_dummy;
wire    regslice_both_output_r_V_keep_V_U_vld_out;
wire    regslice_both_output_r_V_strb_V_U_apdone_blk;
wire    regslice_both_output_r_V_strb_V_U_ack_in_dummy;
wire    regslice_both_output_r_V_strb_V_U_vld_out;
wire    regslice_both_output_r_V_last_V_U_apdone_blk;
wire    regslice_both_output_r_V_last_V_U_ack_in_dummy;
wire    regslice_both_output_r_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_ap_start_reg = 1'b0;
#0 ap_CS_fsm = 10'd1;
#0 grp_fft_fast_fu_78_ap_start_reg = 1'b0;
#0 grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_ap_start_reg = 1'b0;
#0 grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_ap_start_reg = 1'b0;
end

doppler_fft_256_buf_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 19 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
buf_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buf_M_real_V_address0),
    .ce0(buf_M_real_V_ce0),
    .we0(buf_M_real_V_we0),
    .d0(buf_M_real_V_d0),
    .q0(buf_M_real_V_q0),
    .address1(buf_M_real_V_address1),
    .ce1(buf_M_real_V_ce1),
    .we1(buf_M_real_V_we1),
    .d1(buf_M_real_V_d1),
    .q1(buf_M_real_V_q1)
);

doppler_fft_256_buf_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 19 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
buf_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buf_M_imag_V_address0),
    .ce0(buf_M_imag_V_ce0),
    .we0(buf_M_imag_V_we0),
    .d0(buf_M_imag_V_d0),
    .q0(buf_M_imag_V_q0),
    .address1(buf_M_imag_V_address1),
    .ce1(buf_M_imag_V_ce1),
    .we1(buf_M_imag_V_we1),
    .d1(buf_M_imag_V_d1),
    .q1(buf_M_imag_V_q1)
);

doppler_fft_256_doppler_fft_256_Pipeline_VITIS_LOOP_65_1 grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_ap_start),
    .ap_done(grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_ap_done),
    .ap_idle(grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_ap_idle),
    .ap_ready(grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_ap_ready),
    .input_r_TVALID(input_r_TVALID_int_regslice),
    .input_r_TDATA(input_r_TDATA_int_regslice),
    .input_r_TREADY(grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_input_r_TREADY),
    .input_r_TKEEP(input_r_TKEEP_int_regslice),
    .input_r_TSTRB(input_r_TSTRB_int_regslice),
    .input_r_TLAST(input_r_TLAST_int_regslice),
    .buf_M_real_V_address0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_real_V_address0),
    .buf_M_real_V_ce0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_real_V_ce0),
    .buf_M_real_V_we0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_real_V_we0),
    .buf_M_real_V_d0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_real_V_d0),
    .buf_M_imag_V_address0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_imag_V_address0),
    .buf_M_imag_V_ce0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_imag_V_ce0),
    .buf_M_imag_V_we0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_imag_V_we0),
    .buf_M_imag_V_d0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_imag_V_d0),
    .grp_fu_110_p_din0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_110_p_din0),
    .grp_fu_110_p_din1(grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_110_p_din1),
    .grp_fu_110_p_dout0(grp_fu_110_p2),
    .grp_fu_110_p_ce(grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_110_p_ce),
    .grp_fu_114_p_din0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_114_p_din0),
    .grp_fu_114_p_din1(grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_114_p_din1),
    .grp_fu_114_p_dout0(grp_fu_114_p2),
    .grp_fu_114_p_ce(grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_114_p_ce),
    .grp_fu_118_p_din0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_118_p_din0),
    .grp_fu_118_p_dout0(grp_fu_118_p1),
    .grp_fu_118_p_ce(grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_118_p_ce)
);

doppler_fft_256_fft_fast grp_fft_fast_fu_78(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_fft_fast_fu_78_ap_start),
    .ap_done(grp_fft_fast_fu_78_ap_done),
    .ap_idle(grp_fft_fast_fu_78_ap_idle),
    .ap_ready(grp_fft_fast_fu_78_ap_ready),
    .x_M_real_address0(grp_fft_fast_fu_78_x_M_real_address0),
    .x_M_real_ce0(grp_fft_fast_fu_78_x_M_real_ce0),
    .x_M_real_we0(grp_fft_fast_fu_78_x_M_real_we0),
    .x_M_real_d0(grp_fft_fast_fu_78_x_M_real_d0),
    .x_M_real_q0(buf_M_real_V_q0),
    .x_M_real_address1(grp_fft_fast_fu_78_x_M_real_address1),
    .x_M_real_ce1(grp_fft_fast_fu_78_x_M_real_ce1),
    .x_M_real_we1(grp_fft_fast_fu_78_x_M_real_we1),
    .x_M_real_d1(grp_fft_fast_fu_78_x_M_real_d1),
    .x_M_real_q1(buf_M_real_V_q1),
    .x_M_imag_address0(grp_fft_fast_fu_78_x_M_imag_address0),
    .x_M_imag_ce0(grp_fft_fast_fu_78_x_M_imag_ce0),
    .x_M_imag_we0(grp_fft_fast_fu_78_x_M_imag_we0),
    .x_M_imag_d0(grp_fft_fast_fu_78_x_M_imag_d0),
    .x_M_imag_q0(buf_M_imag_V_q0),
    .x_M_imag_address1(grp_fft_fast_fu_78_x_M_imag_address1),
    .x_M_imag_ce1(grp_fft_fast_fu_78_x_M_imag_ce1),
    .x_M_imag_we1(grp_fft_fast_fu_78_x_M_imag_we1),
    .x_M_imag_d1(grp_fft_fast_fu_78_x_M_imag_d1),
    .x_M_imag_q1(buf_M_imag_V_q1),
    .grp_fu_118_p_din0(grp_fft_fast_fu_78_grp_fu_118_p_din0),
    .grp_fu_118_p_dout0(grp_fu_118_p1),
    .grp_fu_118_p_ce(grp_fft_fast_fu_78_grp_fu_118_p_ce)
);

doppler_fft_256_doppler_fft_256_Pipeline_VITIS_LOOP_49_1 grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_ap_start),
    .ap_done(grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_ap_done),
    .ap_idle(grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_ap_idle),
    .ap_ready(grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_ap_ready),
    .buf_M_real_V_address0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_address0),
    .buf_M_real_V_ce0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_ce0),
    .buf_M_real_V_we0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_we0),
    .buf_M_real_V_d0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_d0),
    .buf_M_real_V_q0(buf_M_real_V_q0),
    .buf_M_real_V_address1(grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_address1),
    .buf_M_real_V_ce1(grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_ce1),
    .buf_M_real_V_we1(grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_we1),
    .buf_M_real_V_d1(grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_d1),
    .buf_M_real_V_q1(buf_M_real_V_q1),
    .buf_M_imag_V_address0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_address0),
    .buf_M_imag_V_ce0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_ce0),
    .buf_M_imag_V_we0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_we0),
    .buf_M_imag_V_d0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_d0),
    .buf_M_imag_V_q0(buf_M_imag_V_q0),
    .buf_M_imag_V_address1(grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_address1),
    .buf_M_imag_V_ce1(grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_ce1),
    .buf_M_imag_V_we1(grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_we1),
    .buf_M_imag_V_d1(grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_d1),
    .buf_M_imag_V_q1(buf_M_imag_V_q1)
);

doppler_fft_256_doppler_fft_256_Pipeline_VITIS_LOOP_74_2 grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_ap_start),
    .ap_done(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_ap_done),
    .ap_idle(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_ap_idle),
    .ap_ready(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_ap_ready),
    .output_r_TREADY(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TREADY),
    .buf_M_real_V_address0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_buf_M_real_V_address0),
    .buf_M_real_V_ce0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_buf_M_real_V_ce0),
    .buf_M_real_V_q0(buf_M_real_V_q0),
    .buf_M_imag_V_address0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_buf_M_imag_V_address0),
    .buf_M_imag_V_ce0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_buf_M_imag_V_ce0),
    .buf_M_imag_V_q0(buf_M_imag_V_q0),
    .output_r_TDATA(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TDATA),
    .output_r_TVALID(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TVALID),
    .output_r_TKEEP(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TKEEP),
    .output_r_TSTRB(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TSTRB),
    .output_r_TLAST(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TLAST),
    .grp_fu_110_p_din0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_grp_fu_110_p_din0),
    .grp_fu_110_p_din1(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_grp_fu_110_p_din1),
    .grp_fu_110_p_dout0(grp_fu_110_p2),
    .grp_fu_110_p_ce(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_grp_fu_110_p_ce),
    .grp_fu_114_p_din0(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_grp_fu_114_p_din0),
    .grp_fu_114_p_din1(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_grp_fu_114_p_din1),
    .grp_fu_114_p_dout0(grp_fu_114_p2),
    .grp_fu_114_p_ce(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_grp_fu_114_p_ce)
);

doppler_fft_256_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U41(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_110_p0),
    .din1(grp_fu_110_p1),
    .ce(grp_fu_110_ce),
    .dout(grp_fu_110_p2)
);

doppler_fft_256_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U42(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_114_p0),
    .din1(grp_fu_114_p1),
    .ce(grp_fu_114_ce),
    .dout(grp_fu_114_p2)
);

doppler_fft_256_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U43(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_118_p0),
    .ce(grp_fu_118_ce),
    .dout(grp_fu_118_p1)
);

doppler_fft_256_regslice_both #(
    .DataWidth( 64 ))
regslice_both_input_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TDATA),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_data_V_U_ack_in),
    .data_out(input_r_TDATA_int_regslice),
    .vld_out(input_r_TVALID_int_regslice),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_data_V_U_apdone_blk)
);

doppler_fft_256_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TKEEP),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_keep_V_U_ack_in),
    .data_out(input_r_TKEEP_int_regslice),
    .vld_out(regslice_both_input_r_V_keep_V_U_vld_out),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_keep_V_U_apdone_blk)
);

doppler_fft_256_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TSTRB),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_strb_V_U_ack_in),
    .data_out(input_r_TSTRB_int_regslice),
    .vld_out(regslice_both_input_r_V_strb_V_U_vld_out),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_strb_V_U_apdone_blk)
);

doppler_fft_256_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TLAST),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_last_V_U_ack_in),
    .data_out(input_r_TLAST_int_regslice),
    .vld_out(regslice_both_input_r_V_last_V_U_vld_out),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_last_V_U_apdone_blk)
);

doppler_fft_256_regslice_both #(
    .DataWidth( 64 ))
regslice_both_output_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TDATA),
    .vld_in(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TVALID),
    .ack_in(output_r_TREADY_int_regslice),
    .data_out(output_r_TDATA),
    .vld_out(regslice_both_output_r_V_data_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_data_V_U_apdone_blk)
);

doppler_fft_256_regslice_both #(
    .DataWidth( 8 ))
regslice_both_output_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TKEEP),
    .vld_in(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TVALID),
    .ack_in(regslice_both_output_r_V_keep_V_U_ack_in_dummy),
    .data_out(output_r_TKEEP),
    .vld_out(regslice_both_output_r_V_keep_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_keep_V_U_apdone_blk)
);

doppler_fft_256_regslice_both #(
    .DataWidth( 8 ))
regslice_both_output_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TSTRB),
    .vld_in(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TVALID),
    .ack_in(regslice_both_output_r_V_strb_V_U_ack_in_dummy),
    .data_out(output_r_TSTRB),
    .vld_out(regslice_both_output_r_V_strb_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_strb_V_U_apdone_blk)
);

doppler_fft_256_regslice_both #(
    .DataWidth( 1 ))
regslice_both_output_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TLAST),
    .vld_in(grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TVALID),
    .ack_in(regslice_both_output_r_V_last_V_U_ack_in_dummy),
    .data_out(output_r_TLAST),
    .vld_out(regslice_both_output_r_V_last_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_ap_start_reg <= 1'b1;
        end else if ((grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_ap_ready == 1'b1)) begin
            grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_ap_start_reg <= 1'b1;
        end else if ((grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_ap_ready == 1'b1)) begin
            grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_ap_start_reg <= 1'b1;
        end else if ((grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_ap_ready == 1'b1)) begin
            grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_fft_fast_fu_78_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_fft_fast_fu_78_ap_start_reg <= 1'b1;
        end else if ((grp_fft_fast_fu_78_ap_ready == 1'b1)) begin
            grp_fft_fast_fu_78_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_fft_fast_fu_78_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_M_imag_V_address0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_buf_M_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_M_imag_V_address0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_M_imag_V_address0 = grp_fft_fast_fu_78_x_M_imag_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_M_imag_V_address0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_imag_V_address0;
    end else begin
        buf_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_M_imag_V_address1 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_M_imag_V_address1 = grp_fft_fast_fu_78_x_M_imag_address1;
    end else begin
        buf_M_imag_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_M_imag_V_ce0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_buf_M_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_M_imag_V_ce0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_M_imag_V_ce0 = grp_fft_fast_fu_78_x_M_imag_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_M_imag_V_ce0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_imag_V_ce0;
    end else begin
        buf_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_M_imag_V_ce1 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_M_imag_V_ce1 = grp_fft_fast_fu_78_x_M_imag_ce1;
    end else begin
        buf_M_imag_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_M_imag_V_d0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_M_imag_V_d0 = grp_fft_fast_fu_78_x_M_imag_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_M_imag_V_d0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_imag_V_d0;
    end else begin
        buf_M_imag_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_M_imag_V_d1 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_d1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_M_imag_V_d1 = grp_fft_fast_fu_78_x_M_imag_d1;
    end else begin
        buf_M_imag_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_M_imag_V_we0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_M_imag_V_we0 = grp_fft_fast_fu_78_x_M_imag_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_M_imag_V_we0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_imag_V_we0;
    end else begin
        buf_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_M_imag_V_we1 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_imag_V_we1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_M_imag_V_we1 = grp_fft_fast_fu_78_x_M_imag_we1;
    end else begin
        buf_M_imag_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_M_real_V_address0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_buf_M_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_M_real_V_address0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_M_real_V_address0 = grp_fft_fast_fu_78_x_M_real_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_M_real_V_address0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_real_V_address0;
    end else begin
        buf_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_M_real_V_address1 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_M_real_V_address1 = grp_fft_fast_fu_78_x_M_real_address1;
    end else begin
        buf_M_real_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_M_real_V_ce0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_buf_M_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_M_real_V_ce0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_M_real_V_ce0 = grp_fft_fast_fu_78_x_M_real_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_M_real_V_ce0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_real_V_ce0;
    end else begin
        buf_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_M_real_V_ce1 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_M_real_V_ce1 = grp_fft_fast_fu_78_x_M_real_ce1;
    end else begin
        buf_M_real_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_M_real_V_d0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_M_real_V_d0 = grp_fft_fast_fu_78_x_M_real_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_M_real_V_d0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_real_V_d0;
    end else begin
        buf_M_real_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_M_real_V_d1 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_d1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_M_real_V_d1 = grp_fft_fast_fu_78_x_M_real_d1;
    end else begin
        buf_M_real_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_M_real_V_we0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_M_real_V_we0 = grp_fft_fast_fu_78_x_M_real_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_M_real_V_we0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_buf_M_real_V_we0;
    end else begin
        buf_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_M_real_V_we1 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_buf_M_real_V_we1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_M_real_V_we1 = grp_fft_fast_fu_78_x_M_real_we1;
    end else begin
        buf_M_real_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_110_ce = grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_grp_fu_110_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_110_ce = grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_110_p_ce;
    end else begin
        grp_fu_110_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_110_p0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_grp_fu_110_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_110_p0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_110_p_din0;
    end else begin
        grp_fu_110_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_110_p1 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_grp_fu_110_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_110_p1 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_110_p_din1;
    end else begin
        grp_fu_110_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_114_ce = grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_grp_fu_114_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_114_ce = grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_114_p_ce;
    end else begin
        grp_fu_114_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_114_p0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_grp_fu_114_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_114_p0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_114_p_din0;
    end else begin
        grp_fu_114_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_114_p1 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_grp_fu_114_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_114_p1 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_114_p_din1;
    end else begin
        grp_fu_114_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_118_ce = grp_fft_fast_fu_78_grp_fu_118_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_118_ce = grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_118_p_ce;
    end else begin
        grp_fu_118_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_118_p0 = grp_fft_fast_fu_78_grp_fu_118_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_118_p0 = grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_grp_fu_118_p_din0;
    end else begin
        grp_fu_118_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_r_TREADY_int_regslice = grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_input_r_TREADY;
    end else begin
        input_r_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_fft_fast_fu_78_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((regslice_both_output_r_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_ap_start = grp_doppler_fft_256_Pipeline_VITIS_LOOP_49_1_fu_90_ap_start_reg;

assign grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_ap_start = grp_doppler_fft_256_Pipeline_VITIS_LOOP_65_1_fu_64_ap_start_reg;

assign grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_ap_start = grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_ap_start_reg;

assign grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TREADY = (output_r_TREADY_int_regslice & ap_CS_fsm_state9);

assign grp_fft_fast_fu_78_ap_start = grp_fft_fast_fu_78_ap_start_reg;

assign input_r_TREADY = regslice_both_input_r_V_data_V_U_ack_in;

assign output_r_TVALID = regslice_both_output_r_V_data_V_U_vld_out;

assign output_r_TVALID_int_regslice = grp_doppler_fft_256_Pipeline_VITIS_LOOP_74_2_fu_96_output_r_TVALID;

endmodule //doppler_fft_256
