-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft_1024_top_fft_fast_Pipeline_VITIS_LOOP_22_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m2 : IN STD_LOGIC_VECTOR (9 downto 0);
    trunc_ln21_1 : IN STD_LOGIC_VECTOR (9 downto 0);
    trunc_ln21_2 : IN STD_LOGIC_VECTOR (9 downto 0);
    x_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    x_0_ce0 : OUT STD_LOGIC;
    x_0_we0 : OUT STD_LOGIC;
    x_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    x_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_0_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    x_0_ce1 : OUT STD_LOGIC;
    x_0_we1 : OUT STD_LOGIC;
    x_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    x_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    x_1_ce0 : OUT STD_LOGIC;
    x_1_we0 : OUT STD_LOGIC;
    x_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    x_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    x_1_ce1 : OUT STD_LOGIC;
    x_1_we1 : OUT STD_LOGIC;
    x_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    x_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of fft_1024_top_fft_fast_Pipeline_VITIS_LOOP_22_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (17 downto 0) := "000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (17 downto 0) := "000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (17 downto 0) := "000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (17 downto 0) := "000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (17 downto 0) := "000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (17 downto 0) := "000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (17 downto 0) := "000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (17 downto 0) := "000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (17 downto 0) := "000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (17 downto 0) := "001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (17 downto 0) := "010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (17 downto 0) := "100000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln22_fu_184_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal ap_block_state18_pp0_stage17_iter0 : BOOLEAN;
    signal tw_M_value_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal tw_M_value_1_ce0 : STD_LOGIC;
    signal tw_M_value_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal tw_M_value_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal tw_M_value_ce0 : STD_LOGIC;
    signal tw_M_value_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_140_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_164 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_block_state11_pp0_stage10_iter0 : BOOLEAN;
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal ap_block_state17_pp0_stage16_iter0 : BOOLEAN;
    signal grp_fu_144_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_170 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_0_addr_reg_257 : STD_LOGIC_VECTOR (9 downto 0);
    signal x_1_addr_reg_262 : STD_LOGIC_VECTOR (9 downto 0);
    signal x_0_addr_2_reg_267 : STD_LOGIC_VECTOR (9 downto 0);
    signal x_1_addr_2_reg_272 : STD_LOGIC_VECTOR (9 downto 0);
    signal tw_M_value_2_reg_277 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal tw_M_value_3_reg_283 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_t_reg_289 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_t_1_reg_295 : STD_LOGIC_VECTOR (31 downto 0);
    signal u_M_value_reg_301 : STD_LOGIC_VECTOR (31 downto 0);
    signal u_M_value_2_reg_306 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_148_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ac_i_i_reg_311 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_block_state6_pp0_stage5_iter0 : BOOLEAN;
    signal grp_fu_152_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_bd_i_i_reg_316 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_156_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ad_i_i_reg_321 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_160_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_bc_i_i_reg_326 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_r_M_value_2_reg_331 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal ap_block_state16_pp0_stage15_iter0 : BOOLEAN;
    signal p_r_M_value_3_reg_336 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln23_fu_202_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1097_fu_226_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln388_fu_214_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_42 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln22_fu_190_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_140_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_140_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal grp_fu_144_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_144_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln23_fu_196_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln24_fu_208_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln1097_fu_220_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_140_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_state12_pp0_stage11_iter0 : BOOLEAN;
    signal ap_block_state7_pp0_stage6_iter0 : BOOLEAN;
    signal ap_block_state13_pp0_stage12_iter0 : BOOLEAN;
    signal grp_fu_144_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_block_state4_pp0_stage3_iter0 : BOOLEAN;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_block_state5_pp0_stage4_iter0 : BOOLEAN;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_block_state8_pp0_stage7_iter0 : BOOLEAN;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_block_state9_pp0_stage8_iter0 : BOOLEAN;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_block_state10_pp0_stage9_iter0 : BOOLEAN;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_block_state14_pp0_stage13_iter0 : BOOLEAN;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_block_state15_pp0_stage14_iter0 : BOOLEAN;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fft_1024_top_faddfsub_32ns_32ns_32_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fft_1024_top_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fft_1024_top_fft_fast_Pipeline_VITIS_LOOP_22_4_tw_M_value_1_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fft_1024_top_fft_fast_Pipeline_VITIS_LOOP_22_4_tw_M_value_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fft_1024_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    tw_M_value_1_U : component fft_1024_top_fft_fast_Pipeline_VITIS_LOOP_22_4_tw_M_value_1_ROM_AUTO_1R
    generic map (
        DataWidth => 32,
        AddressRange => 1023,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => tw_M_value_1_address0,
        ce0 => tw_M_value_1_ce0,
        q0 => tw_M_value_1_q0);

    tw_M_value_U : component fft_1024_top_fft_fast_Pipeline_VITIS_LOOP_22_4_tw_M_value_ROM_AUTO_1R
    generic map (
        DataWidth => 32,
        AddressRange => 1023,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => tw_M_value_address0,
        ce0 => tw_M_value_ce0,
        q0 => tw_M_value_q0);

    faddfsub_32ns_32ns_32_5_full_dsp_1_U20 : component fft_1024_top_faddfsub_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_140_p0,
        din1 => grp_fu_140_p1,
        opcode => grp_fu_140_opcode,
        ce => ap_const_logic_1,
        dout => grp_fu_140_p2);

    faddfsub_32ns_32ns_32_5_full_dsp_1_U21 : component fft_1024_top_faddfsub_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_144_p0,
        din1 => grp_fu_144_p1,
        opcode => grp_fu_144_opcode,
        ce => ap_const_logic_1,
        dout => grp_fu_144_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U22 : component fft_1024_top_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tw_M_value_2_reg_277,
        din1 => p_t_reg_289,
        ce => ap_const_logic_1,
        dout => grp_fu_148_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U23 : component fft_1024_top_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tw_M_value_3_reg_283,
        din1 => p_t_1_reg_295,
        ce => ap_const_logic_1,
        dout => grp_fu_152_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U24 : component fft_1024_top_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tw_M_value_2_reg_277,
        din1 => p_t_1_reg_295,
        ce => ap_const_logic_1,
        dout => grp_fu_156_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U25 : component fft_1024_top_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tw_M_value_3_reg_283,
        din1 => p_t_reg_289,
        ce => ap_const_logic_1,
        dout => grp_fu_160_p2);

    flow_control_loop_pipe_sequential_init_U : component fft_1024_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    j_fu_42_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln22_fu_184_p2 = ap_const_lv1_0)) then 
                    j_fu_42 <= add_ln22_fu_190_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_42 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                mul_ac_i_i_reg_311 <= grp_fu_148_p2;
                mul_ad_i_i_reg_321 <= grp_fu_156_p2;
                mul_bc_i_i_reg_326 <= grp_fu_160_p2;
                mul_bd_i_i_reg_316 <= grp_fu_152_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
                p_r_M_value_2_reg_331 <= grp_fu_140_p2;
                p_r_M_value_3_reg_336 <= grp_fu_144_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                p_t_1_reg_295 <= x_1_q1;
                p_t_reg_289 <= x_0_q1;
                tw_M_value_2_reg_277 <= tw_M_value_1_q0;
                tw_M_value_3_reg_283 <= tw_M_value_q0;
                u_M_value_2_reg_306 <= x_1_q0;
                u_M_value_reg_301 <= x_0_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state11))) then
                reg_164 <= grp_fu_140_p2;
                reg_170 <= grp_fu_144_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln22_fu_184_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                x_0_addr_2_reg_267 <= zext_ln388_fu_214_p1(10 - 1 downto 0);
                x_0_addr_reg_257 <= zext_ln1097_fu_226_p1(10 - 1 downto 0);
                x_1_addr_2_reg_272 <= zext_ln388_fu_214_p1(10 - 1 downto 0);
                x_1_addr_reg_262 <= zext_ln1097_fu_226_p1(10 - 1 downto 0);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, icmp_ln22_fu_184_p2, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln22_fu_184_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln1097_fu_220_p2 <= std_logic_vector(unsigned(add_ln24_fu_208_p2) + unsigned(m2));
    add_ln22_fu_190_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_1) + unsigned(ap_const_lv10_1));
    add_ln23_fu_196_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_1) + unsigned(trunc_ln21_1));
    add_ln24_fu_208_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_1) + unsigned(trunc_ln21_2));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start_int)
    begin
        if ((ap_start_int = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;
        ap_block_state10_pp0_stage9_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage10_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage11_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage12_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage13_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage14_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage15_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage16_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage17_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;

        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage2_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage3_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage4_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage5_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage6_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage7_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage8_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, icmp_ln22_fu_184_p2, ap_start_int)
    begin
        if (((icmp_ln22_fu_184_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_1_assign_proc : process(ap_CS_fsm_state1, j_fu_42, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j_1 <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_j_1 <= j_fu_42;
        end if; 
    end process;


    grp_fu_140_opcode_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state12, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            grp_fu_140_opcode <= ap_const_lv2_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_140_opcode <= ap_const_lv2_0;
        else 
            grp_fu_140_opcode <= "XX";
        end if; 
    end process;


    grp_fu_140_p0_assign_proc : process(u_M_value_reg_301, mul_ac_i_i_reg_311, ap_CS_fsm_state7, ap_CS_fsm_state12, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            grp_fu_140_p0 <= u_M_value_reg_301;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_140_p0 <= mul_ac_i_i_reg_311;
        else 
            grp_fu_140_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_140_p1_assign_proc : process(reg_164, mul_bd_i_i_reg_316, ap_CS_fsm_state7, ap_CS_fsm_state12, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            grp_fu_140_p1 <= reg_164;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_140_p1 <= mul_bd_i_i_reg_316;
        else 
            grp_fu_140_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_144_opcode_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state12, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_fu_144_opcode <= ap_const_lv2_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            grp_fu_144_opcode <= ap_const_lv2_0;
        else 
            grp_fu_144_opcode <= "XX";
        end if; 
    end process;


    grp_fu_144_p0_assign_proc : process(u_M_value_2_reg_306, mul_ad_i_i_reg_321, ap_CS_fsm_state7, ap_CS_fsm_state12, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            grp_fu_144_p0 <= u_M_value_2_reg_306;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_144_p0 <= mul_ad_i_i_reg_321;
        else 
            grp_fu_144_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_144_p1_assign_proc : process(reg_170, mul_bc_i_i_reg_326, ap_CS_fsm_state7, ap_CS_fsm_state12, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            grp_fu_144_p1 <= reg_170;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_144_p1 <= mul_bc_i_i_reg_326;
        else 
            grp_fu_144_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln22_fu_184_p2 <= "1" when (ap_sig_allocacmp_j_1 = m2) else "0";
    tw_M_value_1_address0 <= zext_ln23_fu_202_p1(10 - 1 downto 0);

    tw_M_value_1_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            tw_M_value_1_ce0 <= ap_const_logic_1;
        else 
            tw_M_value_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    tw_M_value_address0 <= zext_ln23_fu_202_p1(10 - 1 downto 0);

    tw_M_value_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            tw_M_value_ce0 <= ap_const_logic_1;
        else 
            tw_M_value_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    x_0_address0_assign_proc : process(ap_CS_fsm_state1, icmp_ln22_fu_184_p2, ap_CS_fsm_state17, x_0_addr_2_reg_267, zext_ln388_fu_214_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            x_0_address0 <= x_0_addr_2_reg_267;
        elsif (((icmp_ln22_fu_184_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            x_0_address0 <= zext_ln388_fu_214_p1(10 - 1 downto 0);
        else 
            x_0_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    x_0_address1_assign_proc : process(ap_CS_fsm_state1, icmp_ln22_fu_184_p2, ap_CS_fsm_state18, x_0_addr_reg_257, zext_ln1097_fu_226_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            x_0_address1 <= x_0_addr_reg_257;
        elsif (((icmp_ln22_fu_184_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            x_0_address1 <= zext_ln1097_fu_226_p1(10 - 1 downto 0);
        else 
            x_0_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    x_0_ce0_assign_proc : process(ap_CS_fsm_state1, icmp_ln22_fu_184_p2, ap_CS_fsm_state17, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state17) or ((icmp_ln22_fu_184_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            x_0_ce0 <= ap_const_logic_1;
        else 
            x_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    x_0_ce1_assign_proc : process(ap_CS_fsm_state1, icmp_ln22_fu_184_p2, ap_CS_fsm_state18, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state18) or ((icmp_ln22_fu_184_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            x_0_ce1 <= ap_const_logic_1;
        else 
            x_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    x_0_d0 <= p_r_M_value_2_reg_331;
    x_0_d1 <= reg_164;

    x_0_we0_assign_proc : process(ap_CS_fsm_state17)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            x_0_we0 <= ap_const_logic_1;
        else 
            x_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    x_0_we1_assign_proc : process(ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            x_0_we1 <= ap_const_logic_1;
        else 
            x_0_we1 <= ap_const_logic_0;
        end if; 
    end process;


    x_1_address0_assign_proc : process(ap_CS_fsm_state1, icmp_ln22_fu_184_p2, ap_CS_fsm_state17, x_1_addr_2_reg_272, zext_ln388_fu_214_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            x_1_address0 <= x_1_addr_2_reg_272;
        elsif (((icmp_ln22_fu_184_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            x_1_address0 <= zext_ln388_fu_214_p1(10 - 1 downto 0);
        else 
            x_1_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    x_1_address1_assign_proc : process(ap_CS_fsm_state1, icmp_ln22_fu_184_p2, ap_CS_fsm_state18, x_1_addr_reg_262, zext_ln1097_fu_226_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            x_1_address1 <= x_1_addr_reg_262;
        elsif (((icmp_ln22_fu_184_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            x_1_address1 <= zext_ln1097_fu_226_p1(10 - 1 downto 0);
        else 
            x_1_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    x_1_ce0_assign_proc : process(ap_CS_fsm_state1, icmp_ln22_fu_184_p2, ap_CS_fsm_state17, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state17) or ((icmp_ln22_fu_184_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            x_1_ce0 <= ap_const_logic_1;
        else 
            x_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    x_1_ce1_assign_proc : process(ap_CS_fsm_state1, icmp_ln22_fu_184_p2, ap_CS_fsm_state18, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state18) or ((icmp_ln22_fu_184_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            x_1_ce1 <= ap_const_logic_1;
        else 
            x_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    x_1_d0 <= p_r_M_value_3_reg_336;
    x_1_d1 <= reg_170;

    x_1_we0_assign_proc : process(ap_CS_fsm_state17)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            x_1_we0 <= ap_const_logic_1;
        else 
            x_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    x_1_we1_assign_proc : process(ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            x_1_we1 <= ap_const_logic_1;
        else 
            x_1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln1097_fu_226_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1097_fu_220_p2),64));
    zext_ln23_fu_202_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln23_fu_196_p2),64));
    zext_ln388_fu_214_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln24_fu_208_p2),64));
end behav;
